### ISSUE TITLE
Missing neuron-device-plugin Dockerfile

### ISSUE THREAD

**Issue by RobertLucian** [aws/aws-neuron-sdk#102]
It appears that there's no provided Dockerfile for the `790709498068.dkr.ecr.us-east-1.amazonaws.com/neuron-device-plugin:latest` image. 

In production, I don't want to resort to using the latest version every time, because that can break the underlying software product.

Is there a Dockerfile for this image that I could use?

**Comment by mrnikwaws** [comment]
Hi Robert,

Thanks for you feedback.  Publishing the Dockerfile seems to make a lot of sense, and we are working to make that available via Github.  In the meantime here is a list of the existing tags for the neuron-device-plugin image so that you can pin your version.  

We are also looking into making the repository ListImages permission publicly available so that you can see the available images yourself for pinning.

```
{
    "imageIds": [
        {
            "imageDigest": "sha256:e50e216eb5f85ee459e98ecad40ca78056f80579af4f51859a0bf2e1d36e1981",
            "imageTag": "1.0.6554.0"
        },
        {
            "imageDigest": "sha256:e50e216eb5f85ee459e98ecad40ca78056f80579af4f51859a0bf2e1d36e1981",
            "imageTag": "latest"
        },
        {
            "imageDigest": "sha256:257f8bcf3dcdde9eb3d7db444ec91634cd51ce02916add8a3a8657b0be0fecc0",
            "imageTag": "1.0.4587.0"
        },
        {
            "imageDigest": "sha256:c5917f371860dc737e20544fe9e31a08a1970fe8376b08359134fa2ab6526a23",
            "imageTag": "1.0.4250.0"
        },
        {
            "imageDigest": "sha256:674661754c0d40f1a588d9a55f4e473cf1697872c44f905dde919f6c4b1deccb",
            "imageTag": "1.0.5165.0"
        },
        {
            "imageDigest": "sha256:fc25e4878ee1cdf09534f4a7c75e185ff33ca6f410466743f3361e75d9e42f00",
            "imageTag": "1.0.5832.0"
        }
    ]
}
```

**Comment by RobertLucian** [comment]
I see. If not for the Dockerfile, then at least for the tags. I really need a way to guarantee the version that's pulled in, so I'm really happy you shared the available tags. 

Thanks a lot! This will be enough.

**Comment by RobertLucian** [comment]
@mrnikwaws just tried this the previous days:
```bash
$ eval $(aws ecr get-login --no-include-email --region us-east-1)
$ docker pull 790709498068.dkr.ecr.us-east-1.amazonaws.com/neuron-device-plugin:latest
```

And I get an error saying that I either don't have the credentials to do this or the image doesn't exist. I know I was able to pull this image a month / 2 months ago using the same account, but it no longer works.

Any idea if the image got moved somewhere else?
