### ISSUE TITLE
Can't run inference on a batch larger then 1 (resnet-50 tutorial)

### ISSUE THREAD

**Issue by ebochkov** [aws/aws-neuron-sdk#106]
I successfully reproduced [Getting started with torch-neuron](https://github.com/aws/aws-neuron-sdk/blob/master/docs/pytorch-neuron/tutorial-compile-infer.md) tutorial. However, when I tried to run inference step on batch size greater then 1, I got following error:
```
Traceback (most recent call last):
  File "pytorch_infer_resnet50.py", line 50, in <module>
    results = model_neuron( image )
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
RuntimeError: nrt infer_wait failed in nrtd
The above operation failed in interpreter, with the following stack trace:
at code/__torch__/torch_neuron/decorators.py:7:9
op_version_set = 1
class NeuronModule(Module):
  __parameters__ = []
  training : bool
  def forward(self: __torch__.torch_neuron.decorators.NeuronModule,
    argument_1: Tensor) -> Tensor:
    _0 = ops.neuron.forward_1([argument_1], CONSTANTS.c0, CONSTANTS.c1, CONSTANTS.c2)
         ~~~~~~~~~~~~~~~~~~~~ <--- HERE
    return _0
Compiled from code /home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch_neuron/decorators.py(245): forward
/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch/nn/modules/module.py(525): _slow_forward
/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch/nn/modules/module.py(539): __call__
/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch/jit/__init__.py(997): trace_module
/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch/jit/__init__.py(858): trace
/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch_neuron/decorators.py(259): trace
pytorch_trace_resnet50.py(14): <module>
```
The only change in the code was made:
```
#image, _ = eval_dataset[0]
#image = torch.tensor(image.numpy()[np.newaxis, ...])

batch_size = 2 # works when batch_size = 1
image = torch.tensor(np.array([eval_dataset[0][0].numpy()] * batch_size))
```

I used ```aws_neuron_pytorch_p36``` Conda environment.

```
pip show torch_neuron
Name: torch-neuron
Version: 1.0.763.0
Summary: UNKNOWN
Home-page: UNKNOWN
Author: AWS
Author-email: UNKNOWN
License: Proprietary
Location: /home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages
Requires: torch-neuron-base
Required-by:
```

**Comment by mrnikwaws** [comment]
Hi ebochkov,

Thanks for the feedback.  Unfortunately this is a known issue the team is working on: https://github.com/aws/aws-neuron-sdk/blob/master/docs/technotes/performance-tuning.md#compiling-for-batching-optimization (note 2).  At the moment only the float32 options is available for PyTorch, leading to this restriction.

I'll comment back on this issue with any updates.

**Comment by aws-taylor** [comment]
Hello ebochkov,

  I just wanted to let you know that we have not forgotten about you. While we do not have any fixes yet, we are hard at work with some performance and correctness fixes that we expect to improve our batching performance. We'll continue to track this issue and update as we have results.

-Taylor

**Comment by aws-zejdaj** [comment]
Still working on Pytorch batching support

**Comment by mrnikwaws** [comment]
Hi ebochkov,

ResNet-50 is now running with batch sizes of greater than 1!  In my testing I see the best results when I run compilation and inference using batch 5 for 224 x 224 images, but you should feel free to experiment.  The team is working on updating some of the tutorial material for torch-neuron, but I wanted to let you know so that you can rerun your previous tests if you want to.

You can change the existing "compile-infer" tutorial for compilation by using:

```
batch_size = 5
image = torch.zeros([batch_size, 3, 224, 224], dtype=torch.float32)
```

in place of 

```
image = torch.zeros([1, 3, 224, 224], dtype=torch.float32)
```

for compilation, and for inference change:

```
image = torch.tensor(image.numpy()[np.newaxis, ...])

## Load model
model_neuron = torch.jit.load( 'resnet50_neuron.pt' )

## Predict
results = model_neuron( image )
```

to

```
image = torch.tensor(image.numpy()[np.newaxis, ...])
batch_size = 5

## Create a "batch" image with enough images to go on each of the four cores
batch_image = image

for i in range(batch_size - 1):
    batch_image = torch.cat( [batch_image, image], 0 )

## Since the first inference also loads the model to the chip let's exclude it 
## from timing
results = model_neuron( batch_image )
```

This will simply make 5 copies of the image in the batch to test.  Note that the tensor sizes for compilation and inference must match.

I am going to keep this issue open for now until I hear back from you or post a link to the updated tutorial information.

**Comment by mrnikwaws** [comment]
The tutorial for ResNet-50 is now updated with the guidance requested [here](https://github.com/aws/aws-neuron-sdk/blob/master/src/pytorch/getting_started.md) - closing this issue.  Please re-open if you are still having problems.
