### ISSUE TITLE
Loading ONNX neuron-compiled models

### ISSUE THREAD

**Issue by RobertLucian** [aws/aws-neuron-sdk#107]
I've followed the instructions provided in this comment https://github.com/aws/aws-neuron-sdk/issues/59#issuecomment-577783414 and I've generated my `model.neff` binary. 

My question is, how do I actually load it on the Inf chip and do predictions? I suppose I have to use the `onnxruntime` module, but I don't see anything in the documentation describing this process.

**Comment by aws-renfu** [comment]
Hi Robert,

Thanks for the question. We currently do not support onnxruntime nor loading of model.neff natively. Could you provide some background information of your use model (framework, execution environment, ...) so that we can provide better guidance for you?

--Randy

**Comment by RobertLucian** [comment]
@aws-renfu it would exactly be the model compiled in the link I've given you: https://github.com/aws/aws-neuron-sdk/issues/59#issuecomment-577783414. To us, the Resnet50 model is a nice model to present to our users. It is to you what it is to us as well: a demo model. 

Does this make sense? Thanks!

**Comment by aws-renfu** [comment]
@RobertLucian,

I understand you want to demo the ResNet-50 model. Is your motivation to use ONNX because you do not want to use a framework like TensorFlow (to save system memory)? 

Thanks,

--Randy

**Comment by RobertLucian** [comment]
@aws-renfu the motivation is that ONNX may just be yet another framework that our users might want to use. Just like Tensorflow and PyTorch. I'm not the end-user here.

**Comment by aws-taylor** [comment]
Hello @RobertLucian,

  We agree and will continue to monitor ONNX requests from our customers as we prioritize customer production workloads. I will go ahead and close this issue for now, feel free to re-open if needed.

Regards,
Taylor

**Comment by fishuke** [comment]
@aws-taylor We need onnx neuron support in order to run one of the most common nude detection ai application [NudeNet](https://github.com/notAI-tech/NudeNet) please consider supporting it.

**Comment by stancld** [comment]
Hi @aws-taylor, I'd be curious if there's any consideration about adding support for onnx even though there's no public plans in the roadmap.

I'd consider onnxruntime not only as another framework like torch/tensorflow, but a great way for inference unification of models trained in tensorflow and torch. A direct consequence is one can have docker images containing only very light onnxruntime, instead of both heavy tensorflow/torch, which brings several advantages.

Thanks a lot for your reply and for the work of AWS team on another great open-source tool. <3

**Comment by kurosch** [comment]
@aws-taylor I am with @stancld onnxruntime would be a great way of inference unification. Also how do you prefer customer requests to pop in, shall I contact our aws solution architect, account manager or just create a support request ticket?
