### ISSUE TITLE
Neuron NCGs don't get destroyed when k8s deployments are deleted

### ISSUE THREAD

**Issue by RobertLucian** [aws/aws-neuron-sdk#108]
### Description

@aws-mo I have a k8s deployment which creates a pod with a container that has access to the host's neuron runtime (in my case `neuron-rtd.service`). There can be multiple pods running at the same time using different NCG(s) on the same instance. The following things have been done:

- Mounted `/run/neuron.sock` to `/sock/neuron.sock` and exported `NEURON_RTD_ADDRESS` appropriately in the pod's container.
- Set `NEURONCORE_GROUP_SIZES` appropriately - depending on how much the model requires.
- Added the k8s device plugin for Inferentia devices as a DaemonSet. DaemonSet [here](https://github.com/aws/aws-neuron-sdk/blob/master/docs/neuron-container-tools/k8s-neuron-device-plugin.yml).

Unlike in [k8s_bert_demo/bert_service.yml](https://github.com/aws/aws-neuron-sdk/blob/master/src/examples/tensorflow/k8s_bert_demo/bert_service.yml), I haven't added the `securityContext` field. I didn't think of adding it because the `neuron-rtd` service is already running on the host.

### Problem

Here's the thing: the pod spins up successfully, I can make predictions on my neuron-compiled model - I even checked that the neuron model is loaded, checked that the NCG(s) is/are created. All fine! But when the pod is deleted, the NCG(s) and model(s) still remain present. And when a new pod is created, the associated container gets the following error when trying to run an inference:
```
Traceback (most recent call last):
  File "/opt/conda/envs/env/lib/python3.6/site-packages/uvicorn/protocols/http/httptools_impl.py", line 385, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/opt/conda/envs/env/lib/python3.6/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/opt/conda/envs/env/lib/python3.6/site-packages/fastapi/applications.py", line 151, in __call__
    await super().__call__(scope, receive, send)  # pragma: no cover
  File "/opt/conda/envs/env/lib/python3.6/site-packages/starlette/applications.py", line 102, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/conda/envs/env/lib/python3.6/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/opt/conda/envs/env/lib/python3.6/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/opt/conda/envs/env/lib/python3.6/site-packages/starlette/middleware/base.py", line 25, in __call__
    response = await self.dispatch_func(request, self.call_next)
  File "/src/cortex/serve/serve.py", line 130, in register_request
    response = await call_next(request)
  File "/opt/conda/envs/env/lib/python3.6/site-packages/starlette/middleware/base.py", line 45, in call_next
    task.result()
  File "/opt/conda/envs/env/lib/python3.6/site-packages/starlette/middleware/base.py", line 38, in coro
    await self.app(scope, receive, send)
  File "/opt/conda/envs/env/lib/python3.6/site-packages/starlette/middleware/cors.py", line 76, in __call__
    await self.app(scope, receive, send)
  File "/opt/conda/envs/env/lib/python3.6/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/opt/conda/envs/env/lib/python3.6/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/opt/conda/envs/env/lib/python3.6/site-packages/starlette/routing.py", line 550, in __call__
    await route.handle(scope, receive, send)
  File "/opt/conda/envs/env/lib/python3.6/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/opt/conda/envs/env/lib/python3.6/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/opt/conda/envs/env/lib/python3.6/site-packages/fastapi/routing.py", line 166, in app
    dependant=dependant, values=values, is_coroutine=is_coroutine
  File "/opt/conda/envs/env/lib/python3.6/site-packages/fastapi/routing.py", line 121, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/opt/conda/envs/env/lib/python3.6/site-packages/starlette/concurrency.py", line 34, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "/opt/conda/envs/env/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/src/cortex/serve/serve.py", line 154, in predict
    prediction = predictor_impl.predict(request)
  File "/mnt/project/predictor_accelerator.py", line 58, in predict
    results = self.model(image)
  File "/opt/conda/envs/env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
RuntimeError: create_eg failed
The above operation failed in interpreter, with the following stack trace:
at code/__torch__/torch_neuron/decorators.py:7:9
op_version_set = 1
class NeuronModule(Module):
  __parameters__ = []
  training : bool
  def forward(self: __torch__.torch_neuron.decorators.NeuronModule,
    argument_1: Tensor) -> Tensor:
    _0 = ops.neuron.forward_1([argument_1], CONSTANTS.c0, CONSTANTS.c1, CONSTANTS.c2)
         ~~~~~~~~~~~~~~~~~~~~ <--- HERE
    return _0
Compiled from code /home/robert/.miniconda3/envs/py36-neuron-2/lib/python3.6/site-packages/torch_neuron/decorators.py(249): forward
/home/robert/.miniconda3/envs/py36-neuron-2/lib/python3.6/site-packages/torch/nn/modules/module.py(525): _slow_forward
/home/robert/.miniconda3/envs/py36-neuron-2/lib/python3.6/site-packages/torch/nn/modules/module.py(539): __call__
/home/robert/.miniconda3/envs/py36-neuron-2/lib/python3.6/site-packages/torch/jit/__init__.py(997): trace_module
/home/robert/.miniconda3/envs/py36-neuron-2/lib/python3.6/site-packages/torch/jit/__init__.py(858): trace
/home/robert/.miniconda3/envs/py36-neuron-2/lib/python3.6/site-packages/torch_neuron/decorators.py(263): trace
<ipython-input-3-690ff3856001>(4): <module>
/home/robert/.miniconda3/envs/py36-neuron-2/lib/python3.6/site-packages/IPython/core/interactiveshell.py(3331): run_code
/home/robert/.miniconda3/envs/py36-neuron-2/lib/python3.6/site-packages/IPython/core/interactiveshell.py(3254): run_ast_nodes
/home/robert/.miniconda3/envs/py36-neuron-2/lib/python3.6/site-packages/IPython/core/interactiveshell.py(3063): run_cell_async
/home/robert/.miniconda3/envs/py36-neuron-2/lib/python3.6/site-packages/IPython/core/async_helpers.py(68): _pseudo_sync_runner
/home/robert/.miniconda3/envs/py36-neuron-2/lib/python3.6/site-packages/IPython/core/interactiveshell.py(2886): _run_cell
/home/robert/.miniconda3/envs/py36-neuron-2/lib/python3.6/site-packages/IPython/core/interactiveshell.py(2858): run_cell
/home/robert/.miniconda3/envs/py36-neuron-2/lib/python3.6/site-packages/ipykernel/zmqshell.py(536): run_cell
/home/robert/.miniconda3/envs/py36-neuron-2/lib/python3.6/site-packages/ipykernel/ipkernel.py(300): do_execute
/home/robert/.miniconda3/envs/py36-neuron-2/lib/python3.6/site-packages/tornado/gen.py(209): wrapper
/home/robert/.miniconda3/envs/py36-neuron-2/lib/python3.6/site-packages/ipykernel/kernelbase.py(545): execute_request
/home/robert/.miniconda3/envs/py36-neuron-2/lib/python3.6/site-packages/tornado/gen.py(209): wrapper
/home/robert/.miniconda3/envs/py36-neuron-2/lib/python3.6/site-packages/ipykernel/kernelbase.py(268): dispatch_shell
/home/robert/.miniconda3/envs/py36-neuron-2/lib/python3.6/site-packages/tornado/gen.py(209): wrapper
/home/robert/.miniconda3/envs/py36-neuron-2/lib/python3.6/site-packages/ipykernel/kernelbase.py(365): process_one
/home/robert/.miniconda3/envs/py36-neuron-2/lib/python3.6/site-packages/tornado/gen.py(748): run
/home/robert/.miniconda3/envs/py36-neuron-2/lib/python3.6/site-packages/tornado/gen.py(787): inner
/home/robert/.miniconda3/envs/py36-neuron-2/lib/python3.6/site-packages/tornado/ioloop.py(743): _run_callback
/home/robert/.miniconda3/envs/py36-neuron-2/lib/python3.6/site-packages/tornado/ioloop.py(690): <lambda>
/home/robert/.miniconda3/envs/py36-neuron-2/lib/python3.6/asyncio/events.py(145): _run
/home/robert/.miniconda3/envs/py36-neuron-2/lib/python3.6/asyncio/base_events.py(1451): _run_once
/home/robert/.miniconda3/envs/py36-neuron-2/lib/python3.6/asyncio/base_events.py(438): run_forever
/home/robert/.miniconda3/envs/py36-neuron-2/lib/python3.6/site-packages/tornado/platform/asyncio.py(149): start
/home/robert/.miniconda3/envs/py36-neuron-2/lib/python3.6/site-packages/ipykernel/kernelapp.py(583): start
/home/robert/.miniconda3/envs/py36-neuron-2/lib/python3.6/site-packages/traitlets/config/application.py(664): launch_instance
/home/robert/.miniconda3/envs/py36-neuron-2/lib/python3.6/site-packages/ipykernel_launcher.py(16): <module>
/home/robert/.miniconda3/envs/py36-neuron-2/lib/python3.6/runpy.py(85): _run_code
/home/robert/.miniconda3/envs/py36-neuron-2/lib/python3.6/runpy.py(193): _run_module_as_main
``` 

When that happens, I get this error in `neuron-rtd.service`:

```
May 04 02:18:56 ip-192-168-41-8.ec2.internal nrtd[20664]: [NMGR:kmgr_create_eg] Not enough free NCs to allocate 2 members group
May 04 02:18:56 ip-192-168-41-8.ec2.internal nrtd[20664]: [NRTD:create_eg] create_eg() failed.
```

### Solution

To verify that this is due to not destroying/unloading the NCG(s) and model(s), when I `neuron-cli destroy-ncg` appropriately, I can restart a pod and everything will work fine yet again. So, it's totally due to not releasing the resources from the previous pods as it should be. 

I feel like I'm missing something here. A pre-stop command or a flag or something. Does anyone know what has to be done in this situation? And no, spinning up another instance won't cut it. And neither `sudo systemctl restart neuron-rtd`-ing won't be okay because it might affect other processes using other NCG(s). There are cases when pods will be launched one after another, on the same instance.

Thanks!

**Comment by deliahu** [comment]
@mrnikwaws @RobertLucian have you been able to resolve this? I am also running into this issue.

**Comment by mrnikwaws** [comment]
Hi Robert, David,
 
Are you are already following the recommendation from here?  https://github.com/aws/aws-neuron-sdk/tree/master/docs/neuron-container-tools.  One thing that may not be clear from the docs is that the lifecycle of the application and the matching runtime container should match (i.e. you stand them up and tear them down together).  If you have a separate lifecycle, or you are just using the runtime running on an instance – then you can see problems of the kind seen here. 
 
If you’re not deploying a runtime container tightly coupled with your application container, then your app would need to keep track and remove all network & NCGs explicitly. It could be done by calling neuron-cli as you’ve mentioned and passing IDs of the networks and NCGs.
 
For example:
```
neuron-cli unload <nn-id-1> -a unix:/run/neuron.sock
neuron-cli unload <nn-id-2> -a unix:/run/neuron.sock
```
 
Let me know if this information helps.  I am not an expert on EKS, but I am happy to dig in with you if we need to gather more information.

**Comment by RobertLucian** [comment]
@mrnikwaws 

Thanks a lot for coming back with a reply. This is really great! Yeah, I've gone through the documentation multiple times. So, to sum this up, there are 2 approaches to running the runtime:

1. Either by having the runtime tightly coupled with the application container. This means to have it running as a side-car in the pod and have them communicate via a shared UDS.
2. Or by using the instance's runtime that spins up at boot time. This one would be `neuron-rtd.service`. 

Assuming I continue going with the 2nd option where the lifecycle of the runtime is not the same as that of the application container, how can I determine from my application container which models/NCGs have to be unloaded/destroyed? Because if I can figure out what are these, then the fix would be doable. Are there any functions in `tensorflow-neuron` and/or `torch-neuron` and/or `mxnet-neuron` packages pertaining to this? Something like `unload`, `release_ncg`, `get_used_inf_devices`. This question just boils down to the idea of tracking the models & NCGs as they are created. Or would I have to resort to `neuron-cli` in some way?

---

As for the 1st option, this would mean I'd have to follow [these instructions](https://github.com/aws/aws-neuron-sdk/tree/master/docs/neuron-container-tools), which I already did. More specifically, [these instructions](https://github.com/aws/aws-neuron-sdk/blob/master/src/examples/tensorflow/k8s_bert_demo/README.md). In this case, I understand I have to do the following:
* Run the k8s plugin for Inferentia on each workload instance.
* For each pod that has a runtime container, add limits for `hugepages` & `aws.amazon.com/infa`.
* Share a UDS via a shared volume between the runtime sidecar and the application container.
* Configure [hugepages](https://github.com/aws/aws-neuron-sdk/blob/94402fabd2887b647028a2a24cb6efc8c87ab5cf/docs/neuron-runtime/nrt_start.md#step-3-configure-nr_hugepages) on the instance. Use 128 2Mi pages by default per Inferentia chip. In in the deployment's specs this translates to a total of 256Mi.

Apart from having tried the 2nd option and getting the said error, I've also tried the 1st option. Unfortunately, I'm getting a hugepages error when starting up the runtime container. I'm gonna create a separate ticket for it.

---

Can you confirm me 2 things about Inferentia?
1. The requested memory for the runtime container is used for those models that can't be fully cached onto the Inferentia device. This means the models won't actually get loaded on the application container's memory, but on the runtime's.
1. Idem as for 1, but for the CPU. This is when the `OnNeuronRatio` is smaller than 1.0.

Also, are there any performance penalties when there's only one runtime service running on an instance equipped with 16 Inferentia chips as opposed to having a runtime for each 1/2/4... Inferentia chips? As far as I understand from the documentation, having multiple runtimes can help.

**Comment by mrnikwaws** [comment]
I am going to close this issue since recommended course of action (matching runtime containers on the same life-cycle) has been shown to work correctly.

To respond on some questions here as discussed offline:

> The requested memory for the runtime container is used for those models that can't be fully cached onto the Inferentia device. This means the models won't actually get loaded on the application container's memory, but on the runtime's.

This is not correct, huge pages are used for loading models onto a neuron core group, if there is not enough space the load will fail.  The team will be following up on other issues mentioned in this thread.

If you have concerns that there is a remaining issue related to runtime life-cycle please reopen this issue
