### ISSUE TITLE
Neuron sdk for tensorflow 1.14.0

### ISSUE THREAD

**Issue by bharat-patidar** [aws/aws-neuron-sdk#115]
Is there any way to compile a model built with tensorflow=1.14.0 using  tensorflow-neuron?

**Comment by aws-diamant** [comment]
Hello @bharat-patidar,
Yes, as long as the model can be loaded into tensorflow=1.15.0, we expect it to compile with tensorflow-neuron.
Please let us know if you encounter any problem while attempting to do so.
