### ISSUE TITLE
"_resolve_func" Error message

### ISSUE THREAD

**Issue by psj8252** [aws/aws-neuron-sdk#121]
When assertion is fail '_resolve_func' in torch_neuron/decorators.py,
I think it's better to provide not only mod_name and func_name but 'node' information
if then, It's easy to know where to modify using file and line information

**Comment by awsryg** [comment]
Hi Park SangJun,
 
Thanks for the suggestion, we agree it will be useful for partitioning or modifying a model, and will be investigating it further.
We are also working on ways to provide a full list of operators that should be partitioned to the CPU (not just the first failure), and provide the option to have PyTorch automatically partition your model.

**Comment by psj8252** [comment]
OK, That's great.

**Comment by aws-taylor** [comment]
Hello Park SangJun,

  With our July 16 release, auto-partitioning is now available and ought to address your issue. Please don't hesitate to reach out to us if you need further assistance.

https://github.com/aws/aws-neuron-sdk/tree/master/release-notes

Regards,
Taylor
