### ISSUE TITLE
Frameworks and deployments: add support for TensorFlow 2 

### ISSUE THREAD

**Issue by AWSGH** [aws/aws-neuron-sdk#123]

**Comment by aws-zejdaj** [comment]
Still on our roadmap

**Comment by anjiefang** [comment]
ETA for TensorFlow 2 support ?

**Comment by AWSGH** [comment]
Hi anjiefang: the Neuron team is still working on adding the support. Please watch the repo for future updates. In the meantime, if you'd like, please email us at aws-neuron-support@amazon.com to provide more details on your specific workload,(pointer to model/specific Tf2.x version, etc) so we can capture the requirement.

**Comment by Andrei997** [comment]
Is there any update on the TF2 support ? We were super excited when we saw the AWS Inferentia instances but we are locked out for now because of the lack of support for TF2.

**Comment by jeffhataws** [comment]
https://awsdocs-neuron.readthedocs-hosted.com/en/latest/neuron-guide/neuron-frameworks/tensorflow-neuron/tf2.html
