### ISSUE TITLE
What happens if parts of the model graph are not Neuron-compatible?

### ISSUE THREAD

**Issue by la-cruche** [aws/aws-neuron-sdk#125]
Hi,

This is a question not an issue; feel free to point to a more relevant place if any. 
**What happens if parts of a model graph are not Neuron-compatible?** Will (A) Neuron send incompatible subgraphs to run on main CPU/mem an the Neuron-compatible subgraphs to run on Inferentia chips, or (B) is the model Inferentia inference not possible then?

**Comment by AWSNB** [comment]
Its (A)

**Comment by jeffhataws** [comment]
Hi la-cruche,
Please let us know if we can help further.
Thanks,
