### ISSUE TITLE
Can't compile when batch size is None

### ISSUE THREAD

**Issue by ClementColletReminiz** [aws/aws-neuron-sdk#127]
I'm trying to compile a model with a "resnet like" architecture, trained with TF 1.13

I'm already export my model using tensorflow saved_model. During this export, i use None as batch size for my inputs :
`images = tf.placeholder(tf.float32, shape=[None,None,None,3])`

I'm trying to compile my model with tensorflow.neuron.saved_model.compile.
When doing so, i get : 

> Traceback (most recent call last):
>   File "compile_resnet50.py", line 7, in <module>
>     tfn.saved_model.compile(saved_model_path, compiled_saved_model_path)
>   File "/home/ec2-user/test_venv/lib64/python3.7/site-packages/tensorflow_core/python/neuron/python/saved_model.py", line 158, in convert_to_inference_model
>     kwargs.update(shape_feed_dict=_infer_input_shapes(inputs.values(), batch_size))
>   File "/home/ec2-user/test_venv/lib64/python3.7/site-packages/tensorflow_core/python/neuron/python/saved_model.py", line 87, in _infer_input_shapes
>     ' shape of input tensor {}'.format(tensor))
> ValueError: batch_size is not sufficient to determine the shape of input tensor Tensor("47_Sport/classification_nccl_0/dataset_0/serving_input/Placeholder:0", shape=(?, ?, ?, 3), dtype=uint8)

In tensorflow.neuron.saved_model.compile, i specify : 
`model_shape_feed_dict={'images':[None,None,None,3]}`
And i get : 
> 2020-06-16 09:17:39.399757: I bazel-out/k8-opt/genfiles/tensorflow/python/neuron/convert/segment.cc:460] There are 7 ops of 5 different types in the graph that are not compiled by neuron-cc: ResizeBilinear, Assert, Const, NoOp, Placeholder, (For more information see https://github.com/aws/aws-neuron-sdk/blob/master/release-notes/neuron-cc-ops/neuron-cc-ops-tensorflow.md).
> WARNING:tensorflow:subgraph neuron_op_10da8093af6d83df, tensor 47_Sport/classification_nccl_0/dataset_0/serving_input/Reshape0/_0:0: invalid shape (?, 256, 256, 3)
> WARNING:tensorflow:Not fusing subgraph neuron_op_10da8093af6d83df: --io-config error
> WARNING:tensorflow:subgraph neuron_op_e6a7e1af44f56386, tensor 47_Sport/classification_nccl_0/dataset_0/serving_input/resize/ResizeBilinear0/_1:0: invalid shape (?, 256, 256, 3)
> WARNING:tensorflow:Not fusing subgraph neuron_op_e6a7e1af44f56386: --io-config error
> INFO:tensorflow:Number of operations in TensorFlow session: 1853
> INFO:tensorflow:Number of operations after tf.neuron optimizations: 392
> INFO:tensorflow:Number of operations placed on Neuron runtime: 0
> WARNING:tensorflow:Converted ./model/sport_47/ to ./compiled_model/ but no operator will be running on AWS machine learning accelerators. This is probably not what you want. Please refer to https://github.com/aws/aws-neuron-sdk for current limitations of the AWS Neuron SDK. We are actively improving (and hiring)!

Does it mean that the undefined batch size prevent Neuron operation ?

**Comment by aws-zejdaj** [comment]
Hi Clement,  

Yes, shapes have to be defined at compile time, please use  1,256,256,3. 
Also support for uint8 may be limited, please use fp16 or fp32 if encountering issues.

Please also see our batching tutorial, https://github.com/aws/aws-neuron-sdk/blob/master/docs/technotes/neuroncore-batching.md

Let us know if this was helpful
Regards,
Jindrich
