### ISSUE TITLE
Pytorch model compile failed. AssertionError: Neuron compile failed.  Operator aten::adaptive_max_pool2d is not supported

### ISSUE THREAD

**Issue by jriskin** [aws/aws-neuron-sdk#130]
I'm attempting to import my model with little success. It's a variant of resnet50.  I'm using the Deep learning AMI 30 with nothing extra. I ran source activate aws_neuron_pytorch_p36 and grabbed my file and ran the following code... 

`#!/usr/bin/env python3

import torch
import numpy as np
import os
import torch_neuron
from torchvision import models

model = torch.jit.load('torchscript.zip', map_location=torch.device('cpu'))
image = torch.zeros([1, 3, 299, 299], dtype=torch.float32)
model.eval()
model_neuron = torch.neuron.trace(model, example_inputs=[image])
model_neuron.save("gamedata_neuron.pt")`

`WARNING:root:Limited tf.compat.v2.summary API due to missing TensorBoard installation.
/home/ec2-user/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch/jit/__init__.py:852: UserWarning: The input to trace is already a ScriptModule, tracing it is a no-op. Returning the object as is.
  warnings.warn('The input to trace is already a ScriptModule, tracing it is a no-op. Returning the object as is.')
Traceback (most recent call last):
  File "./trace.py", line 14, in <module>
    model_neuron = torch.neuron.trace(model, example_inputs=[image])
  File "/home/ec2-user/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch_neuron/decorators.py", line 71, in trace
    transform_torch_graph_to_tensorflow( func, example_inputs, *args, **kwargs )
  File "/home/ec2-user/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch_neuron/decorators.py", line 291, in transform_torch_graph_to_tensorflow
    tensor_outputs = _resolve_func(node)(op, *tensor_inputs)
  File "/home/ec2-user/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch_neuron/decorators.py", line 1082, in _resolve_func
    assert hasattr(module, func_name), "Neuron compile failed.  Operator {}::{} is not supported".format(mod_name,func_name)
AssertionError: Neuron compile failed.  Operator aten::adaptive_max_pool2d is not supported`

**Comment by mrnikwaws** [comment]
Hi Jolie,

Please consult https://github.com/aws/aws-neuron-sdk/blob/master/release-notes/neuron-cc-ops/neuron-cc-ops-pytorch.md for the list of supported operators. You are correct that we do not support adaptive_max_pool2d yet in the current release.

We are working to improve operator support for torch-neuron and provide a mechanism to report the full set of unsupported operators (rather than the first unsupported one).  We are also working on delivering auto-partitioning model graphs so that you can easily compile without supported operators as part of our roadmap (https://github.com/aws/aws-neuron-sdk/issues/122)

Until the operator is supported, or auto-partitioning is available you can look at manually partitioning around the unsupported operators, following the tutorial here: https://github.com/aws/aws-neuron-sdk/blob/master/src/examples/pytorch/bert_tutorial/bert_large_mrpc_tutorial.md

You can run this code snippet to get a full list of unsupported operators in your model:

```
import torch
from torch.neuron import get_supported_operations

def analyze_model( model, example_inputs ):
    if isinstance(example_inputs, torch.Tensor):
        example_inputs=[example_inputs]
    model_jit = torch.jit.trace(model, example_inputs=example_inputs )
    torch._C._jit_pass_inline(model_jit.graph)

    ## Get the operators in the model
    operators_in_model = set()
    supported_in_model = set()

    ## Get the supported operations in the current version of torch-neuron
    supported_operators = set(get_supported_operations())

    total_count = 0
    supported_count = 0

    for node in model_jit.graph.nodes():
        operators_in_model.add( node.kind() )
        total_count += 1
        if node.kind() in supported_operators:
            supported_in_model.add(node.kind())
            supported_count += 1

    logging.warning("The following operations are currently supported in torch-neuron for this model")

    for op in supported_in_model:
        logging.warning(op)

    not_supported_operators = operators_in_model - supported_operators

    logging.warning("The following operations are currently not supported in torch-neuron for this model")
    sorted_not_supported_ops = sorted(list(not_supported_operators))
    for op in sorted_not_supported_ops:
        logging.warning(op)

    sorted_all_model_ops = sorted(list(operators_in_model))

    percent_supported = 100.0 * float(supported_count) / float( total_count )

    logging.warning("{:.2f}% of operations ({} of {}) are supported".format(percent_supported,supported_count,total_count))

    results = dict()

    results['percent_supported'] = percent_supported
    results['supported_count'] = supported_count
    results['total_count'] = total_count
    results['supported_operators'] = supported_in_model
    results['unsupported_operators'] = sorted_not_supported_ops
    results['operators'] = sorted_all_model_ops

    return results
```

**Comment by jriskin** [comment]
Just following up... I'll take a look at that script, but, i'm not entirely sure how much effort that will be. I'm mostly trying to see if there is cost savings moving from g4 to inf1 and it needs to be an easy path to get from our models to deployment.

The following operations are currently supported in torch-neuron for this model
aten::adaptive_avg_pool2d
aten::size
aten::relu_
aten::Int
aten::t
aten::cat
aten::addmm
aten::batch_norm
aten::max_pool2d
aten::add_
aten::_convolution
aten::dropout
aten::view
The following operations are currently not supported in torch-neuron for this model
aten::adaptive_max_pool2d
prim::Constant
prim::GetAttr
prim::ListConstruct
prim::NumToTensor
22.33% of operations (186 of 833) are supported

**Comment by mrnikwaws** [comment]
Hi Jolie,

Thanks for providing that readout.  In fact you can ignore the primitive operations (they are supported, but don't appear in get_supported_operations in the current release - this will be changed in the next release which the code I posted is intended to work with).  So the only missing operator is aten::adaptive_max_pool2d.  I'm exploring what we need to do to implement that operator.

**Comment by aws-taylor** [comment]
Hello Jolie,

 We have just pushed our July 16 release. While it does not include support for adaptive max pool, it does include a new auto-partitioning feature that may make it easier to achieve good performance using the operators that we do support. 

You can find an example usage in our Jupyter notebook here: https://github.com/aws/aws-neuron-sdk/blob/master/src/examples/pytorch/bert_tutorial/tutorial_pretrained_bert.ipynb

Release notes here: https://github.com/aws/aws-neuron-sdk/tree/master/release-notes

Regards,
Taylor

**Comment by aws-diamant** [comment]
Hi Jolie,

Just checking in, were you able to compile the model using the July 16 release?
The new auto-partitioner feature should make the migration path simpler and more automated.

Please let us know if we can assist further.

/Ron

**Comment by aws-joshim** [comment]
Hi Jolie,
Following up on the question from @aws-diamant, let us know if you were able to try out the July 16 release with the Pytorch auto-partitioner. We can assist if you are running into issues

**Comment by aws-joshim** [comment]
Hi Jolie, please reopen this issue if you have issues with the July 16th or later releases that support the auto partitioner feature
