### ISSUE TITLE
Error while compiling - TypeError: forward() got an unexpected keyword argument 'output_attentions'

### ISSUE THREAD

**Issue by C24IO** [aws/aws-neuron-sdk#133]
https://github.com/aws/aws-neuron-sdk/blob/6431512195ee3d9c9f42160f7b528bf97103fc0a/src/examples/pytorch/bert_tutorial/neuron_bert_mrpc_tutorial.ipynb#L687

WARNING:transformers.tokenization_utils_base:Truncation was not explicitely activated but `max_length` is provided a specific value, please use `truncation=True` to explicitely truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.
WARNING:transformers.tokenization_utils_base:Truncation was not explicitely activated but `max_length` is provided a specific value, please use `truncation=True` to explicitely truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.
-- Loading MRPC Adapted BERT
=== Confirm that BERT is doing something sane ===
Sentence 0 = 'Federal agents said yesterday they are investigating the theft.'
Sentence 1 = 'The agents indicated they were looking for stolen property.'
Sentence 2 = 'A Cuban architect was sentenced to 20 years in prison Friday.'

==Tokens (word ids) tensor==
tensor([[  101,  2976,  6074,  2056,  7483,  2027,  2024, 11538,  1996, 11933,
          1012,   102,  1996,  6074,  5393,  2027,  2020,  2559,  2005,  7376,
          3200,  1012,   102,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0]])
torch.Size([1, 128])

NB: 101 = [CLS] == start, 102 = [SEP] == separator
==Segment tensor (which word are in each sentence to compare)==
tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0]])
torch.Size([1, 128])

==Attention tensor (which word are in each sentence to compare)==
==(words vs padding to 128 constant width)==
tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0]])
torch.Size([1, 128])

Trace input sizes
===
torch.Size([4, 128])
torch.Size([4, 128])
torch.Size([4, 128])

-- Generating 4 model(s)
 - bert_large_mrpc_pytorch_batch4_0.pt
 - bert_large_mrpc_pytorch_batch4_1.pt
 - bert_large_mrpc_pytorch_batch4_2.pt
 - bert_large_mrpc_pytorch_batch4_3.pt

Load pretrained model

Partially compile Neuron Test BERT for PyTorch 'bert_large_mrpc_pytorch_batch4_0.pt'
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-15-0f11d62d2db2> in <module>
----> 1 compile_bert()

<ipython-input-11-fd6b7a12bd7a> in compile_bert()
     96     start = time.time()
     97 
---> 98     output = neuron_model(*dummy_input_1)
     99     print(output)
    100     delta = time.time() - start

~/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    539             result = self._slow_forward(*input, **kwargs)
    540         else:
--> 541             result = self.forward(*input, **kwargs)
    542         for hook in self._forward_hooks.values():
    543             hook_result = hook(self, input, result)

~/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/transformers/modeling_bert.py in forward(self, input_ids, attention_mask, token_type_ids, position_ids, head_mask, inputs_embeds, labels, output_attentions, output_hidden_states)
   1265             inputs_embeds=inputs_embeds,
   1266             output_attentions=output_attentions,
-> 1267             output_hidden_states=output_hidden_states,
   1268         )
   1269 

~/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    539             result = self._slow_forward(*input, **kwargs)
    540         else:
--> 541             result = self.forward(*input, **kwargs)
    542         for hook in self._forward_hooks.values():
    543             hook_result = hook(self, input, result)

TypeError: forward() got an unexpected keyword argument 'output_attentions'

**Comment by aws-taylor** [comment]
Hello Chaitanya,

 The 'output_attentions' parameter was changed in transformers 3.x. At this time, we only support 2.5.1. Please ensure that you are running the correct transformers version. You can check by running the following:

```
python3 -m pip show transformers
```

And install the correct version using:

```
python3 -m pip install transformers==2.5.1
```

Please let us know if you need any additional assistance.

Regards,
Taylor

**Comment by C24IO** [comment]
Resolved after locking down the transformers version.
