### ISSUE TITLE
Pytorch model compile failed. AssertionError: Neuron compile failed. Operator aten::ones is not supported

### ISSUE THREAD

**Issue by AdrianVandierAst** [aws/aws-neuron-sdk#140]
Hello :)

I'm trying to compile a camembert-base pytorch model fine-tuned with fast-bert (https://github.com/kaushaltrivedi/fast-bert).

During the compilation, I've got this error:
`AssertionError: Neuron compile failed.  Operator aten::ones is not supported `

I've seen that the compilation first transforms the pytorch model into a tensorflow one and indeed this operator is not listed when I do `neuron-cc list-operators --framework TENSORFLOW`.

Can i add this operation myself ? I think this is an easy one since ::zeros is implemented.
Or is there a way to bypass the problem ?

I'm using the Deep Learning AMI (Amazon Linux 2) Version 30.1 and the pre-configured virtualenv aws_neuron_pytorch_p36.
The version of torch-neuron and torch-neuron-base are the following:
Name: torch-neuron
Version: 1.0.1168.0
Name: torch-neuron-base
Version: 1.3.0.1.0.215.0

Thanks for your help.

Adrian

**Comment by AdrianVandierAst** [comment]
Ok, there is an update of torch_neuron, I was missing because we need to set the extra-url to get it:
`pip install torch-neuron torch-neuron-base -U --extra-index-url=https://pip.repos.neuron.amazonaws.com`

But `print(*torch.neuron.get_supported_operations(), sep='\n')` still does not list `aten::ones`.

**Comment by aws-diamant** [comment]
Hello AdrianVandierAst,
Thanks much for your question, and for finding the solution before we could reply ;)
aten::ones is indeed not supported in the July release.  We did introduce the PyTorch auto-partitioner feature in this release, which should help with this. The auto-partitioner automatically partitions the model graph to run the supported operators on Inferentia and the non-supported operators on the host CPU. You can then use `torch.neuron.analyze_model(model, example_input)` to examine the Neuron coverage of your model.

As you mentioned, that’s a simple operator. We will add support for aten::ones in the upcoming August release.

/Ron

**Comment by aws-diamant** [comment]
Hey AdrianVandierAst,

Just checking in if you were able to compile the model.

/Ron

**Comment by AdrianVandierAst** [comment]
Hello :)

I tried again yesterday, it almost worked but I got a new error:
```
Traceback (most recent call last):
  File "predict.py", line 32, in <module>
    model_neuron = torch.neuron.trace(predictor.learner.model, example_inputs=example_inputs)
  File "/home/ec2-user/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch_neuron/convert.py", line 41, in trace
    neuron_graph, jit_trace = to_graph(func, example_inputs, return_trace=True)
  File "/home/ec2-user/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch_neuron/convert.py", line 103, in to_graph
    neuron_graph = optimize.demodulize(neuron_graph, jit_trace, example_inputs)
  File "/home/ec2-user/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch_neuron/optimize.py", line 17, in demodulize
    jit_trace = torch.jit.trace(new_neuron_graph, example_inputs)
  File "/home/ec2-user/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch/jit/__init__.py", line 899, in trace
    _force_outplace)
  File "/home/ec2-user/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch_neuron/graph.py", line 72, in __call__
    outputs = op(*inputs)
  File "/home/ec2-user/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch_neuron/graph.py", line 158, in __call__
    return self.func(self, *inputs)
  File "/home/ec2-user/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch_neuron/resolve_function.py", line 52, in func
    return auto_func(**_get_kwargs(op, func_args, args))
RuntimeError: [enforce fail at CPUAllocator.cpp:64] . DefaultCPUAllocator: can't allocate memory: you tried to allocate 50331648 bytes. Error code 12 (Cannot allocate memory)
```

I've done the compilation on a c5.4xlarge. The problem is due to the size of the ram or with something else ? Do you think the problem would disappear if I use a c5.8xlarge or more ?

Thanks for your help.

Adrian

**Comment by micwade-aws** [comment]
Adrian - I'm taking a look today.  Will let you know if more memory is needed or if this is simply a bug in Neuron's torch auto-partitioner asap.

**Comment by micwade-aws** [comment]
@AdrianVandierAst, I was able to compile camembert-base on c5.4xlarge w/ AL2 DLAMI v30.  I tried a few different builds and instance sizes, but none of them reproduced the same error message you're seeing (CPUAllocator).  Is it possible to share sample code to help recreate the problem?

**Comment by AdrianVandierAst** [comment]
Hello. Thank you for your help. I will try to help you reproduce :)
The model that I tried to compile is a fine-tuned one. I can give you the code that I've done to compile but you will need the model to reproduce. I can prepare everything for you to recreate the model. The second 'problem' is that I've modified the library 'fast-bert' to remove the dependency to pytorch to keep the neuron one that is already installed in the virtualenv. The modified version is in a fork on github so with a pip install it should work.
I come back to you when I have everything ready for you. I hope you will encounter the problem with everything !

Adrian

**Comment by AdrianVandierAst** [comment]
I started from scratch the generation of the model and the compilation to have a reproducible error and it just worked :) Don't know what happened.
So, the compilation is OK. I still have to figure out how to optimise everything now !

Thank you.
Adrian
