### ISSUE TITLE
yolov5 model compile fail - copy_() missing 1 required positional arguments: "other"

### ISSUE THREAD

**Issue by imyoungyang** [aws/aws-neuron-sdk#141]
Hi

When I tried to compile yolo-v5 model, I got the following error message: copy_() missing 1 required positional arguments: "other"

pytorch version 1.5.1.1.0.251.0

The detail repeatable code is [here](https://github.com/imyoungyang/myAWSStudyBlog/blob/master/yolov5-onnx-sm/6-yolov5-inf1/Compile%20YoloV5%20model%20for%20AWS%20neuron.ipynb)

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-5-8575e7c3fa62> in <module>
      6 y = model(img)  # dry run to inference mode
      7 
----> 8 model_neuron = torch.neuron.trace(model, example_inputs=[img])
      9 model_neuron.save("yolov5_neuron.pt")

~/anaconda3/envs/pytorch_latest_p36/lib/python3.6/site-packages/torch_neuron/convert.py in trace(func, example_inputs, fallback, op_whitelist, minimum_segment_size, debug_must_trace, compiler_workdir, **kwargs)
     39         return node.type_string in op_whitelist
     40 
---> 41     neuron_graph, jit_trace = to_graph(func, example_inputs, return_trace=True)
     42     if _contains_neuron_forward(neuron_graph):
     43         logger.debug('{} already contains neuron::forward operators -- returning a plain trace'.format(func))

~/anaconda3/envs/pytorch_latest_p36/lib/python3.6/site-packages/torch_neuron/convert.py in to_graph(func_or_mod, example_inputs, return_trace)
    101     if not _contains_neuron_forward(neuron_graph):
    102         if isinstance(jit_trace, torch.jit.ScriptModule):
--> 103             neuron_graph = optimize.demodulize(neuron_graph, jit_trace, example_inputs)
    104         neuron_graph = optimize.remove_inplace_ops(neuron_graph)
    105     if return_trace:

~/anaconda3/envs/pytorch_latest_p36/lib/python3.6/site-packages/torch_neuron/optimize.py in demodulize(neuron_graph, jit_trace, example_inputs)
     15     new_neuron_graph.import_operations(neuron_graph.operations, neuron_graph.input_uniques[1:], neuron_graph.output_uniques)
     16     new_neuron_graph.unique_tensor_map[neuron_graph.input_uniques[0]] = jit_trace
---> 17     jit_trace = torch.jit.trace(new_neuron_graph, example_inputs)
     18     neuron_graph = graph.Graph()
     19     neuron_graph.import_jit_graph(jit_trace.graph)

~/anaconda3/envs/pytorch_latest_p36/lib/python3.6/site-packages/torch/jit/__init__.py in trace(func, example_inputs, optimize, check_trace, check_inputs, check_tolerance, _force_outplace, _module_class, _compilation_unit)
    897     traced = torch._C._create_function_from_trace(name, func, example_inputs,
    898                                                   var_lookup_fn,
--> 899                                                   _force_outplace)
    900 
    901     # Check the trace against new traces created from user-specified inputs

~/anaconda3/envs/pytorch_latest_p36/lib/python3.6/site-packages/torch_neuron/graph.py in __call__(self, op_converter, op_container, *inputs)
     70             if op_converter is not None:
     71                 op = op_converter(idx, op, inputs)
---> 72             outputs = op(*inputs)
     73             if len(op.output_uniques) == 1:
     74                 outputs = [outputs]

~/anaconda3/envs/pytorch_latest_p36/lib/python3.6/site-packages/torch_neuron/graph.py in __call__(self, *inputs)
    156 
    157     def __call__(self, *inputs):
--> 158         return self.func(self, *inputs)
    159 
    160 

~/anaconda3/envs/pytorch_latest_p36/lib/python3.6/site-packages/torch_neuron/resolve_function.py in func(op, tensor, *args)
     47         if resolved_module is torch.Tensor:
     48             def func(op, tensor, *args):
---> 49                 return auto_func(tensor, **_get_kwargs(op, func_args, args, offset=1))
     50         else:
     51             def func(op, *args):

TypeError: copy_() missing 1 required positional arguments: "other"

**Comment by micwade-aws** [comment]
Hi Young Yang (@imyoungyang),

Thanks for trying AWS Neuron. We are alway adding new operators to the supported list, but at the moment we're missing support for a couple operators in your model (copy and leaky_relu).  You can use the PyTorch coverage tool to get a list of supported and not supported operators like this:

```
results = torch.neuron.analyze_model( model, example_inputs )
```

On your specific sample code, output will look like this:

```
WARNING:root:The following operations are currently supported in torch-neuron for this model
WARNING:root:aten::detach
WARNING:root:aten::upsample_nearest2d
WARNING:root:aten::pow
WARNING:root:prim::TupleUnpack
WARNING:root:aten::floor
WARNING:root:aten::select
WARNING:root:aten::slice
WARNING:root:prim::ListConstruct
WARNING:root:aten::add
WARNING:root:aten::sigmoid
WARNING:root:aten::to
WARNING:root:prim::GetAttr
WARNING:root:aten::max_pool2d
WARNING:root:aten::permute
WARNING:root:aten::expand
WARNING:root:aten::batch_norm
WARNING:root:aten::contiguous
WARNING:root:aten::_convolution
WARNING:root:aten::sub
WARNING:root:aten::Int
WARNING:root:prim::NumToTensor
WARNING:root:prim::Constant
WARNING:root:aten::cat
WARNING:root:aten::mul
WARNING:root:prim::TupleConstruct
WARNING:root:aten::size
WARNING:root:aten::view
WARNING:root:The following operations are currently not supported in torch-neuron for this model
WARNING:root:aten::copy_
WARNING:root:aten::leaky_relu_
WARNING:root:97.79% of operations (2878 of 2943) are supported
```

For leaky_relu, we suggest replacing with relu, if possible, to ensure activation is executed on Inferentia (faster).  The copy operator is expected to work as part of an autopartitioning update in our next release.

We'll continue to add support for new operators each release. Please keep a close eye on the roadmap and specifically the list of supported operators here: https://github.com/aws/aws-neuron-sdk/blob/master/release-notes/neuron-cc-ops/neuron-cc-ops-pytorch.md
