### ISSUE TITLE
Release v1.6.1

### ISSUE THREAD

**Issue by jayrodge** [aws/aws-neuron-sdk#146]
What are the release updates for the v1.6.1 release of the Neuron SDK?

**Comment by aws-joshim** [comment]
This release is primarily a bugfix release for a stress induced race condition in Neuron Runtime which can lead to possible crashes. The Neuron Runtime package (aws-neuron-runtime) is updated to version 1.0.8813.0 or newer. Other package updates are non critical. Details at @ https://github.com/aws/aws-neuron-sdk/blob/master/release-notes/README.md

**Comment by jayrodge** [comment]
Thanks for the quick response, why not also add the info present in README.md in https://github.com/aws/aws-neuron-sdk/releases/tag/v1.6.1

**Comment by micwade-aws** [comment]
No reason not to do exactly that.  Fixing it up and will maintain the top level release notes in both places going forward.
