### ISSUE TITLE
[Q] SageMaker muliti model server support 

### ISSUE THREAD

**Issue by oonisim** [aws/aws-neuron-sdk#154]
Please advise if we can run multi models in the SageMaker MMS. As in https://docs.aws.amazon.com/sagemaker/latest/dg/multi-model-endpoints.html, GPU instance is not supported on the MMS.

**Comment by awsrjh** [comment]
Hello. We do not yet have support for MMS with inf1 in Sagemaker, but we are looking at it. Please check back. We will update our roadmap with more details: https://github.com/aws/aws-neuron-sdk/projects/2
