### ISSUE TITLE
Error neuron for pytorch model on inf instance, not finding neuron cores?

### ISSUE THREAD

**Issue by grant-swinton** [aws/aws-neuron-sdk#156]
New to neuron, so might be making a basic mistake. 

I'm trying to follow this tutorial (https://github.com/aws/aws-neuron-sdk/tree/master/src/examples/pytorch/bert_tutorial) for a BertForTokenClassification model. I made some modifications to the export script which all seemed to eventually work. 

The exported model passes the following code block with the correct values on the machine it was compiled on. However, it fails with an error on an inf 1 instance. Both instance are using the amazon linux 2 deep learning ami with the packages updated with this block
 
`pip install pip -U
pip install torch-neuron
pip install transformers==2.5.1
pip install pandas
pip install ipykernel
pip install boto3`

Here is the code. 
`model = torch.jit.load(model_name)

z1 = torch.zeros([2,128], dtype=torch.int64)
z2 = torch.zeros([2, 128], dtype=torch.float32)
prime_inputs = ( z1, z2)

print("Priming")
model(*prime_inputs)
print(" ...done")`

Here is the error that appears on the inf 1 instance. 

`RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript, serialized code (most recent call last):
  File "code/__torch__/___torch_mangle_731.py", line 11, in forward
    attention_mask: Tensor) -> Tuple[Tensor]:
    _0 = self.dropout
    _1 = (self.bert).forward(input_ids, attention_mask, )
          ~~~~~~~~~~~~~~~~~~ <--- HERE
    _2 = (self.classifier).forward((_0).forward(_1, ), )
    return (_2,)
  File "code/__torch__/___torch_mangle_728.py", line 21, in forward
    _7 = torch.to(extended_attention_mask, 6, False, False, None)
    _8 = torch.mul(torch.rsub(_7, 1., 1), CONSTANTS.c0)
    _9 = (_1).forward((_2).forward(input_ids, input, ), _8, )
          ~~~~~~~~~~~ <--- HERE
    hidden_states, = _9
    _10 = (_0).forward(hidden_states, )
  File "code/__torch__/torch_neuron/decorators.py", line 7, in forward
    argument_1: Tensor,
    argument_2: Tensor) -> Tuple[Tensor]:
    _0 = ops.neuron.forward_1([argument_1, argument_2], CONSTANTS.c1, CONSTANTS.c2, CONSTANTS.c3)
         ~~~~~~~~~~~~~~~~~~~~ <--- HERE
    return (_0,)

Traceback of TorchScript, original code (most recent call last):
/home/ec2-user/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch_neuron/decorators.py(242): forward
/home/ec2-user/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch/nn/modules/module.py(534): _slow_forward
/home/ec2-user/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch/nn/modules/module.py(548): __call__
/home/ec2-user/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch/jit/__init__.py(1027): trace_module
/home/ec2-user/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch/jit/__init__.py(875): trace
/home/ec2-user/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch_neuron/decorators.py(256): create_runnable
/home/ec2-user/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch_neuron/decorators.py(145): trace
/home/ec2-user/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch_neuron/convert.py(31): trace
<ipython-input-21-88aee4ddc4b3>(153): forward
/home/ec2-user/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch/nn/modules/module.py(550): __call__
/home/ec2-user/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/transformers/modeling_bert.py(1371): forward
/home/ec2-user/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch/nn/modules/module.py(550): __call__
<ipython-input-37-32001be231e3>(8): <module>
/home/ec2-user/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/IPython/core/interactiveshell.py(3343): run_code
/home/ec2-user/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/IPython/core/interactiveshell.py(3263): run_ast_nodes
/home/ec2-user/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/IPython/core/interactiveshell.py(3072): run_cell_async
/home/ec2-user/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/IPython/core/async_helpers.py(68): _pseudo_sync_runner
/home/ec2-user/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/IPython/core/interactiveshell.py(2895): _run_cell
/home/ec2-user/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/IPython/core/interactiveshell.py(2867): run_cell
/home/ec2-user/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/ipykernel/zmqshell.py(536): run_cell
/home/ec2-user/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/ipykernel/ipkernel.py(306): do_execute
/home/ec2-user/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/tornado/gen.py(209): wrapper
/home/ec2-user/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/ipykernel/kernelbase.py(545): execute_request
/home/ec2-user/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/tornado/gen.py(209): wrapper
/home/ec2-user/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/ipykernel/kernelbase.py(268): dispatch_shell
/home/ec2-user/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/tornado/gen.py(209): wrapper
/home/ec2-user/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/ipykernel/kernelbase.py(365): process_one
/home/ec2-user/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/tornado/gen.py(748): run
/home/ec2-user/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/tornado/gen.py(787): inner
/home/ec2-user/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/tornado/ioloop.py(743): _run_callback
/home/ec2-user/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/tornado/ioloop.py(690): <lambda>
/home/ec2-user/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/asyncio/events.py(145): _run
/home/ec2-user/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/asyncio/base_events.py(1462): _run_once
/home/ec2-user/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/asyncio/base_events.py(442): run_forever
/home/ec2-user/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/tornado/platform/asyncio.py(149): start
/home/ec2-user/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/ipykernel/kernelapp.py(612): start
/home/ec2-user/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/traitlets/config/application.py(664): launch_instance
/home/ec2-user/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/ipykernel/__main__.py(3): <module>
/home/ec2-user/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/runpy.py(85): _run_code
/home/ec2-user/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/runpy.py(193): _run_module_as_main
RuntimeError: NeuronDevice::process_nrtd_response: Context=NRTD_CTX_INITIALIZE NRTD response code 'NERR_RESOURCE_NC' (9) There were insufficent NCs for the requested operation Raw runtime error message ''`

It looks to me like it doesn't have an access to neuron cores. I'm running it on a inf1.2xlarge, in the aws_neuron_pytorch_p36 image. Is there a way to check if python can "see" the neuron cores?

**Comment by awsryg** [comment]
Hi Grant, there is a possibility that after you run the regular tutorial, and before you tried with your changes, the FAL process ended non gracefully. Could you please try a
neuron-cli reset
in between?

**Comment by AWSGH** [comment]
one more update: the team was able to reproduce a scenario that produce the same error , but since you didn't provide the changes made from our tutorial, this might not be the exact same issue. We will add a fix to what we observed in the next release. In the meantime, can you try the recovery step @awsryg proposed above and let us know if it solved the issue?

**Comment by grant-swinton** [comment]
Hey awsryg, thanks for the response. 

The neuron-cli reset didn't seem to solve the problem, but I'm not familiar enough with this software to be sure I have all the correct versions. In an effort to make this easier to debug, I set up DLAMI ubuntu instances exactly as described in the tutorial, and then ran my scripts again. Unfortunately, I ran into a different bug, this time when trying to load the model on the machine which compiled it (and also on the inferentia instance). 

I'll share the code used to build it. I reused precisely the same definitions of "NeuronForwardBertModel" and "NeuronForwardBertEncoder" from the example

I make minor changes to create "NeuronForwardBertForTokenClassification"

`class NeuronForwardBertForTokenClassification(BertForTokenClassification):
    
    def __init__(self, config, compiler_options, optimization=None, use_cached_compiler_output=False ):

        super().__init__(config)
        
        self.bert = NeuronForwardBertModel(config,compiler_options, optimization=optimization, use_cached_compiler_output=use_cached_compiler_output)
        
        self.init_weights()
`

Then use this script to compile a model.

`
compiler_options="--fp32-cast all --verbose=1 --tensor-layout-heuristics=spatial-locality -O2"
optimization="aggressive"

config = BertConfig.from_pretrained(bert_model, cache_dir=cache_dir, num_labels = len(tag2idx.keys()), 
                                    id2label = idx2tag, label2id = tag2idx, torchscript = True)
model = NeuronForwardBertForTokenClassification.from_pretrained("ner_32_state_dict.pt", from_tf=False, 
                                                                config=config, compiler_options = compiler_options, 
                                                               optimization=optimization)
model.eval()

batch_size = 2

#I use examples from the dataset, but should be simpler to use the example below. It results in the same error for me
#input_ids_t = torch.from_numpy(input_ids[0:batch_size]).to(device).reshape(-1, 128)
#attention_masks_t = torch.from_numpy(attention_masks[0:batch_size]).to(device).type(torch.float32).reshape(-1, 128)
#inputs = [input_ids_t,  attention_masks_t]

z1 = torch.zeros([2,128], dtype=torch.int64)
z2 = torch.zeros([2, 128], dtype=torch.float32)
inputs = ( z1, z2)

print("Trace input sizes")
print("===")
for inp in inputs:
    print( inp.size() )

model(*inputs)

neuron_model = torch.jit.trace(model, example_inputs=inputs)
torch.jit.save(neuron_model, "ner_neuron.pt")
`

This all runs without error, and then this line `model = torch.jit.load('ner_neuron.pt')` on the same instance in the same virtual environment results in this error.
`
Unknown builtin op: neuron::forward_1.
Could not find any similar ops to neuron::forward_1. This op may not exist or may not be currently supported in TorchScript.
:
/home/ubuntu/bert_mrpc/torch_compile/lib/python3.6/site-packages/torch_neuron/decorators.py(242): forward
/home/ubuntu/bert_mrpc/torch_compile/lib/python3.6/site-packages/torch/nn/modules/module.py(534): _slow_forward
/home/ubuntu/bert_mrpc/torch_compile/lib/python3.6/site-packages/torch/nn/modules/module.py(548): __call__
/home/ubuntu/bert_mrpc/torch_compile/lib/python3.6/site-packages/torch/jit/__init__.py(1027): trace_module
/home/ubuntu/bert_mrpc/torch_compile/lib/python3.6/site-packages/torch/jit/__init__.py(875): trace
/home/ubuntu/bert_mrpc/torch_compile/lib/python3.6/site-packages/torch_neuron/decorators.py(256): create_runnable
/home/ubuntu/bert_mrpc/torch_compile/lib/python3.6/site-packages/torch_neuron/decorators.py(145): trace
/home/ubuntu/bert_mrpc/torch_compile/lib/python3.6/site-packages/torch_neuron/convert.py(32): trace
<ipython-input-9-88aee4ddc4b3>(153): forward
/home/ubuntu/bert_mrpc/torch_compile/lib/python3.6/site-packages/torch/nn/modules/module.py(550): __call__
/home/ubuntu/bert_mrpc/torch_compile/lib/python3.6/site-packages/transformers/modeling_bert.py(1371): forward
/home/ubuntu/bert_mrpc/torch_compile/lib/python3.6/site-packages/torch/nn/modules/module.py(550): __call__
<ipython-input-15-f9b1bfb6daa6>(15): <module>
/home/ubuntu/bert_mrpc/torch_compile/lib/python3.6/site-packages/IPython/core/interactiveshell.py(3343): run_code
/home/ubuntu/bert_mrpc/torch_compile/lib/python3.6/site-packages/IPython/core/interactiveshell.py(3263): run_ast_nodes
/home/ubuntu/bert_mrpc/torch_compile/lib/python3.6/site-packages/IPython/core/interactiveshell.py(3072): run_cell_async
/home/ubuntu/bert_mrpc/torch_compile/lib/python3.6/site-packages/IPython/core/async_helpers.py(68): _pseudo_sync_runner
/home/ubuntu/bert_mrpc/torch_compile/lib/python3.6/site-packages/IPython/core/interactiveshell.py(2895): _run_cell
/home/ubuntu/bert_mrpc/torch_compile/lib/python3.6/site-packages/IPython/core/interactiveshell.py(2867): run_cell
/home/ubuntu/bert_mrpc/torch_compile/lib/python3.6/site-packages/ipykernel/zmqshell.py(536): run_cell
/home/ubuntu/bert_mrpc/torch_compile/lib/python3.6/site-packages/ipykernel/ipkernel.py(306): do_execute
/home/ubuntu/bert_mrpc/torch_compile/lib/python3.6/site-packages/tornado/gen.py(209): wrapper
/home/ubuntu/bert_mrpc/torch_compile/lib/python3.6/site-packages/ipykernel/kernelbase.py(545): execute_request
/home/ubuntu/bert_mrpc/torch_compile/lib/python3.6/site-packages/tornado/gen.py(209): wrapper
/home/ubuntu/bert_mrpc/torch_compile/lib/python3.6/site-packages/ipykernel/kernelbase.py(268): dispatch_shell
/home/ubuntu/bert_mrpc/torch_compile/lib/python3.6/site-packages/tornado/gen.py(209): wrapper
/home/ubuntu/bert_mrpc/torch_compile/lib/python3.6/site-packages/ipykernel/kernelbase.py(365): process_one
/home/ubuntu/bert_mrpc/torch_compile/lib/python3.6/site-packages/tornado/gen.py(748): run
/home/ubuntu/bert_mrpc/torch_compile/lib/python3.6/site-packages/tornado/gen.py(787): inner
/home/ubuntu/bert_mrpc/torch_compile/lib/python3.6/site-packages/tornado/ioloop.py(743): _run_callback
/home/ubuntu/bert_mrpc/torch_compile/lib/python3.6/site-packages/tornado/ioloop.py(690): <lambda>
/home/ubuntu/anaconda3/lib/python3.6/asyncio/events.py(145): _run
/home/ubuntu/anaconda3/lib/python3.6/asyncio/base_events.py(1434): _run_once
/home/ubuntu/anaconda3/lib/python3.6/asyncio/base_events.py(422): run_forever
/home/ubuntu/bert_mrpc/torch_compile/lib/python3.6/site-packages/tornado/platform/asyncio.py(149): start
/home/ubuntu/bert_mrpc/torch_compile/lib/python3.6/site-packages/ipykernel/kernelapp.py(612): start
/home/ubuntu/bert_mrpc/torch_compile/lib/python3.6/site-packages/traitlets/config/application.py(664): launch_instance
/home/ubuntu/bert_mrpc/torch_compile/lib/python3.6/site-packages/ipykernel_launcher.py(16): <module>
/home/ubuntu/anaconda3/lib/python3.6/runpy.py(85): _run_code
/home/ubuntu/anaconda3/lib/python3.6/runpy.py(193): _run_module_as_main
Serialized   File "code/__torch__/torch_neuron/decorators.py", line 7
    argument_1: Tensor,
    argument_2: Tensor) -> Tuple[Tensor]:
    _0 = ops.neuron.forward_1([argument_1, argument_2], CONSTANTS.c1, CONSTANTS.c2, CONSTANTS.c3)
         ~~~~~~~~~~~~~~~~~~~~ <--- HERE
    return (_0,)
`

The op it seems to be complaining about exists in the tutorial. So I'm not entirely sure why there's a difference here.

**Comment by mrnikwaws** [comment]
Hi Grant,

Thanks for following up.  It looks like there are two separate issues:

1. On you repro is looks like you have no "import torch.neuron" line

When you torch.jit.load on a compiled model this has to be imported first.  The act of importing torch.neuron registers the operators needed to run the neuron hardware.

2. Earlier in this bug report you reported problems loading models into a neuron core.

The earlier advice was good, but is hard to root cause this without more data.  Can you share the contents of your /var/log/syslog file?  This shows the history of loading and unloading models in neuron cores.  

It may be that you are trying to invoke an already busy neuron core and the runtime is trying to find a new core (but none are available).  We are working on improving the usability of the runtime via PyTorch and other frameworks to avoid confusion on this topic.

Similarly, if you have more information on the number of processes / threads that you are running (and whether the loaded models are shared by multiple processes / threads) that would help. 

For a single process calling neuron-cli reset before invoking python ought to solve the issue as previously recommended (if your use case is that simple).

**Comment by grant-swinton** [comment]
Thanks a lot. I suspected it was something dumb. I had import torch_neuron. It's correct in the tutorial, but I changed it before I set up the environment exactly like the example in ubuntu.
Issue resolved, thank you for your advice.

**Comment by aws-zejdaj** [comment]
Marking as resolved per feedback from Grant.
