### ISSUE TITLE
PyTorch BERT Fails on Compiler Arguments

### ISSUE THREAD

**Issue by joelsimonoff** [aws/aws-neuron-sdk#157]
When running the provided PyTorch BERT everything works perfectly. However, when I add compiler arguments it throws an error and the compiled model will only run on the CPU – when I run the stock example the compiled model runs on the inf1 chips. I'm checking for the usage of the inf1 chips versus CPU by monitoring `neuron-top` and regular `top`.

Here is the example script that works great:

```
# Build tokenizer and model
tokenizer = AutoTokenizer.from_pretrained("bert-base-cased-finetuned-mrpc")
model = AutoModelForSequenceClassification.from_pretrained("bert-base-cased-finetuned-mrpc")

# Setup some example inputs
sequence_0 = "The company HuggingFace is based in New York City"
sequence_1 = "Apples are especially bad for your health"
sequence_2 = "HuggingFace's headquarters are situated in Manhattan"
paraphrase = tokenizer.encode_plus(sequence_0, sequence_2, max_length=128, pad_to_max_length=True, return_tensors="pt")
not_paraphrase = tokenizer.encode_plus(sequence_0, sequence_1, max_length=128, pad_to_max_length=True, return_tensors="pt")

# Run the original PyTorch model on both example inputs
paraphrase_classification_logits = model(**paraphrase)[0]
not_paraphrase_classification_logits = model(**not_paraphrase)[0]

# Convert example inputs to a format that is compatible with TorchScript tracing
example_inputs_paraphrase = paraphrase['input_ids'], paraphrase['attention_mask'], paraphrase['token_type_ids']
example_inputs_not_paraphrase = not_paraphrase['input_ids'], not_paraphrase['attention_mask'], not_paraphrase['token_type_ids']

# Run torch.neuron.trace to generate a TorchScript that is optimized by AWS Neuron, using optimization level -O2
model_neuron = torch.neuron.trace(model, example_inputs_paraphrase, compiler_args=['-O2'])

# Verify the TorchScript works on both example inputs
paraphrase_classification_logits_neuron = model_neuron(*example_inputs_paraphrase)
not_paraphrase_classification_logits_neuron = model_neuron(*example_inputs_not_paraphrase)

# Save the TorchScript for later use
model_neuron.save('bert_neuron.pt')
```
I get the following output:

```
INFO:Neuron:Optimize = None
INFO:Neuron:Compiler args type is <class 'list'> value is ['-O2', '--verbose', 'DEBUG']
INFO:Neuron:compiling function _NeuronGraph$1995 with neuron-cc
INFO:Neuron:Compiling with command line: '/home/ubuntu/main/bin/neuron-cc compile /tmp/tmpil66ogz4/graph_def.pb --framework TENSORFLOW --pipeline compile SaveTemps --output /tmp/tmpil66ogz4/graph_def.neff --io-config {"inputs": {"0:0": [[1, 128, 768], "float32"], "1:0": [[1, 1, 1, 128], "float32"]}, "outputs": ["Add_133:0"]} -O2''
-- Use compile_from_neff function
-- Use create_runnable function
```

However, when I add a compiler argument the compilation fails. For example, take modifying this line: 
```
model_neuron = torch.neuron.trace(model, example_inputs_paraphrase, compiler_args=['-O2'])
``` 
to (adding '--num-neuroncores', '4'):
```
model_neuron = torch.neuron.trace(model, example_inputs_paraphrase, compiler_args=['-O2', '--num-neuroncores', '4'])
```

The output becomes:

```
INFO:Neuron:Optimize = None
INFO:Neuron:Compiler args type is <class 'list'> value is ['-O2', '--num-neuroncores', '4']
INFO:Neuron:compiling function _NeuronGraph$1327 with neuron-cc
INFO:Neuron:Compiling with command line: '/home/ubuntu/main/bin/neuron-cc compile /tmp/tmpqj415bff/graph_def.pb --framework TENSORFLOW --pipeline compile SaveTemps --output /tmp/tmpqj415bff/graph_def.neff --io-config {"inputs": {"0:0": [[1, 128, 768], "float32"], "1:0": [[1, 1, 1, 128], "float32"]}, "outputs": ["Add_133:0"]} -O2 --num-neuroncores 4''

WARNING:Neuron:torch.neuron.trace failed on <torch_neuron.graph.Graph object at 0x7f93a750a490>; falling back to native python function call

WARNING:Neuron:torch.neuron.trace error: neuron-cc failed with the following command line call:
/home/ubuntu/main/bin/neuron-cc compile /tmp/tmpqj415bff/graph_def.pb --framework TENSORFLOW --pipeline compile SaveTemps --output /tmp/tmpqj415bff/graph_def.neff --io-config '{"inputs": {"0:0": [[1, 128, 768], "float32"], "1:0": [[1, 1, 1, 128], "float32"]}, "outputs": ["Add_133:0"]}' -O2 --num-neuroncores 4
```
When I load the new checkpoint into the inference example, the code runs, **BUT** it doesn't run on the inf1 chip, it only runs on the CPU (the original checkpoint from the example, without the compiler option, runs on the inf1 chip).

The same behavior seems to occur with `dynamic_batch_size True` and `--static-weights`.

System Specs:
- In house Linux VM: (gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04))
- Python 3.7.7
- `torch` Version: 1.5.1
- `torch-neuron` Version: 1.5.1.1.0.1532.0
- `transformers` Version: 2.8.0 (**Older Version**: _Could this likely make a difference?_)

Thanks for taking the time to read through the issue!

**Comment by aws-zejdaj** [comment]
Hi Joel, Thanks for letting us know and happy to see that the original tutorial is working well for you.

We'll check the issue with the additional arguments and get back to you.

Jindrich

**Comment by joelsimonoff** [comment]
I just gave it a try with a newer version of `transformers` version `3.0.2` and it has the same behavior.

**Comment by aws-zejdaj** [comment]
Hi Joel,

With BERT we have mainly seen customers running the same model on four parallel NeuronCores, to maximize throughput performance. is that what you are intending to implement?  

The --num-neuron-cores argument is used when you want to run single model with parts of the computation on several cores. Assuming you do want run the same model on multiple cores you can call torch.jit.load on a previously saved model several times, and then have a thread associated with each callable model which will direct traffic to that neuron core.  Some example code can be found at  https://github.com/aws/aws-neuron-sdk/blob/master/src/examples/pytorch/bert_tutorial/neuron_bert_mrpc_benchmark.ipynb.

Please advise

**Comment by joelsimonoff** [comment]
@aws-zejdaj Using multiple threads definitely works for our use case. We are hoping to try out `--static_weights`, and `--num-neuron-cores` to see what performance we get with different parameters. However, if this issue is that it may be unimplemented for PyTorch or for Transformer models then we can stick with running on four parallel cores.

**Comment by jeffhataws** [comment]
Thank you. Yes, please use data-parallel for now as the pipelined approach is used when you need to optimize for both throughput and latency. More details on NeuronCore Pipeline can be found here:  https://github.com/aws/aws-neuron-sdk/blob/master/docs/technotes/neuroncore-pipeline.md.

**Comment by jeffhataws** [comment]
Closing issue for now. Please let us know if there's any further issues or questions. Thanks.
