### ISSUE TITLE
Neuron docker images not available on ECR

### ISSUE THREAD

**Issue by RobertLucian** [aws/aws-neuron-sdk#159]
#### Reproduce

Trying to `docker pull` [790709498068.dkr.ecr.us-west-2.amazonaws.com/neuron-device-plugin](https://github.com/aws/aws-neuron-sdk/blob/master/docs/neuron-container-tools/k8s-neuron-device-plugin.yml#L55) and [790709498068.dkr.ecr.us-west-2.amazonaws.com/neuron-scheduler](https://github.com/aws/aws-neuron-sdk/blob/master/docs/neuron-container-tools/k8s-neuron-scheduler.yml#L97) results in the following error messages:

```text
Error response from daemon: Get https://790709498068.dkr.ecr.us-west-2.amazonaws.com/v2/neuron-device-plugin/manifests/latest: no basic auth credentials

Error response from daemon: Get https://790709498068.dkr.ecr.us-west-2.amazonaws.com/v2/neuron-scheduler/manifests/latest: no basic auth credentials
```

I've also made sure to be logged in the right region with ECR. Supposedly, the images were made public.

```bash
$ eval $(aws ecr get-login --no-include-email --region us-west-2)
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
WARNING! Your password will be stored unencrypted in /home/robert/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store

Login Succeeded
```

Is there anything that we do wrong here? The only thing that works is to list the image tags/digests. Here's an example for `neuron-device-plugin` image:

```bash
$ aws ecr list-images --region us-west-2 --registry-id 790709498068 --repository-name neuron-device-plugin
{
    "imageIds": [
        {
            "imageDigest": "sha256:23bcdf7f99b531518e2d8de706c93ef5feb45684640919942bea75f75bd2c286"
        },
        {
            "imageDigest": "sha256:c5cd86e85af7c8a4a6a79f0e33ae37b669668660adf9d10fea1ccba904b44fb5",
            "imageTag": "1.0.9700.0"
        },
        {
            "imageDigest": "sha256:ea46cb88948037a2b422148d74daad417ce91bf2a44da8f683ef33c9f9cabfd3"
        },
        {
            "imageDigest": "sha256:fac4e2b750fb5a3efb6ff9a7304d94dc44f6d2a0020294b4e5c43c25793b2b05",
            "imageTag": "1.0.10182.0"
        },
        {
            "imageDigest": "sha256:422206249b431c3bc2605952c2c153faf8c17349f89745fec2f74e6905aedbfa",
            "imageTag": "1.0.8550.0"
        },
        {
            "imageDigest": "sha256:ed1032f87bc2ed65c917a816274562ba6c237f8f215a06eafc9f3acf5c862cea"
        },
        {
            "imageDigest": "sha256:0272cc9f278bf606e5b81db87a99841fa8926382d916ccfc65ee832bf609f589",
            "imageTag": "1.0.11000.0"
        },
        {
            "imageDigest": "sha256:0272cc9f278bf606e5b81db87a99841fa8926382d916ccfc65ee832bf609f589",
            "imageTag": "latest"
        },
        {
            "imageDigest": "sha256:6a0df1d6446c96b752f7abbdc9478873e2f3da05989dcaf17667076db8339728",
            "imageTag": "1.0.9043.0"
        },
        {
            "imageDigest": "sha256:51ea1ef36d9a8e347c7557a2d73eef75369cc19969dbad97c0ca19d5e25a52be",
            "imageTag": "1.0.9171.0"
        },
        {
            "imageDigest": "sha256:f040fed0e60888d82f3101630629a5433affc051897eb161dc924cf4205c1ebb"
        }
    ]
}
```

#### Additional context

@mrnikwaws I also had the same issue a couple of months ago, back when the images were placed in `us-east-1`. This was described here https://github.com/aws/aws-neuron-sdk/issues/102#issuecomment-644164571. Interestingly, this wasn't an issue before June (i.e May, late April), so they definitely worked at some point.

**Comment by deliahu** [comment]
The same command is also failing for me:

```text
$ docker pull 790709498068.dkr.ecr.us-west-2.amazonaws.com/neuron-device-plugin:latest
Error response from daemon: Get https://790709498068.dkr.ecr.us-west-2.amazonaws.com/v2/neuron-device-plugin/manifests/latest: no basic auth credentials
```

I have tried logging into ECR in `us-west-2` by running `eval $(aws ecr get-login --no-include-email --region us-west-2)` (as @RobertLucian has). I have also tried adding `"790709498068.dkr.ecr.us-west-2.amazonaws.com": {},` to my `~/.docker/config.json`, but still no luck.

**Comment by micwade-aws** [comment]
Taking a look - will correct whatever has changed or provide instructions asap.

**Comment by micwade-aws** [comment]
There has certainly been a change here and we're investigating it.  On AWS cli version 2, the get-login api was [deprecated](https://docs.aws.amazon.com/cli/latest/reference/ecr/get-login.html).

Please change to get-login-password instead:
```
aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 790709498068.dkr.ecr.us-west-2.amazonaws.com
```

If that works it will save the credentials off to ~/.docker/config.json; unblocking your ability to issue the pull.

We're going to reach out to ECR internally to get a better idea of why this is changed.  The documentation will be updated today as well to reflect the new command.  

Please confirm this worked for you @RobertLucian and @deliahu ?

**Comment by RobertLucian** [comment]
@micwade-aws yes, I confirm that this is now working for me. Thanks a lot for the swift response!

By the way, the output of `aws ecr get-login-password` is identical to the token spit out by `aws ecr get-login`. The username and registry address from `aws ecr get-login` are identical too to those passed in `aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 790709498068.dkr.ecr.us-west-2.amazonaws.com`.

So, all in all, both commands `eval $(aws ecr get-login --no-include-email --region us-west-2)` and `aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 790709498068.dkr.ecr.us-west-2.amazonaws.com` appear to be equivalent and yet, one of them works and the other not. Any idea why this is the case?

**Comment by micwade-aws** [comment]
Working on that answer before we officially update the docs.

**Comment by deliahu** [comment]
@micwade-aws yes that did the trick, thank you for the quick response!

In case it helps with your investigation, it may not actually be an issue with the AWS CLI version (1 vs 2) or the `ecr get-login` vs `ecr get-login-password` command (although I might as well switch to the `ecr get-login-password` command if that's recommended). If it is expected to have to `docker login` to the AWS ECR repo in order to pull, there may not be an issue after all. I say this because my CLI version is `aws-cli/1.18.130 Python/3.6.9 Linux/5.3.0-1032-aws botocore/1.17.53`, and both of the following commands seemed to do the trick for me:

```text
aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 790709498068.dkr.ecr.us-west-2.amazonaws.com
``` 

```text
eval $(aws ecr get-login --no-include-email --region us-west-2 --registry-ids 790709498068)
```

**Comment by micwade-aws** [comment]
We're updating the Neuron docs to use the newer ECR API call, get-login-password, and to specify the registry.  When accessing ECR across accounts, the registry is needed, which was missing from our original 'get-login' instructions.  

@deliahu - both of your commands are working because the registry-id was being specified.  This was a great callout - thank you both.

Will close this issue out once the docs are updated.

**Comment by deliahu** [comment]
Sounds good @micwade-aws, thanks for your quick help on this!
