### ISSUE TITLE
batch_size is not sufficient to determine the shape of input tensor

### ISSUE THREAD

**Issue by Pan-EDU** [aws/aws-neuron-sdk#162]
Hi Neuron team,

I try to compile Fast R-CNN (by tensorflow) with your compiler(aws_neuron_tensorflow_p36 environment).
But an error occurred:

> ValueError: batch_size is not sufficient to determine the shape of input tensor Tensor("image:0", shape=(?, ?, 3), dtype=float32)

Does this mean neuron compiler don’t support dynamic shapes?

I save this model by
```
inputs = tf.get_default_graph().get_tensor_by_name("image:0")
output1 = tf.get_default_graph().get_tensor_by_name("output/boxes:0")
output2 = tf.get_default_graph().get_tensor_by_name("output/scores:0")
output3 = tf.get_default_graph().get_tensor_by_name("output/labels:0")
tf.saved_model.simple_save(
    sess,
    export_dir= MODEL_DIR,
    inputs= {'input': inputs},
    outputs= {'boxes': output1, 'scores':output2, 'labels':output3}
)
```
If neuron don’t support tensorflow dynamic shapes, how can I store models in fixed shapes?

There's model info by `saved_model_cli show `:

signature_def['serving_default']:
  The given SavedModel SignatureDef contains the following input(s):
    inputs['input'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1, -1, 3)
        name: image:0
  The given SavedModel SignatureDef contains the following output(s):
    outputs['boxes'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1, 4)
        name: output/boxes:0
    outputs['labels'] tensor_info:
        dtype: DT_INT64
        shape: (-1)
        name: output/labels:0
    outputs['scores'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1)
        name: output/scores:0

Thanks in advance!

**Comment by aws-renfu** [comment]
Thank you for the feedback. We will look into this and get back to you shortly.

**Comment by aws-renfu** [comment]
Inferentia requires fixed tensor shapes and the error message indicates that it is not able to infer tensor shapes using default batch size 1. Please make use of the "model_shape_feed_dict" or "model_feed_dict" argument in `tfn.saved_model.compile`. In interactive python, `help(tfn.saved_model.compile)` can display a full list of accepted argument.

**Comment by aws-renfu** [comment]
Separately, we are actively working on the compilation of Fast R-CNN. Please see our roadmap: https://github.com/aws/aws-neuron-sdk/projects/2#column-7472362. Thanks.

**Comment by mrnikwaws** [comment]
I am closing this issue, since the specific question "How do I set my input dimensions?", and the implied question "How do I make RCNN models run on AWS Neuron?" (roadmap) have both been addressed.

Please re-open this ticket if you have further questions.

**Comment by vuquocan1987** [comment]
Following on the topic, how do you deal with the model that allow free input size. At my work, I have to deploy a text detection model, which allowed free input size. 

If I try to resize the input image the quality of prediction goes down tremendously ( ~ 15 - 20 % ). 
How do you deal with that ?
