### ISSUE TITLE
Can't Compile HuggingFace MarianMT

### ISSUE THREAD

**Issue by hamishhuggard** [aws/aws-neuron-sdk#163]
I'm trying to compile a [HuggingFace MarianMT](https://huggingface.co/transformers/model_doc/marian.html) model using Neuron. I've tried modifying the code in the [Huggingface BERT Tutorial](https://github.com/aws/aws-neuron-sdk/blob/master/src/examples/pytorch/bert_tutorial/tutorial_pretrained_bert.ipynb), and running it in the `aws_neuron_pytorch_p36` conda environment with `Transformers` installed. No dice.

Here's my code:
```
from transformers import MarianMTModel, MarianTokenizer
import torch
import torch_neuron

model_name = 'Helsinki-NLP/opus-mt-en-ROMANCE'
tokenizer = MarianTokenizer.from_pretrained(model_name)
model = MarianMTModel.from_pretrained(model_name)

example_txt = [
    '>>fr<< this is a sentence in english that we want to translate to french',
    '>>pt<< This should go to portuguese',
    '>>es<< And this to Spanish'
]

encode_example = tokenizer.encode_plus(example_txt[0], max_length=512, pad_to_max_length=True, return_tensors='pt')

# Convert example inputs to a format that is compatible with TorchScript tracing
example_inputs = encode_example['input_ids'], encode_example['attention_mask'] #, encode_example['token_type_ids']

# Run torch.neuron.trace to generate a TorchScript that is optimized by AWS Neuron, using optimization level -O2
model_neuron = torch.neuron.trace(model, example_inputs, compiler_args=['-O2'])
```
Here's the error
```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-6-1249abcc7d13> in <module>
      4 
      5 # Run torch.neuron.trace to generate a TorchScript that is optimized by AWS Neuron, using optimization level -O2
----> 6 model_neuron = torch.neuron.trace(model, example_inputs_paraphrase, compiler_args=['-O2'])

~/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch_neuron/convert.py in trace(func, example_inputs, fallback, op_whitelist, minimum_segment_size, debug_must_trace, compiler_workdir, **kwargs)
     43         return node.type_string in op_whitelist
     44 
---> 45     neuron_graph, jit_trace = to_graph(func, example_inputs, return_trace=True)
     46     num_ops_before_fusing = len([op for op in neuron_graph.operations if _is_compute_op(op)])
     47 

~/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch_neuron/convert.py in to_graph(func_or_mod, example_inputs, return_trace)
     96     neuron_graph = graph.Graph()
     97     neuron_graph.import_jit_graph(jit_trace.graph)
---> 98     neuron_graph = optimize.unroll_call_method(neuron_graph, jit_trace)
     99     neuron_graph = optimize.resolve_call_function(neuron_graph, script_tracker)
    100     if neuron_graph is None:

~/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch_neuron/optimize.py in unroll_call_method(neuron_graph, jit_trace)
     61             module_neuron_graph = graph.Graph()
     62             module_neuron_graph.import_jit_graph(jit_module.graph)
---> 63             module_neuron_graph = unroll_call_method(module_neuron_graph, jit_module)
     64             module_op = graph.CallMethodOperation('{}#{}'.format(jit_module.original_name, op.index))
     65             module_op.import_graph(module_neuron_graph, op.input_uniques, op.output_uniques)

~/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch_neuron/optimize.py in unroll_call_method(neuron_graph, jit_trace)
     61             module_neuron_graph = graph.Graph()
     62             module_neuron_graph.import_jit_graph(jit_module.graph)
---> 63             module_neuron_graph = unroll_call_method(module_neuron_graph, jit_module)
     64             module_op = graph.CallMethodOperation('{}#{}'.format(jit_module.original_name, op.index))
     65             module_op.import_graph(module_neuron_graph, op.input_uniques, op.output_uniques)

~/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch_neuron/optimize.py in unroll_call_method(neuron_graph, jit_trace)
     58             new_neuron_graph.run_op(op, new_neuron_graph.unique_tensor_map)
     59         if op_type.is_call_method(op.type_string):
---> 60             jit_module = new_neuron_graph.unique_tensor_map[op.input_uniques[0]]
     61             module_neuron_graph = graph.Graph()
     62             module_neuron_graph.import_jit_graph(jit_module.graph)

KeyError: 1
```
How to fix?

**Comment by aws-renfu** [comment]
Thanks for the feedback. We are actively investigating this issue.

**Comment by aws-taylor** [comment]
Hello Hamish,

 We were able to reproduce and fix this issue as part of our [Sept. 22 release](https://github.com/aws/aws-neuron-sdk/blob/master/release-notes/torch-neuron.md).  At this time, it appears we have limited operator support for this network, so I encourage you to follow our release notes as we continue to add expanded our operator coverage. Also, if you are using Conda, please be aware of a [limitation](https://github.com/aws/aws-neuron-sdk/blob/master/release-notes/conda/conda-torch-neuron.md#known-issues-updated-9222020) when upgrading packages. 

Regards,
Taylor

**Comment by awsrjh** [comment]
@hamishhuggard checking int to see if this has helped at all. We are still working on adding more operators which will reduce the fragmentation of this graph following compilation, but we want to check that you have made some progress in the mean time.

**Comment by hamishhuggard** [comment]
We've switched to using a GPU machine.

**Comment by aws-zejdaj** [comment]
Hello Hamish,

We also resolved one issue in compiler with compile-time constant inputs and we will test if it improves public Hugging Face model.
Feel free to reach us directly at  aws-neuron-support@amazon.com

**Comment by aws-zejdaj** [comment]
Just to share some updates:  We we able to compile large portions of the model with our release preview. There are still unsupported operators which causes the model to be split into 17 accelerated partitions. We are debugging and evaluating inference speed.

**Comment by mrnikwaws** [comment]
Hi Hamish - a quick update: we are continuing to work on this issue - but no concrete updates yet

**Comment by aws-taylor** [comment]
Hello @hamishhuggard ,

 We think we have fixed the issue and are trying to perform final verification. Assuming that work goes well, the fix will be available in our next release. As always, we'll continue to update this issue as we get more information.

Regards,
Taylor

**Comment by micwade-aws** [comment]
@hamishhuggard - This is still under active debug. Will continue to update here as we make progress.

**Comment by aws-zejdaj** [comment]
@hamishhuggard  - We are still working on it.

**Comment by aws-taylor** [comment]
Hello @hamishhuggard  ,

  Please see the new PyTorch MarianMT tutorial in the documentation for help compiling generative models:
https://awsdocs-neuron.readthedocs-hosted.com/en/latest/neuron-guide/neuron-frameworks/pytorch-neuron/tutorials/transformers-marianmt.html

I'm going to resolve this issue, but please feel free to reach back to us if you have any further questions.

Regards,
Taylor

**Comment by AlviseSembenico** [comment]
Hi, thank you for the support. How can I make the notebook running on batch inference?

**Comment by phaterpekar** [comment]
How do these run with the Data Parallel Inference API ? Seems like these don't seem to be supported on torch >= 1.8 which is required for parallelization? Without that support only one core is being utilized at best. Also the performance is quite poor(similar to CPU) on max_encoder_ length/Max_decoder_lengths of 128 or 256 which is required for translating longer sentences.
