### ISSUE TITLE
The runtime was unable to allocate a resource

### ISSUE THREAD

**Issue by renatoviolin** [aws/aws-neuron-sdk#178]
While trace the model, deeplab-v3, pytorch, using the conda env, I'm getting this message.

```
-- Use compile_from_neff function
-- Use create_runnable function
[E neuron_runtime.cpp:269] NeuronDevice::process_nrtd_response: Context=NRTD_CTX_LOAD NRTD response code 'NERR_RESOURCE' (4) The runtime was unable to allocate a resource for the requested operation. Raw runtime error message '[TDRV:dma_mp_allocate_dma_buffer_from_tdram] Could not satisfy request for 2097152 bytes from channel
[TDRV:dma_mp_create_mla_buf] TDRAM 0/0 has no free space
[TDRV:dma_mp_alloc] Failed to create MLA buffer
[TDRV:alloc_tmp_buf_entry] failed to alloc DMA TMP_BUF mem for TMP2742
[TDRV:mem_ref_to_addr_model] failed to alloc DMA TMP BUF mem for TMP2742
[TDRV:kbl_model_add] create_data_refill_rings() error
[NMGR:dlr_kelf_stage] Failed to load subgraph
[NMGR:stage_kelf_models] Failed to stage graph: kelf-a.json to NeuronCore
[NMGR:kmgr_load_nn] Failed to load NN: 1.0.20600.0+0.b426b885f-/tmp/tmp9a9qiqfg, err: 4
'
WARNING:Neuron:torch.neuron.trace failed on <torch_neuron.graph.Graph object at 0x7efdb40159e8>; falling back to native python function call
WARNING:Neuron:torch.neuron.trace error: NeuronDevice::process_nrtd_response: Context=NRTD_CTX_LOAD NRTD response code 'NERR_RESOURCE' (4) The runtime was unable to allocate a resource for the requested operation. Raw runtime error message '[TDRV:dma_mp_allocate_dma_buffer_from_tdram] Could not satisfy request for 2097152 bytes from channel
[TDRV:dma_mp_create_mla_buf] TDRAM 0/0 has no free space
[TDRV:dma_mp_alloc] Failed to create MLA buffer
[TDRV:alloc_tmp_buf_entry] failed to alloc DMA TMP_BUF mem for TMP2742
[TDRV:mem_ref_to_addr_model] failed to alloc DMA TMP BUF mem for TMP2742
[TDRV:kbl_model_add] create_data_refill_rings() error
[NMGR:dlr_kelf_stage] Failed to load subgraph
[NMGR:stage_kelf_models] Failed to stage graph: kelf-a.json to NeuronCore
[NMGR:kmgr_load_nn] Failed to load NN: 1.0.20600.0+0.b426b885f-/tmp/tmp9a9qiqfg, err: 4
```

The command fails but generate a model. When running the model, it not uses the inferentia device.

**Comment by aws-taylor** [comment]
Hello @renatoviolin,

  The error you are seeing occurs when a model is partitioned into too many inferentia-compatible subgraphs such that they will not fit on the chip's memory. The most common reason for this occurring is because the graph contains operators that are not (yet!) supported. You can analyze the model to understand operator support by using:

```results = torch.neuron.analyze_model( model, example_inputs )```

Since you are using deeplab-v3, one possible mitigation would to experiment with different backbones. These may have different levels of operator support.  

We are working on improvements to `analyze_model` that will give even better diagnostic output in the next release, as well as our ongoing operator support projects. 

Would it be possible for you to share your model/code? If it is sensitive, you can message me directly. That would allow us to better debug.

Regards,
Taylor

**Comment by aws-taylor** [comment]
Hello again @renatoviolin,

 After brainstorming with my peers, another potential mitigation would be to try to use Tensorflow's version of deeplab-v3. The operators supported from PyTorch and Tensorflow are different, so you may get better coverage.

Regards,
Taylor

**Comment by renatoviolin** [comment]
Hi Taylor, 
thanks for your answers.

If you wanna try:

```
pip install torch torchvision
```

```
import torch
from torchvision import models

dlab = models.segmentation.deeplabv3_resnet101(pretrained=1).eval()
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

image = torch.zeros([1, 3, 640, 640], dtype=torch.float32)
pred = model.forward(image)['out']
print(pred.shape)
```

**Comment by aws-joshim** [comment]
@renatoviolin We've identified the issue within the Neuron Compiler (neuron-cc) and are working on a fix.  Please leave this issue open and we'll update when a fix is released

**Comment by jeffhataws** [comment]
@renatoviolin just want to let you know that we are actively working on a fix. Thanks.

**Comment by renatoviolin** [comment]
@jeffhataws thanks. As we need to deploy the application, we reserved a GPU instance until we can use the inferentia one.

**Comment by mrnikwaws** [comment]
@renatoviolin - we are continuing to work on this issue and will provide more updates here as they become available

**Comment by aws-taylor** [comment]
Hello @renatoviolin,

  We think we have fixed the issue and are performing final verification. Assuming that work goes well, the fix will be in our next release. As always, we'll continue to update this issue as we get more information.

Regards,
Taylor

**Comment by micwade-aws** [comment]
@renatoviolin - This remains under debug.  Will keep updating you as we make progress towards fixing this with a release.

**Comment by aws-zejdaj** [comment]
@renatoviolin We have resolved the issue and our internal test passed. We'll update you once the fix is released.

**Comment by aws-renfu** [comment]
Neuron releae 1.12 is now available: https://awsdocs-neuron.readthedocs-hosted.com/en/latest/release-notes/README.html. We have fixed this issue in this release. Please take a look.

**Comment by mrnikwaws** [comment]
Closing since we believe this is issue is not resolved.  Please re-open if you still have and issue
