### ISSUE TITLE
Pegasus Huggingface model compilation issue

### ISSUE THREAD

**Issue by aws-joshim** [aws/aws-neuron-sdk#182]
Hi,

Thanks @AWSGH

I have used the following code to compile the model and it was successful in compiling with a lot of warnings

import tensorflow
import torch
import torch.neuron
from transformers import AutoTokenizer, AutoModelForSequenceClassification

# Build tokenizer and model
tokenizer = AutoTokenizer.from_pretrained("sshleifer/distill-pegasus-cnn-16-4")
model = AutoModelForSequenceClassification.from_pretrained("sshleifer/distill-pegasus-cnn-16-4")

example_txt = [
    'this is a sentence in english that we want to summarize',
]

encode_example = tokenizer.encode_plus(example_txt[0],truncation=True, padding='longest',  max_length=1024, pad_to_max_length=True, return_tensors='pt')
example_inputs = encode_example['input_ids'], encode_example['attention_mask'] #, encode_example['token_type_ids']
model_neuron = torch.neuron.trace(model, example_inputs, compiler_args=['-O2'])
model_neuron.save('pegasus_neuron.pt')
When I am trying to infer the sentence. I am getting error.

Inference code:

from transformers import AutoTokenizer, AutoModelWithLMHead

import os
import torch
import torch_neuron

    

class DistillSummarizeLarge:
    def __init__(self):
        self.device = Config.device
        _cache = Config.mount
        self.tokenizer = AutoTokenizer.from_pretrained(
            "sshleifer/distill-pegasus-cnn-16-4", cache_dir=_cache)
        self.model = torch.jit.load('pegasus_neuron.pt')
        #self.model.eval()

    def __call__(self, text):
        batch = self.tokenizer.encode_plus(
            text, truncation=True, padding='longest',return_tensors="pt")
        
        batch_new = batch['input_ids'], batch['attention_mask']
        translated = self.model(*batch_new)
        tgt_text = self.tokenizer.batch_decode(
            translated, skip_special_tokens=True)
        return tgt_text

summarizer = DistillSummarizeLarge()
print(summarizer('''It indicates a way to close an interaction, or dismiss a notification. Good Subscriber Account active since Edit my Account Premium Articles Upgrade Membership Email Preferences My Subscription FAQs Logout DOW S&P 500 NASDAQ 100 Close icon Two crossed lines that form an 'X'. It indicates a way to close an interaction, or dismiss a notification. Streaming Software & Apps Smart Home Smartphones Laptops & Tablets Gaming Gadgets More Button Icon Circle with three vertical dots'''))

I am getting the below error:

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-6-e49367b7b011> in <module>
      1 summarizer = DistillSummarizeLarge()
      2 
----> 3 print(summarizer('''It indicates a way to close an interaction, or dismiss a notification. Good Subscriber Account active since Edit my Account Premium Articles Upgrade Membership Email Preferences My Subscription FAQs Logout DOW S&P 500 NASDAQ 100 Close icon Two crossed lines that form an 'X'. It indicates a way to close an interaction, or dismiss a notification. Streaming Software & Apps Smart Home Smartphones Laptops & Tablets Gaming Gadgets More Button Icon Circle with three vertical dots'''))

<ipython-input-2-ac180eb64b6e> in __call__(self, text)
     27 
     28         batch_new = batch['input_ids'], batch['attention_mask']
---> 29         translated = self.model(*batch_new)
     30         tgt_text = self.tokenizer.batch_decode(
     31             translated, skip_special_tokens=True)

~/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    548             result = self._slow_forward(*input, **kwargs)
    549         else:
--> 550             result = self.forward(*input, **kwargs)
    551         for hook in self._forward_hooks.values():
    552             hook_result = hook(self, input, result)

RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript, serialized code (most recent call last):
  File "code/__torch__/torch_neuron/convert.py", line 74, in forward
    _58 = torch.slice(tensor6, 0, 0, 9223372036854775807, 1)
    tensor7 = torch.slice(_58, 1, 1, 9223372036854775807, 1)
    tensor8 = torch.view(tensor5, [13])
              ~~~~~~~~~~ <--- HERE
    _59 = torch.expand(tensor8, [1, 13], implicit=True)
    _60 = torch.copy_(tensor7, _59, False)

Traceback of TorchScript, original code (most recent call last):
/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch_neuron/resolve_function.py(49): func
/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch_neuron/graph.py(195): __call__
/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch_neuron/graph.py(85): run_op
/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch_neuron/graph.py(74): __call__
/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch_neuron/convert.py(106): forward
/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch/nn/modules/module.py(534): _slow_forward
/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch/nn/modules/module.py(548): __call__
/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch/jit/__init__.py(1027): trace_module
/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch/jit/__init__.py(875): trace
/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch_neuron/convert.py(87): trace
compile.py(24): <module>
RuntimeError: shape '[13]' is invalid for input of size 87
Could you please look into this issue and help me in resolving this issue.

**Comment by aws-joshim** [comment]
Pegasus model for Summarization (https://huggingface.co/sshleifer/distill-pegasus-cnn-16-4 is the link to the model referenced above

**Comment by aws-joshim** [comment]
Hi karthikgali

Thanks for reporting this issue. AWS Neuron compiles for fixed tensor sizes. At the moment the model that you are using for compilation is varying tensor shapes. You can correct this as follows:

import tensorflow
import torch
import torch.neuron

from transformers import PegasusForConditionalGeneration, PegasusTokenizer
from transformers.generation_utils import GenerationMixin

model_name = "sshleifer/distill-pegasus-cnn-16-4"
tokenizer = PegasusTokenizer.from_pretrained(model_name)
model = PegasusForConditionalGeneration.from_pretrained(
    model_name).to("cpu")
model.eval()

example_txt = [
    'PG&E stated it scheduled the blackouts in response to forecasts for high winds amid dry conditions. The aim is to reduce the risk of wildfires. Nearly 800 thousand customers were scheduled to be affected by the shutoffs which were expected to last through at least midday tomorrow.',
]

max_length = 1024

batch = tokenizer.prepare_seq2seq_batch(
    example_txt, truncation=True, max_length=max_length, padding='max_length').to("cpu")

print(batch)

with torch.no_grad():
    output = model.generate(**batch)
Beyond this there the model is currently fragmented by a small number of unsupported operators and produces many small neuron sub-models that will not give you a performance boost.

We're also thinking about ways to make the 'generate' function easily accessible after compilation. At the moment once you do compile there would be additional work to format the outputs in a human readable way.

We'll keep working on these issues, but the constant padding recommendation may be useful to you for compiling and testing with other models in the meantime.

**Comment by mrnikwaws** [comment]
Hi karthikgali,

Thanks for reporting this issue.  AWS Neuron compiles for fixed tensor sizes.  At the moment the model that you are using for compilation is varying tensor shapes.  You can correct this with constant padding as follows:

```
import tensorflow
import torch
import torch.neuron

from transformers import PegasusForConditionalGeneration, PegasusTokenizer
from transformers.generation_utils import GenerationMixin

model_name = "sshleifer/distill-pegasus-cnn-16-4"
tokenizer = PegasusTokenizer.from_pretrained(model_name)
model = PegasusForConditionalGeneration.from_pretrained(
    model_name).to("cpu")
model.eval()

example_txt = [
    'PG&E stated it scheduled the blackouts in response to forecasts for high winds amid dry conditions. The aim is to reduce the risk of wildfires. Nearly 800 thousand customers were scheduled to be affected by the shutoffs which were expected to last through at least midday tomorrow.',
]

max_length = 1024

batch = tokenizer.prepare_seq2seq_batch(
    example_txt, truncation=True, max_length=max_length, padding='max_length').to("cpu")

print(batch)

with torch.no_grad():
    output = model.generate(**batch)
```

Beyond this there the model is currently fragmented by a small number of unsupported operators and produces many small neuron sub-models that may not give you a performance boost.

We're also thinking about ways to make the 'generate' function easily accessible after compilation.  At the moment once you do compile there would be additional work to format the outputs in a human readable way.

We'll keep working on these issues, but the constant padding recommendation may be useful to you for compiling and testing with other models in the meantime.

**Comment by awsrjh** [comment]
Hi karthikgali

have our suggestions helped you? If not please let us know.

**Comment by karthikgali** [comment]
Hi @awsrjh 

Thanks for reaching out againg.


I haven't tried it because of the below comment:
**Beyond this there the model is currently fragmented by a small number of unsupported operators and produces many small neuron sub-models that will not give you a performance boost.**

Could you please let me know if all the operators are supported now? If yes, I will take a look into it.

Regards,
Karthik

**Comment by aws-taylor** [comment]
Hello Karthik,

 You can use the `torch.neuron.analyze_model` method to collect information about the operator support in your network.  You can find an example of how to use this method [here](https://awsdocs-neuron.readthedocs-hosted.com/en/latest/neuron-guide/neuron-frameworks/pytorch-neuron/tutorials/getting_started.html?highlight=analyze#step-3-compile-on-compilation-instance).

With regards to your original question - we are continuing to debug and fix the issue. In particular, the Neuron SDK does not currently handle generative models that use cached or pre-computed state very well. We are working to address this issue.

Regards,
Taylor

**Comment by karthikgali** [comment]
Thanks @aws-taylor for your update. Do we have any ETA for handling generative models?

**Comment by aws-joshim** [comment]
@karthikgali, In order to make generative functions work with torch_neuron, we need to invoke the encoder/decoder components of the Pegasus model using fixed sized tensors on every iteration of generate. We plan to provide example code to demonstrate torch.jit.trace and torch.neuron.trace for the Pegasus model. We are currently working on an unrelated compilation issue for the Pegasus model. The Pegasus HF model is now tracked on the Neuron roadmap @ https://github.com/aws/aws-neuron-sdk/issues/225. We encourage you to “Watch” the associated roadmap item for progress updates on model compilation and inference status

**Comment by aws-taylor** [comment]
Hello @karthikgali,

 I am going to resolve this issue in favor of the aforementioned roadmap item. Please do not hesitate to re-open or submit a new issue if you have any further questions.

Regards,
Taylor
