### ISSUE TITLE
Not the neuron but CPU is aggressively used in torch-neuron inference tutorial

### ISSUE THREAD

**Issue by Tagussan** [aws/aws-neuron-sdk#184]
Hi,

I've successfully followed [torch-neuron tutorial](https://github.com/aws/aws-neuron-sdk/blob/master/docs/pytorch-neuron/tutorial-compile-infer.md). I did both of compilation and inference on the inf1 instance. After compilation, I got the same inference result on my inf1.xlarge instance. However, watching neuron-top and htop during the inference, CPU is aggressively used and neuron-top shows nothing. 

I tried increasing the inference load by replacing
```
results = model_neuron( image )
```
into
```
for _ in range(1000):
    results = model_neuron( image )
```
but still neuron-top shows nothing. 
I also tried [tensorflow tutorial](https://github.com/aws/aws-neuron-sdk/blob/master/docs/tensorflow-neuron/tutorial-compile-infer.md), and neuron-top shows its load, which means the neuron chip is actually used. 

Are any additional settings required to run torch-neuron?

**Comment by awsrjh** [comment]
Hi 

That sounds like you may not have any compiled model actually running on the inferentia. 

Could you send us the output of neuron-top ? And also neuron-cli list-model after executing the model jit load and predict calls ?

**Comment by Tagussan** [comment]
Hi awsrjh. Thanks for the reply.

Thank God it's now solved. At the first time, I followed this [Pytorch-neuron document on docs.aws.amazon.com ](https://docs.aws.amazon.com/ja_jp/dlami/latest/devguide/tutorial-inferentia-pytorch-neuron.html) to compile the model. In the document, the following code is used:
```
model_neuron = torch.neuron.trace(model, example_inputs=[image])
```
If I use this code, the problem occur. 

However, the code in [Pytorch-neuron document on GitHub](https://github.com/aws/aws-neuron-sdk/blob/master/docs/pytorch-neuron/tutorial-compile-infer.md) is slightly different in terms of compiler flag:
```
model_neuron = torch.neuron.trace(model, example_inputs=[image], compiler_args="-O2")
```
If I use this code, the compiled model successfully uses neuron chip. The neuron-top shows load when I execute inference. 

I think it is better to update the code in the example hosted on docs.aws.amazon.com.

**Comment by awsrjh** [comment]
thanks for the heads-up -- we will get that fixed!

closing this

**Comment by awsrjh** [comment]
Also please note: 

we have replaced the tutorial you pointed to (https://github.com/aws/aws-neuron-sdk/blob/master/docs/pytorch-neuron/tutorial-compile-infer.md ) with a new one:  

https://github.com/aws/aws-neuron-sdk/blob/master/src/pytorch/getting_started.md

which does not use the -O2 option either - as that option has now been made default. We documented this here:

https://github.com/aws/aws-neuron-sdk/blob/master/release-notes/neuron-cc.md#major-new-features
