### ISSUE TITLE
Starting Neuron nrtd-container throws an error message "No device specified" with aws-neuron-runtime_1.1.1402.0 and aws-neuron-runtime-base-1.0.8126.0

### ISSUE THREAD

**Issue by musunita** [aws/aws-neuron-sdk#192]
I have installed aws-neuron-runtime_1.1.1402.0 and aws-neuron-runtime-base-1.0.8126.0 packages and see these error messages on starting Neuron nrtd-container. Is this expected?

**Log snippet:**
```
docker run --env AWS_NEURON_VISIBLE_DEVICES="0" --cap-add SYS_ADMIN --cap-add IPC_LOCK -v /tmp/neuron_rtd_sock/:/sock neuron-rtd
nrtd[1]: [NRTD:nrtd_main] nrtd build using:1.1.1402.0
nrtd[1]: [NMGR:kmgr_init_mlas] No devices specified
nrtd[1]: [NRTD:InitTongas] Failed to initialize devices, error:2
nrtd[1]: [NRTD:nrtd_main] Failed to initialize devices: , attempt: 1
```

**Comment by aws-awaran** [comment]
if using neuron runtime version >= 1.1.1402.0, make sure that latest version of the aws-neuron-runtime-base and aws-neuron-dkms is installed.
Refer to install guide: https://github.com/aws/aws-neuron-sdk/blob/master/docs/neuron-install-guide.md
