### ISSUE TITLE
onnx model compilation error

### ISSUE THREAD

**Issue by dbxinj** [aws/aws-neuron-sdk#195]
Hi team,

I tried the aws-neuron-sdk command line tool to compile an onnx model (resnet model), but I got this error and I had no idea what's the cause for this issue:
![image](https://user-images.githubusercontent.com/13883280/97977069-94cc8300-1e06-11eb-8a25-8d3dcf7e6fad.png)

I was using the Deep Learning AMI (Ubuntu 18.04) Version 36.0 (ami-068f673b54015684e) on a c5.4xlarge instance.
The compilation was run inside this pre-installed virtual environment: 
![image](https://user-images.githubusercontent.com/13883280/97977361-102e3480-1e07-11eb-9e69-4568dea0b676.png)

Do you have any ideas?

**Comment by aws-zejdaj** [comment]
Hi Xin,

We are looking into it, trying to reproduce the issue on a similar public model (Resnet50 v2). If you can share this specific  v3 model with us that would help us as well.

Also please note that ONNX support in neuron-sdk is limited. In the meantime can you try eg a Tensorflow model?

**Comment by dbxinj** [comment]
Hi,

I've uploaded the model to google drive, you should be able to access the model by the following link: https://drive.google.com/file/d/1xT1mm5fSNTQ_WzGBxveE0_O4rMvlBlTh/view?usp=sharing

Actually, I also tested neuron compilation for other models with different backbones, like mobilenet_v2, efficientnet.
For mobilenet_v2, I got a different error message:
![image](https://user-images.githubusercontent.com/13883280/98192326-ce5fd400-1f55-11eb-85a0-6952af4d987d.png)
When I ran `neuron-cc list-operators --framework ONNX`, I could find the operator `Flatten` is included. I suppose it should be supported.

BTW, the test models are originally trained by caffe or pytorch. To make the test flow consistent across different models (caffe model is not supported by aws-neuron-sdk), I intended to convert all models to onnx models and run the inference flow.

Maybe I can try compilation with a pytorch model, or convert caffe/onnx model to tensorflow model for compilation. But I'm just wondering if there are some unsupported operators for some specific models, how should I make it work? Is there a way for developers to self-implement those operators and re-generate the sdk toolkit by ourselves?

**Comment by awsrjh** [comment]
We do support Pytorch also. Please see this as a starting point:

**Comment by awsrjh** [comment]
Hi

yes - we do support Pytorch and it may be a nice way to use an integrated workflow that does both compile and inference together (we have integrated our compiler and runtime into Pytorch for this).

Please see: https://github.com/aws/aws-neuron-sdk/tree/master/docs/pytorch-neuron

At this point, unfortunately, adding user operators is not possible - but it is something we are thinking about. 

Let us review your model to see what we can do.... thanks for your patience.

**Comment by dbxinj** [comment]
Hi,

Please also help to check the mobilenet_v2 onnx model (https://drive.google.com/file/d/1d1RnIcVJd5Nk2ApMeJTrbBuFqhBngp5W/view?usp=sharing), which has the compilation issue with the `Flatten` operator.
Thanks for your help.

**Comment by aws-zejdaj** [comment]
Hi Xin, thanks for the models. I was able to reproduce both issues - shape handling error on resnet50 as well as the unsupported flatten operator on mobile net. We are investigating.

**Comment by dbxinj** [comment]
Hi team, are there any updates about this issue? Or are there any plans to solve the issue?

**Comment by aws-renfu** [comment]
> Hi team, are there any updates about this issue? Or are there any plans to solve the issue?

Hi Xin,

Please see our release note: https://github.com/aws/aws-neuron-sdk/tree/master/release-notes#november-17-2020. 

However, we would like to offer additional help.  Please let us know if ONNX is the only thing that will work or if there are other ways? For example, our support for ONNX is very limited and will require a direct usage of our runtime. As another example, when operators are not supported or better done in the cpu it will be much easier to remain in the native framework.

Please let us know. Thanks.

**Comment by aws-taylor** [comment]
Hello Xin,

  We haven't heard from you in a while, so I'm going to go ahead and resolve this issue. Feel free to re-open if you have any additional problems or questions.

Regards,
Taylor
