### ISSUE TITLE
Frameworks:  PyTorch 1.7 support

### ISSUE THREAD

**Issue by AWSGH** [aws/aws-neuron-sdk#197]
Add Neuron support fro PyTorch 1.7

**Comment by aws-joshim** [comment]
Neuron SDK added support for Pytorch 1.7 as a part of the December 2020 release. Pytorch 1.7 based torch neuron package installation details are at https://awsdocs-neuron.readthedocs-hosted.com/en/latest/neuron-intro/install-pytorch.html

**Comment by aws-joshim** [comment]
Closing since Pytorch 1.7 support has been added to torch neuron
