### ISSUE TITLE
Torch-Neuron fails to compile ResNeXt

### ISSUE THREAD

**Issue by Tagussan** [aws/aws-neuron-sdk#202]
Hi,

I have a problem with compiling ResNeXt using Torch-Neuron. When I use `torch.neuron.trace` to RexNeXt model, I get the following error: 
```
WARNING:root:The following operations are currently supported in torch-neuron for this model
WARNING:root:aten::t
WARNING:root:prim::TupleConstruct
WARNING:root:aten::max_pool2d
WARNING:root:aten::add
WARNING:root:prim::GetAttr
WARNING:root:aten::size
WARNING:root:aten::_convolution
WARNING:root:prim::ListConstruct
WARNING:root:aten::avg_pool2d
WARNING:root:aten::view
WARNING:root:prim::Constant
WARNING:root:prim::NumToTensor
WARNING:root:prim::TupleUnpack
WARNING:root:aten::addmm
WARNING:root:aten::relu
WARNING:root:aten::Int
WARNING:root:aten::batch_norm
WARNING:root:The following operations are currently not supported in torch-neuron for this model
WARNING:root:100.00% of operations (3773 of 3773) are supported
WARNING:root:Limited tf.compat.v2.summary API due to missing TensorBoard installation.
WARNING:Neuron:torch.neuron.trace failed on <torch_neuron.graph.Graph object at 0x7f3f59d1ad30>; falling back to native python function call
WARNING:Neuron:torch.neuron.trace error:
```
I use following code to compile the model:
```
    model = resnext101_64x4d(pretrained=None)
    model.eval()
    data_in = torch.rand(2, 3, 224, 224)
    torch.neuron.analyze_model(model, example_inputs=[data_in])
    model_neuron = torch.neuron.trace(model, example_inputs=[data_in])
    model_neuron.save("resnext.pt")
```

Here's [the entire code](https://github.com/Tagussan/pretrained-models.pytorch/blob/master/pretrainedmodels/models/resnext.py) I use. To reproduce this, please run the following commands:
```
git clone https://github.com/Tagussan/pretrained-models.pytorch
cd pretrained-models.pytorch
python pretrainedmodels/models/resnext.py
```
I'm using `inf1.xlarge` instance with `Deep Learning AMI (Ubuntu 18.04) Version 35.0` to compile this. The version of neuron-cc compiler is `1.0.18001.0+0.5312e6a21`.

Any workaround for this error?

**Comment by aws-renfu** [comment]
Tagussan, 

Thank you for letting us know about this issue. We will take a quick look and get back to you.

**Comment by aws-joshim** [comment]
Hi Tagussan, we are able to recreate the compilation issues that you see with the ResNeXt model using Torch-Neuron. On further analysis, we have found that the compilation errors are related to missing support for the group convolution operation. We are looking into adding support for this operation in a subsequent Neuron SDK release

**Comment by Tagussan** [comment]
Hi joshim,
Thank you for the investigation of this issue. I understand that ResNeXt is not available in the current SDK.
I hope this model will be available on Inferentia soon. Could you notify me in this thread if group convolution operation got supported in the SDK?

**Comment by aws-joshim** [comment]
Hi Tagussan, we will post a update on this thread for the release timeline to support the group convolution operation

**Comment by aws-taylor** [comment]
Also related to group convolution - https://github.com/aws/aws-neuron-sdk/issues/214

**Comment by aws-joshim** [comment]
@Tagussan, We are working on Neuron SDK enablement for Pytorch ResNext and it has been added to our roadmap. We encourage you to “Watch” the associated roadmap item for it @ https://github.com/aws/aws-neuron-sdk/issues/226 for progress updates. We also encourage +1 to these roadmap items to let us know what would be helpful

**Comment by Tagussan** [comment]
@aws-joshim Thank you adding this to the roadmap! I'm looking forward to see the progress.
BTW, enjoy holidays and have a happy new year 😄

**Comment by aws-joshim** [comment]
> @aws-joshim Thank you adding this to the roadmap! I'm looking forward to see the progress.
> BTW, enjoy holidays and have a happy new year 😄

Happy new year to you from the AWS Inferentia team

**Comment by aws-zejdaj** [comment]
@Tagussan - we are still working on it.

**Comment by jeffhataws** [comment]
Hi @Tagussan, I am closing this ticket for now since we have put ResNext on our roadmap. Please let us know if you have any other issues. Thanks.
