### ISSUE TITLE
Models: add support for Marian MT

### ISSUE THREAD

**Issue by AWSGH** [aws/aws-neuron-sdk#224]
https://awsdocs-neuron.readthedocs-hosted.com/en/latest/neuron-guide/neuron-frameworks/pytorch-neuron/tutorials/transformers-marianmt.html

**Comment by dgallitelli** [comment]
Hi! Can we have an update on this please? Thanks!

**Comment by aws-renfu** [comment]
The next Neuron release will enable compilation and deployment of language generative models like Marian MT, and we will keep tuning performance with subsequent releases.

**Comment by AWSGH** [comment]
https://awsdocs-neuron.readthedocs-hosted.com/en/latest/neuron-guide/neuron-frameworks/pytorch-neuron/tutorials/transformers-marianmt.html

**Comment by phaterpekar** [comment]
How do these run with the Data Parallel Inference API ? Seems like these don't seem to be supported on torch >= 1.8 which is required for parallelization? Without that support only one core is being utilized at best. Also the performance is quite poor(similar to CPU) on max_encoder_ length/Max_decoder_lengths of 128 or 256 which is required for translating longer sentences.
