### ISSUE TITLE
torch.neuron.trace expects tensors - error while executing tutorial - tutorial_pretrained_bert.ipynb

### ISSUE THREAD

**Issue by C24IO** [aws/aws-neuron-sdk#229]
Downloading: 100%|██████████████████████████████| 433/433 [00:00<00:00, 760kB/s]
Downloading: 100%|███████████████████████████| 213k/213k [00:00<00:00, 40.8MB/s]
Downloading: 100%|███████████████████████████| 436k/436k [00:00<00:00, 46.3MB/s]
Downloading: 100%|███████████████████████████| 433M/433M [00:10<00:00, 42.3MB/s]
Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.
/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/transformers/tokenization_utils_base.py:2179: FutureWarning: The `pad_to_max_length` argument is deprecated and will be removed in a future version, use `padding=True` or `padding='longest'` to pad to the longest sequence in the batch, or use `padding='max_length'` to pad to a max length. In this case, you can give a specific length with `max_length` (e.g. `max_length=45`) or leave max_length to None to pad to the maximal input size of the model (e.g. 512 for Bert).
  FutureWarning,
/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/transformers/models/bert/modeling_bert.py:192: TracerWarning: Converting a tensor to a Python index might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  position_ids = self.position_ids[:, :seq_length]
/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/transformers/modeling_utils.py:1757: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  input_tensor.shape[chunk_dim] == tensor_shape for input_tensor in input_tensors
Traceback (most recent call last):
  File "/tmp/pycharm_project_424/compile-bert-example-neuron-sdk.py", line 27, in <module>
    model_neuron = torch.neuron.trace(model, example_inputs_paraphrase, compiler_args=['-O2'])
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch_neuron/convert.py", line 50, in trace
    neuron_graph, jit_trace = to_graph(func, example_inputs, return_trace=True)
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch_neuron/convert.py", line 186, in to_graph
    jit_trace = torch.jit.trace(func_or_mod, example_inputs)
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch/jit/__init__.py", line 875, in trace
    check_tolerance, _force_outplace, _module_class)
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch/jit/__init__.py", line 1027, in trace_module
    module._c._create_method_from_trace(method_name, func, example_inputs, var_lookup_fn, _force_outplace)
RuntimeError: Only tensors, lists and tuples of tensors can be output from traced functions

**Comment by awsrjh** [comment]
Hello - we are looking at this and will respond as soon as possible.

**Comment by C24IO** [comment]
Closing this issue, the problem here was the transformers version. This notebook works for transformers version less than 4, I tested this on transformers version 3.5.1 and was able to execute it without issues.
