### ISSUE TITLE
Is DLRM supported on inferentia?

### ISSUE THREAD

**Issue by zqliu19** [aws/aws-neuron-sdk#237]
https://ai.facebook.com/blog/dlrm-an-advanced-open-source-deep-learning-recommendation-model/

**Comment by aws-zejdaj** [comment]
@zqliu19  - While we have not tried it ourselves, Neuron auto partitioning will optimize the model deployment based on its supported operators and as a result may run some sub graphs within the framework. Please give it a try, we are here to help as needed.

**Comment by jeffhataws** [comment]
Hi @zqliu19. Let me close this ticket for now. Please reopen or file a new issue if you need further help on this. Thanks!
