### ISSUE TITLE
Is layer norm supported on inferentia?

### ISSUE THREAD

**Issue by zqliu19** [aws/aws-neuron-sdk#238]
layer norm is not in the supported op list here https://github.com/aws/aws-neuron-sdk/blob/master/release-notes/neuron-cc-ops/neuron-cc-ops-tensorflow.md

However, the BERT demo here https://github.com/aws/aws-neuron-sdk/tree/master/src/examples/tensorflow/bert_demo has layer norm, and it is running at FP32 precision by default.

Does this mean that layer norm is running on CPU with FP32?

(Also does inferentia support native FP32 run on neuron cores, seems FP32 will be automatically casted to bf16 if deployed to Neuron cores?

**Comment by aws-zejdaj** [comment]
Hi @zqliu19, yes, normalization is supported through the framework and typically translated to scale and offset during inference (Mul, Add).

FP32 is supported natively on Inferentia for some operations. Convolutional operations are cast to bf16. You can find more details on https://github.com/aws/aws-neuron-sdk/blob/master/docs/technotes/data-types.md

If you have a specific model or operator where you see any issue let us know and we'll be happy to take a look at it.

**Comment by mrnikwaws** [comment]
Closing this issues since there has been no discussion for 20 days- please re-open if we can provide more help.
