### ISSUE TITLE
When the inference benchmark release will be released?

### ISSUE THREAD

**Issue by JustinhoCHN** [aws/aws-neuron-sdk#24]
We are interested to see the inference benchmark report, and comparision between T4, including inference time cost, and thoughput. It would be great if you guys release it.

**Comment by AWSGH** [comment]
Hi JustinhoCHN,

Thanks for your note. Please take a look at the Inf1 session from re:invent 2019, it has comparison slides showing BERTbase, as well as detailed report from Alexa TTS team on their Inf1 migration results compared to G4 and P3. But the best would be of course to try out your application on Inf1, would be great to get your feedback. 

re:Invent CMP324 session: https://www.youtube.com/watch?v=17r1EapAxpk 

Best regards,
Gadi

**Comment by aws-taylor** [comment]
Hello JustinhoCHN,

 Is there any further assistance I can offer at this time?

Regards,
Taylor

**Comment by micwade** [comment]
Since we haven’t heard back in a while we are closing this issue, please reopen it if more support from us is needed.
