### ISSUE TITLE
Unable to load converted model

### ISSUE THREAD

**Issue by hovhanns** [aws/aws-neuron-sdk#240]
I converted DenseNet model from Pytorch to neuron without any issues and saved the model. Now when I want to load the model using **torch.jit.load** to it throws error. 
_Unknown builtin op: neuron::forward_1.
Could not find any similar ops to neuron::forward_1. This op may not exist or may not be currently supported in TorchScript._
Is there any known workload to escape this issue?

**Comment by jeffhataws** [comment]
Hi hovhanns,

Thank you for reporting the issue. Please check if you have "import torch_neuron" in your inference script before using torch.jit.load. This ensures that the Neuron custom operation is registered.

**Comment by hovhanns** [comment]
Hi @jeffhataws,
Thanks for your response this solved the issue.
