### ISSUE TITLE
add inferentia/neuron sdk as backend to onnxruntime

### ISSUE THREAD

**Issue by hjander** [aws/aws-neuron-sdk#245]
onnxruntime is a widely supported to unify ML/DL inference. It implements onnx operators on  [several backends/accelarators](https://www.onnxruntime.ai/docs/get-started/inference.html#supported-accelerators) therefore allows a unified approach to inference for onnx models on any technological platform.

The benefits of adding the  inferentia/neuron-sdk as backend to onnxruntime would be hidden complexity for end users and therefore easier adoption of inferentia.

**Comment by AWSGH** [comment]
Thank you Hendrik for the comment. As we indicated in our documentation, we have decided to EOL our support for ONNX models. We have not seen strong customer demand. We may revisit this decision later on, if we see increased demand from our customers. I will go ahead and close this issue. If you'd like to further discuss, please email us at aws-neuron-support@amazon.com
