### ISSUE TITLE
add support for encoder-decoder model, e.g. BART 

### ISSUE THREAD

**Issue by anjiefang** [aws/aws-neuron-sdk#246]
I tried to compile a BART model (huggingface + pytorch). Here are the trace error:

```
RuntimeError                              Traceback (most recent call last)
<ipython-input-35-57617b2ff519> in <module>()
----> 1 model_neuron = torch.neuron.trace(encoder_decoder, input_ids)

/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch_neuron/convert.py in trace(func, example_inputs, fallback, op_whitelist, minimum_segment_size, subgraph_builder_function, subgraph_inputs_pruning, skip_compiler, debug_must_trace, allow_no_ops_on_neuron, compiler_workdir, _neuron_trace, **kwargs)
    174     if succesful_compilations == 0 and not allow_no_ops_on_neuron:
    175         raise RuntimeError(
--> 176             "No operations were successfully partitioned and compiled to neuron for this model - aborting trace!")
    177
    178     if percent_operations_compiled < 50.0:

RuntimeError: No operations were successfully partitioned and compiled to neuron for this model - aborting trace!
```

It seems that several operation are not currently supported. See the output from `torch.neuron.analyze_model`:
```
INFO:Neuron:The following operations are currently supported in torch-neuron for this model:
INFO:Neuron:aten::view
INFO:Neuron:aten::squeeze
INFO:Neuron:prim::TupleUnpack
INFO:Neuron:aten::dropout
INFO:Neuron:aten::sub
INFO:Neuron:prim::NumToTensor
INFO:Neuron:aten::Int
INFO:Neuron:aten::copy_
INFO:Neuron:aten::layer_norm
INFO:Neuron:aten::bmm
INFO:Neuron:aten::arange
INFO:Neuron:prim::Constant
INFO:Neuron:aten::sum
INFO:Neuron:aten::lt
INFO:Neuron:aten::to
INFO:Neuron:aten::gelu
INFO:Neuron:aten::softmax
INFO:Neuron:aten::ScalarImplicit
INFO:Neuron:aten::size
INFO:Neuron:aten::transpose
INFO:Neuron:prim::ListConstruct
INFO:Neuron:aten::ne
INFO:Neuron:aten::clone
INFO:Neuron:aten::unsqueeze
INFO:Neuron:aten::slice
INFO:Neuron:aten::matmul
INFO:Neuron:aten::select
INFO:Neuron:aten::masked_fill
INFO:Neuron:aten::contiguous
INFO:Neuron:aten::fill_
INFO:Neuron:aten::expand
INFO:Neuron:aten::zeros
INFO:Neuron:prim::TupleConstruct
INFO:Neuron:aten::t
INFO:Neuron:aten::mul
INFO:Neuron:aten::add
INFO:Neuron:The following operations are currently not supported in torch-neuron for this model:
INFO:Neuron:aten::embedding
INFO:Neuron:aten::gather
INFO:Neuron:aten::type_as
INFO:Neuron:99.76% of all operations (including primitives) (2516 of 2522) are supported
INFO:Neuron:99.45% of arithmetic operations (1084 of 1090) are supported
```

**Comment by awsrjh** [comment]
Angie - checking back to se if we can help?

**Comment by anjiefang** [comment]
Here is the BART model I was trying: https://huggingface.co/facebook/bart-base

> Are you looking to trace this model in order to later invoke generate ? We are working on enabling support for generative models like Pegasus with the roadmap item #225

Yea. Was trying to see if AWS neuron and inf1 can save latency when using BART.

**Comment by jeffhataws** [comment]
Hi Angie. We are working to enable compilation of generative models like BART in our upcoming release. We will keep you posted once we have instructions available. Thanks!

**Comment by aws-taylor** [comment]
Hello Angie,

 This is still under active debug. Will continue to update here as we make progress.

Regards,
Taylor

**Comment by aws-taylor** [comment]
Hello @anjiefang ,

  Please see the new PyTorch MarianMT tutorial in the documentation for help compiling generative models:
https://awsdocs-neuron.readthedocs-hosted.com/en/latest/neuron-guide/neuron-frameworks/pytorch-neuron/tutorials/transformers-marianmt.html

I'm going to resolve this issue, but please feel free to reach back to us if you have any further questions.

Regards,
Taylor

**Comment by phaterpekar** [comment]
How do these run with the Data Parallel Inference API ? Seems like these don't seem to be supported on torch >= 1.8 which is required for parallelization? Without that support only one core is being utilized at best. Also the performance is quite poor(similar to CPU) on max_encoder_ length/Max_decoder_lengths of 128 or 256  which is required for translating longer sentences.
