### ISSUE TITLE
Neuron Monitor Cloudwatch Bug

### ISSUE THREAD

**Issue by joelsimonoff** [aws/aws-neuron-sdk#247]
Hi! I'm having a bit of difficulty with getting Neuron Monitor to work with cloudwatch.

When attempting to run:

```
neuron-monitor | neuron-monitor-cloudwatch.py --namespace neuron_monitor_test --region us-east-1
```

I get the error:

```
(research) ubuntu@ip-172-31-2-226:~$ neuron-monitor | neuron-monitor-cloudwatch.py --namespace neuron_monitor_test --region us-east-1
Traceback (most recent call last):
  File "/opt/aws/neuron/bin/neuron-monitor-cloudwatch.py", line 217, in <module>
    main()
  File "/opt/aws/neuron/bin/neuron-monitor-cloudwatch.py", line 213, in main
    update_loop(args)
  File "/opt/aws/neuron/bin/neuron-monitor-cloudwatch.py", line 196, in update_loop
    metrics_to_send = process_data(monitor_data, args)
  File "/opt/aws/neuron/bin/neuron-monitor-cloudwatch.py", line 119, in process_data
    instance_info = monitor_data['instance_data']
KeyError: 'instance_data'
```

I then noticed that raw JSON from `neuron-monitor` has `instance_data` as `instance_info`. The obvious workaround here is just to use `sed` for finding and replacing `instance_info` with `instance_data`.

This command seems to work (it doesn't error):

```
neuron-monitor | sed -e 's/instance_info/instance_data/' | neuron-monitor-cloudwatch.py --namespace neuron_monitor_test --region us-east-1
```

I manually inspected stdout after the `sed` step and it seems that the json is correct and has values. However, on Cloudwatch the events appear empty:

<img width="350" alt="Screen Shot 2021-03-12 at 12 45 17 PM" src="https://user-images.githubusercontent.com/8621074/110996456-cfa07380-8330-11eb-91da-e028af6c479e.png">

<img width="367" alt="Screen Shot 2021-03-12 at 12 45 45 PM" src="https://user-images.githubusercontent.com/8621074/110996489-dfb85300-8330-11eb-8510-c4220395639c.png">

**Comment by awsrjh** [comment]
Joel - looking and will get back to you shortly.

**Comment by yonatanMedan** [comment]
Was this issue solved? experiencing similar issues

**Comment by sindhupalakodety** [comment]
For me, it is not showing any errors, but not sending anything to cloudwatch. Any ideas?
