### ISSUE TITLE
Broken link in EKS developer flow

### ISSUE THREAD

**Issue by aws-maens** [aws/aws-neuron-sdk#252]
in "Deploy DLC on Elastic Kubernetes Service (EKS)" https://awsdocs-neuron.readthedocs-hosted.com/en/latest/neuron-deploy/dlc-then-eks-devflow.html , in the Setup Environment section , Step 2 :  "Inf1 instance type" and "Amazon EKS optimized accelerated Amazon Linux AMI" has invalid links .

**Comment by micwade-aws** [comment]
Fixed - thanks.
