### ISSUE TITLE
Semantic Segmentation support

### ISSUE THREAD

**Issue by fgabel** [aws/aws-neuron-sdk#254]
Hi there, 

Are there plans to support semantic segmentation variants for AWS inferentia?

Thanks and have a good day,
Frank

**Comment by Ownmarc** [comment]
#153

**Comment by aws-zejdaj** [comment]
Thanks Mark for your help!  
Frank, just to be sure - are you looking for image segmentation like the RCNN (roadmap [#153](https://github.com/aws/aws-neuron-sdk/issues/153)), or already supported bounding box models - SSD (roadmap [#34](https://github.com/aws/aws-neuron-sdk/issues/34)), yolov4 ([#201](https://github.com/aws/aws-neuron-sdk/issues/201)).  Any other specific model?

**Comment by fgabel** [comment]
Thanks for your help, folks. 

I am looking for semantic segmentation models such as U-Net, not object instance segmentation :)

**Comment by aws-zejdaj** [comment]
Frank, thanks for the info. We have not tried U-net yet, please got ahead let us know f you run into any issues.

**Comment by mrnikwaws** [comment]
Hi Frank,

Following up - did you give U-Net a try?  Can you point us at the source code and indication the framework (Tensorflow, PyTorch or MXNet you are focusing on)?  I am assuming you are talking about https://arxiv.org/abs/1505.04597?  I see there are a few github repos that implement this in a framework in a supported framework.

To answer you question we want to accelerate any machine learning workload we can for our customers.  So assuming there isn't something about the model that doesn't work well with our kind of acceleration we'd would want to support it.  In general our assumption is that the compiler should be able to compile most models, unless we hear from our customers that there is a problem.  I'll plan to close this issue if I don't hear back from you.

**Comment by aws-taylor** [comment]
Hello Frank, 

 We haven't heard from you in a while, so I'm going to go ahead and close this issue. Feel free to re-open or cut us a new issue if none of the proposed approaches work for you.

Regards,
Taylor
