### ISSUE TITLE
neuron-cc installation issue on Inf1 instances

### ISSUE THREAD

**Issue by navyamehta** [aws/aws-neuron-sdk#255]
Hey! I seem to be running into issues where the neuron-cc[tensorflow] package does not install into a docker container being run on an Inf1 instance. The AMI being used is a Deep Learning AMI Ubuntu 18.04 with torch-neuron installed successfully and torch==1.7.1.

The dockerfile is as follows:
FROM nvcr.io/nvidia/tensorrt:20.12-py3 ..... initial testing with Inferentia, we will be switching out of this soon

WORKDIR /app/
EXPOSE 8000

RUN apt-get update && DEBIAN_FRONTEND="noninteractive" \
TZ="America/New_York" apt-get install -y tzdata

RUN apt-get install -y \
  ffmpeg gcc build-essential binutils gdb libcairo2-dev pkg-config \
  python3.8-dev freeglut3 freeglut3-dev libxi-dev libxmu-dev \
  libgirepository1.0-dev python3-pip \ 
  && rm -rf /var/lib/apt/lists/*

COPY requirements.txt ./

RUN pip3 install --upgrade keyrings.alt
RUN pip3 install --upgrade setuptools pip
RUN pip3 install --ignore-installed -r requirements.txt
RUN pip3 install --extra-index-url https://pip.repos.neuron.amazonaws.com/ neuron-cc torch-neuron
COPY . ./

The error is thrown in second-last line
---> Running in 2bc5c2283d6d
Looking in indexes: https://pypi.org/simple, https://pip.repos.neuron.amazonaws.com/
ERROR: Could not find a version that satisfies the requirement neuron-cc
ERROR: No matching distribution found for neuron-cc

Both "neuron-cc" and "neuron-cc[tensorflow]" were tried, but same error follows. Thanks!

**Comment by jeffhataws** [comment]
Hello Navya. Thank you for reporting the issue. It looks like the python version on http://nvcr.io/nvidia/tensorrt:20.12-py3 is 3.8. We will be releasing Python 3.8 compatible packages soon. In the meantime, please use python 3.6 or 3.7.

**Comment by paaksing** [comment]
@jeffhataws according to release docs, the latest 3 version is not supporting python 3.8 not even experimental, 3.7 EoL is in 9 months, is there still plan ? if so when ?

**Comment by mahirkukreja** [comment]
@jeffhataws Any updates on Python 3.8 support?

**Comment by HarryCaveMan** [comment]
So python 3.7 is not officially EOL and still no updates on this and no 3.8 support...

**Comment by HarryCaveMan** [comment]
Turns out there  is support, just ont in `pypi`......................... 
- https://pip.repos.neuron.amazonaws.com/neuronx-cc/
- https://pip.repos.neuron.amazonaws.com/neuron-cc/
