### ISSUE TITLE
Neuron gRPC service definition 

### ISSUE THREAD

**Issue by Jswig** [aws/aws-neuron-sdk#260]
Where can I find the service protocol buffer definition for interacting with the Neuron Runtime [gRPC interface](https://awsdocs-neuron.readthedocs-hosted.com/en/latest/neuron-guide/neuron-runtime/nrt-theory-of-operation.html#rt-grpc) ? 

This would be useful for interacting with Neuron through a C++ backend.

**Comment by awsrjh** [comment]
Hi Jswig

I think this is what you are looking for:

https://github.com/aws/aws-neuron-runtime-proto

**Comment by Jswig** [comment]
That's it, thank you!
