### ISSUE TITLE
Add Neuron SDK Container images in AWS China regions(Beijing & Ningxia)

### ISSUE THREAD

**Issue by walkley** [aws/aws-neuron-sdk#261]
[Inf1 instances are available in AWS China regions(Beijing & Ningxia)](https://www.amazonaws.cn/en/new/2021/amazon-ec2-inf1-instances-based-on-amazon-inferentia-now-available-beijing-sinnet-ningxia-nwcd/), could you please upload all the SDK images into the ECR in cn-north-1 and cn-northwest-1 regions?

**Comment by aws-taylor** [comment]
Hello @walkley,

  We are working to extend our support for ECR into these new regions. In the mean time, the best alternative is to pull images from another region, such is us-east-1/IAD. If you are using EKS, this can be accomplished by launching a cluster using the instructions described in https://awsdocs-neuron.readthedocs-hosted.com/en/latest/neuron-deploy/dlc-then-eks-devflow.html then running:
  
  ```kubectl create -f neuron_device_plugin.txt```

Regards,
Taylor
  
[neuron_device_plugin.txt](https://github.com/aws/aws-neuron-sdk/files/6379171/neuron_device_plugin.txt)

**Comment by micwade-aws** [comment]
@walkley - We have added public ECRs to our release process, which will soon be picked up by eksctl in a coming release: [https://github.com/weaveworks/eksctl/releases/tag/0.49.0-rc.0](https://github.com/weaveworks/eksctl/releases/tag/0.49.0-rc.0)

The new ECRs are [here](https://gallery.ecr.aws/?page=1&searchTerm=neuron).  We'll update documentation and make more of an announcement about this change once we know it's safely out the door and tested using latest eksctl.  If you'd like to get an early preview, I'd suggest testing out the pre-release from eksctl above.

**Comment by walkley** [comment]
I've validated the container images with [eksctl 0.49.0](https://github.com/weaveworks/eksctl/releases/tag/0.49.0).

Thank you!
