### ISSUE TITLE
Compile transformer model on local computer

### ISSUE THREAD

**Issue by Matthieu-Tinycoaching** [aws/aws-neuron-sdk#263]
Hello,

Is it possible to compile with the aws_neuron SDK a BERT transformer model on a local computer before deploying it on AWS Inf1?

Thanks!

**Comment by awsrjh** [comment]
in general - yes. It would need to be a version of supported Linux - like Ubuntu, and you would need to install the neuron-cc toolkits with the instructions here:

https://awsdocs-neuron.readthedocs-hosted.com/en/latest/neuron-intro/install-pytorch.html


you would of course, not install the runtime nor tools packages, so just do the pip installs:


```
python3 -m venv test_venv
source test_venv/bin/activate
pip install -U pip

tee $VIRTUAL_ENV/pip.conf > /dev/null <<EOF
[global]
extra-index-url = https://pip.repos.neuron.amazonaws.com
EOF
```

and then, for Pytorch: 

```
pip install neuron-cc[tensorflow]
pip install torch-neuron

```
or for Tensorflow:

```
pip install neuron-cc
pip install tensorflow-neuron
```

**Comment by Matthieu-Tinycoaching** [comment]
@awsrjh thanks for your feedback. Is it possible then to check the validity of the compiled model locally?

Second, if I would like to deploy a microservice on AWS Inf1, which python packages would be necessary within a docker image?

**Comment by micwade-aws** [comment]
> Is it possible then to check the validity of the compiled model locally?

No, verification is best done by examining the inference results on Inf1.
You might also find it useful to use our TensorBoard plugin, this walk-through might be of help: https://awsdocs-neuron.readthedocs-hosted.com/en/latest/neuron-guide/neuron-tools/getting-started-tensorboard-neuron-plugin.html

> Second, if I would like to deploy a microservice on AWS Inf1, which python packages would be necessary within a docker image?

You’ll need to account for the framework, the model server, Neuron runtime, and Neuron driver+base.  All of the above can be placed in the container except the driver and base (aws-neuron-dkms and aws-neuron-runtime-base).  The deep-learning-containers (DLC) for Neuron can be used as an example of how to build a container that supports both inference serving and compilation.  

* Example DLC inference server: https://github.com/aws/deep-learning-containers/blob/master/tensorflow/inference/docker/1.15/py3/Dockerfile.neuron
* Additional specifics on DLC combined with other services: https://awsdocs-neuron.readthedocs-hosted.com/en/latest/neuron-deploy/index.html

**Comment by micwade-aws** [comment]
Closing - please re-open if you need anything else on this topic.

**Comment by Matthieu-Tinycoaching** [comment]
Hi @micwade-aws I have a new question related to the deployment of custom deep learning service on Inf1 instances.

Where should I specify the NEURONCORE_GROUP_SIZES environment variable? Within the dockerfile or in the docker - run command directly?
