### ISSUE TITLE
Can Neuron SW be integrated with nvidia Triton Inference Server, and how?

### ISSUE THREAD

**Issue by zqliu19** [aws/aws-neuron-sdk#264]
Hi AWS experts,

Can Neuron SW be integrated with nvidia Triton Inference Server for model deployment?

https://github.com/triton-inference-server/server

Is there any Neuron SW (NeuronRT) API available to be exposed to Triton inference server for Triton-Neuron integration?

![image](https://user-images.githubusercontent.com/75308137/116961633-73c1ed80-acd6-11eb-9a5f-e0ac222c8891.png)

**Comment by micwade-aws** [comment]
@zqliu19 - 

Absolutely possible to integrate Neuron into almost any open source server/application! In the case of Triton, you'll need to create a backend based on one of the examples provided by Triton.  Suggest starting with this python backend example and modifying the three functions to meet your needs in any of the Neuron supported frameworks: https://github.com/triton-inference-server/python_backend.

**Comment by zqliu19** [comment]
@micwade-aws 
Do we have low level API of neuron SW available to enable tighter integration with triton with Neuron backend, instead of general python backend?
If we use python backend, how do we make sure Triton talks to NeuronRT (also an inference server) properly?

Thank you!

**Comment by micwade-aws** [comment]
The python backend can use a Neuron version of one of the supported ML frameworks, which would talk to the runtime on the instance.  

Help me understand the requirements of what you're attempting to build.  Is there a specific framework that you're expecting to use Triton with?  If you're open to it, I'd like to connect over email (aws-neuron-support@amazon.com) to dive deeper on this topic.

**Comment by aws-joshim** [comment]
Closing this ticket since Neuron SDK framework packages are expected to work with Triton Inference server. @zqliu19 , you can reach out to us for additional details on example code for Triton integration with Inferentia instances at aws-neuron-support@amazon.com
