### ISSUE TITLE
How to set environment variables on custom service container

### ISSUE THREAD

**Issue by Matthieu-Tinycoaching** [aws/aws-neuron-sdk#266]
Hello,

I have a question related to the deployment of custom deep learning service on Inf1 instances.

Where should I specify NEURONCORE_GROUP_SIZES, INIT_WORKERS and BATCH_SIZE environment variables? Within the dockerfile or in the docker - run command directly?

**Comment by awsrjh** [comment]
Hello Matthieu-Tinycoaching,

in general we set these environment variables on the call to docker run. 

as an example using the "-e" option:

`sudo docker run -it --name mxnet18 -p 80:8080 -p 8081:8081 --device=/dev/neuron0 --cap-add IPC_LOCK -e "NEURONCORE_GROUP_SIZES=1" mxnet18 /usr/local/bin/entrypoint.sh -m 'mxnet-resnet50=https://aws-dlc-sample-models.s3.amazonaws.com/mxnet/Resnet50-neuron.mar' -t /home/model-server/config.properties `

more example information can also be found here:

https://docs.aws.amazon.com/deep-learning-containers/latest/devguide/deep-learning-containers-ec2-tutorials-inference.html

**Comment by awsrjh** [comment]
Hi Mathieu

I will close this -- if you need any further help please do not hesitate to reopen or open a new issue.

many thanks.
