### ISSUE TITLE
Use neuron pipeline parallel data with torchserve

### ISSUE THREAD

**Issue by Matthieu-Tinycoaching** [aws/aws-neuron-sdk#268]
Hello,

I have used torchserve and NeuronCore data parallel following: https://awsdocs-neuron.readthedocs-hosted.com/en/latest/neuron-guide/neuron-frameworks/pytorch-neuron/tutorials/tutorial-torchserve.html

But how to configure torchserve for NeuronCore pipeline parallel (https://awsdocs-neuron.readthedocs-hosted.com/en/latest/neuron-guide/neuron-frameworks/pytorch-neuron/tutorials/neuroncore_pipeline_pytorch.html)?

Thanks!

**Comment by awsrjh** [comment]
I will check and get back to you as soon as possible. 

Thanks

**Comment by aws-stdun** [comment]
Hi @Matthieu-Tinycoaching,

You can configure TorchServe to use NeuronCore Pipeline. Let's suppose you have compiled your model using `--neuroncore-pipeline-cores=2`. Then you only need to adjust one line of code in [`handler_bert.py`](https://awsdocs-neuron.readthedocs-hosted.com/en/latest/neuron-guide/neuron-frameworks/pytorch-neuron/tutorials/tutorial-torchserve.html#id2):
```
os.environ['NEURONCORE_GROUP_SIZES'] = '2'  
```
Of course, "2" is just an example. You can replace this with whatever number of NeuronCores you select.

**Comment by Matthieu-Tinycoaching** [comment]
Hi @aws-stdun thanks! And so set `INITIAL_WORKERS` to 1?

**Comment by aws-stdun** [comment]
For `INITIAL_WORKERS`, it will depend on your instance size and the number of cores used. Each worker will be mapped to a model, so you'll need to do the math. Here is a concrete example:

Suppose you are using an inf1.6xlarge, which has 4 Inferentia chips (and therefore 4x4=16 NeuronCores).
Let's also supposed you compile your model using pipeline mode with 2 pipeline cores, as shown above (and therefore, each model will be split across 2 cores).

Then the number of workers you can use to saturate the hardware would be 16 / 2 = 8 workers.

**Comment by Matthieu-Tinycoaching** [comment]
Thanks!
