### ISSUE TITLE
How to configure neuronCore for bentoML serving

### ISSUE THREAD

**Issue by Matthieu-Tinycoaching** [aws/aws-neuron-sdk#273]
Hi,

I would like to test bentoML serving on Inf1 instances. Would anyone be aware of the procedure to follow in order to make it work?

Where and how to define the NeuronCore groups environment variable and the `INITIAL_WORKERS` as specified for torchserve?

Thanks!

**Comment by awsilya** [comment]
I will ask around.

**Comment by awsilya** [comment]
BentoML looks like it is intended to be for containerization so you will likely need to update your env decorator 
with the torch-neuron package and a neuron runtime startup script.
Packages can be specified in the env decorator:
https://docs.bentoml.org/en/latest/concepts.html#defining-service-environment


Bash scripts to install/start the neuron runtime need to be added as well:
https://docs.bentoml.org/en/latest/concepts.html#init-bash-script

For the reference - deep learning container for Neuron:
https://github.com/aws/deep-learning-containers/blob/master/pytorch/inference/docker/1.5.1/py3/Dockerfile.neuron

**Comment by Matthieu-Tinycoaching** [comment]
@awsilya thanks for the tips. Do you think I can reproduce the code used in https://github.com/aws/deep-learning-containers/blob/master/pytorch/inference/docker/1.5.1/py3/Dockerfile.neuron in the init-bash-script of bentoML in order to install and start the neuron runtime?

Thanks!

**Comment by awsilya** [comment]
Hi Matthieu, I don't see why not.  The only neuron specific bits are these installing the runtime the framework and neuron-cc.  You could extract them and move them to any other script.

**Comment by Matthieu-Tinycoaching** [comment]
Hi @awsilya I managed to build my docker image of bentoML service + neuron runtime.

However, I have a problem with the initialization of neuron-runtime within the container. Please see #290 for more informations.

Thanks for helping!
