### ISSUE TITLE
BERT-large compilation question (tensorflow)

### ISSUE THREAD

**Issue by zqliu19** [aws/aws-neuron-sdk#278]
Looks we have 2 methods to compile TF BERT, method-1 is using Neuron compatible BERT-Large implementation, and method-2 is using public BERT SavedModels.

For method-1, If we have a TF saved model with seqlen=128, is it OK to compile it to be a different seqlen (384) like below?
python bert_model.py --input_saved_model $BERT_LARGE_SAVED_MODEL --output_saved_model ./bert-saved-model-neuron --batch_size=6 --aggressive_optimizations **--sequence_length=384**
Here $BERT_LARGE_SAVED_MODEL has seqlen=128

For method-2, when we use public BERT SavedModel (with seqlen=128) 
Is it possible to compile the model to be seqlen=*384* with bert_no_model.py?
python bert_no_model.py --input_saved_model $BERT_LARGE_SAVED_MODEL --output_saved_model ./bert-saved-model-neuron --batch_size=1

**Comment by mrnikwaws** [comment]
Hi zqliu19,

We expect both methods should work with sequence length 384.  For method 1, please use batch 2.

Let us know if this works as expected and we'll close this ticket

**Comment by zqliu19** [comment]
Thanks a lot @mrnikwaws .
Could you help clarify why we need to use batch 2 for seqlen=384 (BERT-large)? 
We actually tried compiling the BERT-large model with seqlen=384 for batch 1 and batch 4 cases, and saw perf dropped significantly from BS1 to BS4, is that expected?

**Comment by aws-renfu** [comment]
Hi zqliu19,

Our earlier comment on using batch 2 for seqlen=384 was meant for benchmarking. To handle seqlen=384, it would be best to use a model that can support the correct sequence length natively.

Separately, regarding batch size and performance, we observe a positive increase in throughput as we increase batch size from 1 to 6 for seqlen=128. However, there is a non-linear impact to throughput as you increase batch size and sequence length. 

In the case for seqlen=384, as you increase batch sizes, it would improve weight reuse. However, larger batch size will also incur larger footprint for the on-chip memory. Hence we recommend our users to do their own benchmarking to find the sweet spot for their own use cases.

Thanks.
