### ISSUE TITLE
How to compile the MLperf inference version BERT-large?

### ISSUE THREAD

**Issue by zqliu19** [aws/aws-neuron-sdk#281]
The BERT tutorial for TensorFlow is using custom Neuron compatible BERT-Large implementation for the **MRPC** task, and if we want to use public BERT SavedModels, the seqlen is limited to be **128**.

The BERT tutorial for Pytorch is using HuggingFace Pretrained BERT, also for the MRPC task.

The BERT-large model in MLperf inference (link: https://github.com/mlcommons/inference/tree/master/language/bert) is using **seqlen=384** and is for the **SQuAD** task.

@aws-experts, how do we compile the MLperf inference version BERT-large on Inferentia **using the exact model source files from mlperf repo**?
The model source files can be found at the **model link** column of the table in  https://github.com/mlcommons/inference/tree/master/language/bert

Thank you!

**Comment by jeffhataws** [comment]
Hi zqliu19,
Thank you for your interest. We are not aware of any issues. Please try it and let us know if there's any issue.
