### ISSUE TITLE
BERT-like model: increasing initial workers in data parallel mode didn't improve throughput nor latency

### ISSUE THREAD

**Issue by Matthieu-Tinycoaching** [aws/aws-neuron-sdk#283]
Hello,

I tried to deploy a sentence-transformer bert-like model on Inf1.xlarge instance. I used bentoML as framework for containerizing inference service and when increasing the initial workers up to 4 that didn't improve the throughput nor the latency, as suggested by https://awsdocs-neuron.readthedocs-hosted.com/en/latest/neuron-guide/neuron-frameworks/pytorch-neuron/tutorials/tutorial-torchserve.html.

Please find the corresponding load testing reports for workers=1 (cf.` report_custom_MiniLM-L12-v2_bentoML128_250_spawn250_b1_worker1_inf1.xlarge.html`) and workers=4 (cf. `report_custom_MiniLM-L12-v2_bentoML128_250_spawn250_b1_worker4_inf1.xlarge.html`) in attached .zip file.

Thanks!

[report_custom_MiniLM-L12-v2_bentoML128_250_spawn250.zip](https://github.com/aws/aws-neuron-sdk/files/6663820/report_custom_MiniLM-L12-v2_bentoML128_250_spawn250.zip)

**Comment by jeffhataws** [comment]
Hi Matthieu,
While running the application, if you run neuron-top you should be able to see the utilization of the devices. If you see that only one NeuronCore is being used, please try setting the environment variable NEURONCORE_GROUP_SIZES=1,1,1,1 before running the application within your docker.

**Comment by Matthieu-Tinycoaching** [comment]
Hi @jeffhataws thanks for the advice. I already verified this and appropriately fixed this environment variable so that when initial workers are set to 4 all inferentia cores are used when looking at neuron-top. However, whatever the number of inferentia cores used that doesn't improve throughput nor latency compared to 1 worker, as suggested by load testing results I provided.

**Comment by micwade-aws** [comment]
@Matthieu-Tinycoaching - when the same model is loaded on multiple cores and verified with neuron-top, throughput may not improve if the model itself is not accelerated by Neuron or the inferences are being serialized somewhere between the client and Neuron.  You can check for the performance improvement of a single worker to confirm Neuron acceleration by comparing a Neuron compiled model to a non-compiled one.  You can also check for the serialization between client and server by scaling the non-compiled model workers. In this case, if you don’t see the expected improvement, the bottleneck is almost certainly outside the processing of inference by the model. Hope this narrows down the search space.  Reach out onaws-neuron-support@amazon.com if still blocked.
