### ISSUE TITLE
"Error class: BrokenProcessPool" when compiling Tensorflow Model using neuron-cc  

### ISSUE THREAD

**Issue by TheJaeLal** [aws/aws-neuron-sdk#287]
Hi team,

I'm trying to compile a Yolo like Tensorflow model to AWS Neuron on inf1.xlarge instance (DLAM v43), and getting the following error. 

**Error Log**:
06/18/2021 10:15:28 AM ERROR [neuron-cc]: ***************************************************************
06/18/2021 10:15:28 AM ERROR [neuron-cc]:  An Internal Compiler Error has occurred
06/18/2021 10:15:28 AM ERROR [neuron-cc]: ***************************************************************
06/18/2021 10:15:28 AM ERROR [neuron-cc]: 
06/18/2021 10:15:28 AM ERROR [neuron-cc]: Error message:  A process in the process pool was terminated abruptly while the future was running or pending.
06/18/2021 10:15:28 AM ERROR [neuron-cc]: 
06/18/2021 10:15:28 AM ERROR [neuron-cc]: Error class:    BrokenProcessPool
06/18/2021 10:15:28 AM ERROR [neuron-cc]: Error location: pipeline.compile.0
06/18/2021 10:15:28 AM ERROR [neuron-cc]: Command line:   /home/ubuntu/anaconda3/envs/aws_neuron_tensorflow_p36/bin/neuron-cc compile pb/semioptimized_frozen_model.pb --framework TENSORFLOW --io-config /home/ubuntu/cd_model.config --verbose debug
06/18/2021 10:15:28 AM ERROR [neuron-cc]: 
06/18/2021 10:15:28 AM ERROR [neuron-cc]: Internal details:
06/18/2021 10:15:28 AM ERROR [neuron-cc]:   File "neuroncc/driver/Job.py", line 244, in neuroncc.driver.Job.runSingleInputFn
06/18/2021 10:15:28 AM ERROR [neuron-cc]:   File "neuroncc/driver/Pipeline.py", line 30, in neuroncc.driver.Pipeline.Pipeline.runSingleInput
06/18/2021 10:15:28 AM ERROR [neuron-cc]:   File "neuroncc/driver/Job.py", line 286, in neuroncc.driver.Job.SingleInputJob.run
06/18/2021 10:15:28 AM ERROR [neuron-cc]:   File "neuroncc/driver/Job.py", line 291, in neuroncc.driver.Job.SingleInputJob.run
06/18/2021 10:15:28 AM ERROR [neuron-cc]:   File "/home/ubuntu/anaconda3/envs/aws_neuron_tensorflow_p36/lib/python3.6/concurrent/futures/_base.py", line 432, in result
06/18/2021 10:15:28 AM ERROR [neuron-cc]:     return self.__get_result()
06/18/2021 10:15:28 AM ERROR [neuron-cc]:   File "/home/ubuntu/anaconda3/envs/aws_neuron_tensorflow_p36/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
06/18/2021 10:15:28 AM ERROR [neuron-cc]:     raise self._exception
06/18/2021 10:15:28 AM ERROR [neuron-cc]: 
06/18/2021 10:15:28 AM ERROR [neuron-cc]: Version information:
06/18/2021 10:15:28 AM ERROR [neuron-cc]:   Neuron Compiler version 1.4.1.0+737cbb69a
06/18/2021 10:15:28 AM ERROR [neuron-cc]:   
06/18/2021 10:15:28 AM ERROR [neuron-cc]:   HWM version 1.4.1.0-0
06/18/2021 10:15:28 AM ERROR [neuron-cc]:   NEFF version 1.0
06/18/2021 10:15:28 AM ERROR [neuron-cc]:   TVM version 1.4.1.0+0
06/18/2021 10:15:28 AM ERROR [neuron-cc]:   NumPy version 1.18.4
06/18/2021 10:15:28 AM ERROR [neuron-cc]:   MXNet not available
06/18/2021 10:15:28 AM ERROR [neuron-cc]:   TF not available
06/18/2021 10:15:28 AM ERROR [neuron-cc]:   ONNX not available

My Compile-Environment details are as follows:

**AWS Instance (for compiling)**: inf1.xlarge
**AMI**: Deep Learning AMI (Ubuntu 18.04) Version 43.0
**Neuron-Compiler version**: 1.4.1.0
**Conda env**: aws_neuron_tensorflow_p36
**tensorflow version**: 1.15.5
**tensorflow-neuron version**: 1.15.5.1.4.0.0
**Compile Method**: Neuron CLI
**Command**: neuron-cc compile <model_file.pb> --framework TENSORFLOW --io-config <model_io.config>
**Model Tensorflow Ops:**
['BiasAdd',
 'Const',
 'Conv2D',
 'FusedBatchNorm',
 'LeakyRelu',
 'MatMul',
 'MaxPool',
 'Pack',
 'Placeholder',
 'Reshape',
 'Shape',
 'StridedSlice']

All of these are supported by Neuron Compile as mentioned [here](https://awsdocs-neuron.readthedocs-hosted.com/en/latest/release-notes/neuron-cc-ops/neuron-cc-ops-tensorflow.html)

Please let me know if I'm missing something.

Thanks,
Jay

**Comment by jeffhataws** [comment]
Hi Jay,

The error message "A process in the process pool was terminated abruptly while the future was running or pending." usually means out-of-memory during compilation. Could you try a larger instance size (say inf1.6xlarge)?

Thanks.

**Comment by TheJaeLal** [comment]
Thanks Jeff, increasing RAM resolved the issue
