### ISSUE TITLE
torch.neuron.trace - ValueError: None values not supported.

### ISSUE THREAD

**Issue by Kenterbery** [aws/aws-neuron-sdk#288]
Hi there,

Have some troubles tracing own architecture:

> try:
>     model_neuron_tentative = torch.neuron.trace(mode, ex_input)
> except Exception as e:
>     print(e)

output:

> INFO:Neuron:All operators are compiled by neuron-cc (this does not guarantee that neuron-cc will successfully compile)
> INFO:Neuron:Number of arithmetic operators (pre-compilation) before = 139, fused = 139, percent fused = 100.0%
> INFO:Neuron:PyTorch to TF conversion failed to resolve function on aten::batch_norm with inputs [<tf.Tensor 'transpose_2:0' shape=(1, 64, 224, 224) dtype=float32>, None, None, <tf.Tensor 'Const_2:0' shape=(64,) dtype=float32>, <tf.Tensor 'Const_3:0' shape=(64,) dtype=float32>, False, 0.1, 1e-05, True]
> INFO:Neuron:Exception = None values not supported.
> WARNING:Neuron:torch.neuron.trace failed on _NeuronGraph$1227; falling back to native python function call
> ERROR:Neuron:None values not supported.
> Traceback (most recent call last):
>   File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch_neuron/convert.py", line 330, in op_converter
>     dynamic_batch_size=self.dynamic_batch_size, **kwargs)
>   File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch_neuron/decorators.py", line 79, in trace
>     transform_torch_graph_to_tensorflow(jit_trace, example_inputs)
>   File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch_neuron/decorators.py", line 487, in transform_torch_graph_to_tensorflow
>     raise e
>   File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch_neuron/decorators.py", line 481, in transform_torch_graph_to_tensorflow
>     tensor_outputs = local_func(op, *tensor_inputs)
>   File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch_neuron/ops/aten.py", line 600, in batch_norm
>     tensor = (tensor - running_mean) / denominator * weight + bias
>   File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/tensorflow_core/python/ops/math_ops.py", line 903, in binary_op_wrapper
>     y, dtype_hint=x.dtype.base_dtype, name="y")
>   File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 1242, in convert_to_tensor_v2
>     as_ref=False)
>   File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 1297, in internal_convert_to_tensor
>     ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
>   File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/tensorflow_core/python/framework/constant_op.py", line 286, in _constant_tensor_conversion_function
>     return constant(v, dtype=dtype, name=name)
>   File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/tensorflow_core/python/framework/constant_op.py", line 227, in constant
>     allow_broadcast=True)
>   File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/tensorflow_core/python/framework/constant_op.py", line 265, in _constant_impl
>     allow_broadcast=allow_broadcast))
>   File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/tensorflow_core/python/framework/tensor_util.py", line 437, in make_tensor_proto
>     raise ValueError("None values not supported.")
> ValueError: None values not supported.
> INFO:Neuron:Number of arithmetic operators (post-compilation) before = 139, compiled = 0, percent compiled = 0.0%
> INFO:Neuron:The neuron partitioner created 1 sub-graphs
> INFO:Neuron:Neuron successfully compiled 0 sub-graphs, Total fused subgraphs = 1, Percent of model sub-graphs successfully compiled = 0.0%

pytorch 1.8.1+cu102
tensorflow 1.15.0
neuron-cc 1.4.1.0+737cbb69a
torch-neuron 1.8.1.1.4.1.0

As I understand, there are some None nodes when graph converts to TF which `aten::batch_norm` cannot process . Does anyone know how to fix it?
Thanks!

**Comment by jeffhataws** [comment]
Hi Dmytro, 
Thank you for reporting this error. We have identified the problem and are working on a fix. To help us identify a workaround and verify the fix, it would help if share your model with us via aws-neuron-support@amazon.com.

**Comment by Kenterbery** [comment]
Hi @jeffhataws,
Unfortunately, I can not share the model due to confidentiality norms. If there is any other way to help you fix it, please let me know.

**Comment by Kenterbery** [comment]
@jeffhataws seems like a problem is in PyTorch nn.BatchNorm2d param `affine = False` which sets the weight and bias to None and then we have an error as above. In other cases everything works fine. 
Hopefully this information will help to avoid the bug.

**Comment by mrnikwaws** [comment]
Hi Dmytro,

Yes! You nailed it.

The bug prevents the batch_norm being used where there are no weights or biases passed to the operator (e.g. BatchNorm2d with args affine=False).  I have made the fix in our code base, but it will take time to run through our integration suites and get to you in a future release.  

In the interim you could use an affine transform (set the weights as identity and bias to zero), if you want to make this work in the interim.

You can alternatively override the operator whitelist argument to temporarily remove the batch_norm operator from the compilation:
```
allowed_ops = set(torch.neuron.get_supported_operations())
allowed_ops.remove("aten::batch_norm")
model_neuron = torch.neuron.trace( model, example_inputs, op_whitelist=allowed_ops )
```
The first work-around will give you a better performance for now, the second solution runs the operator on CPU which means more data transfers to and from the neuron hardware.

**Comment by Kenterbery** [comment]
OK, got it. Using the first option with setting weights as identity and bias to zero with arg `affine=True` helped me to avoid the problem with tracing. 
Thank you!
