### ISSUE TITLE
Internal Compiler Error: inf1.2xlarge with neuroncore_pipeline_cores=1 and batch_size=1

### ISSUE THREAD

**Issue by Kenterbery** [aws/aws-neuron-sdk#291]
Hi, team,

I tried to compile my encoder-like model with following: 

> model_neuron = torch.neuron.trace( encoder, 
>                                     ex_input_encoder,
>                                     compiler_workdir='/tmp/cc-logs/temp')

But got the following error: 

> INFO:Neuron:All operators are compiled by neuron-cc (this does not guarantee that neuron-cc will successfully compile)
> INFO:Neuron:Number of arithmetic operators (pre-compilation) before = 139, fused = 139, percent fused = 100.0%
> INFO:Neuron:Compiling function _NeuronGraph$669 with neuron-cc; log file is at /tmp/cc-logs/temp/0/graph_def.neuron-cc.log
> INFO:Neuron:Compiling with command line: '/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/bin/neuron-cc compile /tmp/cc-logs/temp/0/graph_def.pb --framework TENSORFLOW --pipeline compile SaveTemps --output /tmp/cc-logs/temp/0/graph_def.neff --io-config {"inputs": {"0:0": [[1, 1, 224, 224], "float32"], "1:0": [[1, 3, 224, 224], "float32"]}, "outputs": ["clip_by_value:0"]} --verbose 35'
> INFO:Neuron:Compile command returned: 1
> WARNING:Neuron:torch.neuron.trace failed on _NeuronGraph$669; falling back to native python function call
> ERROR:Neuron:neuron-cc failed with the following command line call:
> /home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/bin/neuron-cc compile /tmp/cc-logs/temp/0/graph_def.pb --framework TENSORFLOW --pipeline compile SaveTemps --output /tmp/cc-logs/temp/0/graph_def.neff --io-config '{"inputs": {"0:0": [[1, 1, 224, 224], "float32"], "1:0": [[1, 3, 224, 224], "float32"]}, "outputs": ["clip_by_value:0"]}' --verbose 35
> Traceback (most recent call last):
>   File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch_neuron/convert.py", line 330, in op_converter
>     dynamic_batch_size=self.dynamic_batch_size, **kwargs)
>   File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch_neuron/decorators.py", line 191, in trace
>     'neuron-cc failed with the following command line call:\n{}'.format(command))
> subprocess.SubprocessError: neuron-cc failed with the following command line call:
> /home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/bin/neuron-cc compile /tmp/cc-logs/temp/0/graph_def.pb --framework TENSORFLOW --pipeline compile SaveTemps --output /tmp/cc-logs/temp/0/graph_def.neff --io-config '{"inputs": {"0:0": [[1, 1, 224, 224], "float32"], "1:0": [[1, 3, 224, 224], "float32"]}, "outputs": ["clip_by_value:0"]}' --verbose 35
> INFO:Neuron:Number of arithmetic operators (post-compilation) before = 139, compiled = 0, percent compiled = 0.0%
> INFO:Neuron:The neuron partitioner created 1 sub-graphs
> INFO:Neuron:Neuron successfully compiled 0 sub-graphs, Total fused subgraphs = 1, Percent of model sub-graphs successfully compiled = 0.0%
> INFO:Neuron:Compiled these operators (and operator counts) to Neuron:
> INFO:Neuron:Not compiled operators (and operator counts) to Neuron:
> INFO:Neuron: => aten::_convolution: 43 [supported]
> INFO:Neuron: => aten::batch_norm: 42 [supported]
> INFO:Neuron: => aten:: cat: 8 [supported]
> INFO:Neuron: => aten:: clamp: 1 [supported]
> INFO:Neuron: => aten:: leaky_relu: 42 [supported]
> INFO:Neuron: => aten::max_pool2d: 3 [supported]

And here what I find in `log-neuron-cc.txt`:

> 06/23/2021 03:30:30 PM ERROR [neuron-cc]: ***************************************************************
> 06/23/2021 03:30:30 PM ERROR [neuron-cc]:  An Internal Compiler Error has occurred
> 06/23/2021 03:30:30 PM ERROR [neuron-cc]: ***************************************************************
> 06/23/2021 03:30:30 PM ERROR [neuron-cc]: 
> 06/23/2021 03:30:30 PM ERROR [neuron-cc]: Error message:  Non-zero exit status (134) for command: /home/ubuntu/anaconda3/envs/aws_neuro
> n_pytorch_p36/lib/python3.6/site-packages/neuroncc/starfish/bin/walrus_driver --optlevel=2 --verbose=40 -o walrus_bir.out.json -i bir.j
> son  --allocator=coloring --min_split_size=10240 --max-partitions=1 --policy=2 --latency=6  --internal-hyper-parameters=/opt/ml/input/c
> onfig/hyperparameters.json --tuning=2 --numcores=1
> 06/23/2021 03:30:30 PM ERROR [neuron-cc]: 
> 06/23/2021 03:30:30 PM ERROR [neuron-cc]: Error class:    CompilerInternalError
> 06/23/2021 03:30:30 PM ERROR [neuron-cc]: Error location: job.WalrusDriver.3
> 06/23/2021 03:30:30 PM ERROR [neuron-cc]: Command line:   /home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/bin/neuron-cc compile /tmp
> /cc-logs/temp/0/graph_def.pb --framework TENSORFLOW --pipeline compile SaveTemps --output /tmp/cc-logs/temp/0/graph_def.neff --io-confi
> g '{"inputs": {"0:0": [[1, 1, 224, 224], "float32"], "1:0": [[1, 3, 224, 224], "float32"]}, "outputs": ["clip_by_value:0"]}' --verbose 
> 35
> 06/23/2021 03:30:30 PM ERROR [neuron-cc]: 
> 06/23/2021 03:30:30 PM ERROR [neuron-cc]: Internal details:
> 06/23/2021 03:30:30 PM ERROR [neuron-cc]:   File "neuroncc/driver/Job.py", line 244, in neuroncc.driver.Job.runSingleInputFn
> 06/23/2021 03:30:30 PM ERROR [neuron-cc]:   File "neuroncc/driver/jobs/WalrusDriver.py", line 228, in neuroncc.driver.jobs.WalrusDriver
> .WalrusDriver.runSingleInput
> 06/23/2021 03:30:30 PM ERROR [neuron-cc]:   File "neuroncc/driver/Job.py", line 178, in neuroncc.driver.Job.Job.shellCommand
> 06/23/2021 03:30:30 PM ERROR [neuron-cc]: 
> 06/23/2021 03:30:30 PM ERROR [neuron-cc]: Version information:
> 06/23/2021 03:30:30 PM ERROR [neuron-cc]:   Neuron Compiler version 1.4.1.0+737cbb69a
> 06/23/2021 03:30:30 PM ERROR [neuron-cc]:   
> 06/23/2021 03:30:30 PM ERROR [neuron-cc]:   HWM version 1.4.1.0-0
> 06/23/2021 03:30:30 PM ERROR [neuron-cc]:   NEFF version 1.0
> 06/23/2021 03:30:30 PM ERROR [neuron-cc]:   TVM version 1.4.1.0+0
> 06/23/2021 03:30:30 PM ERROR [neuron-cc]:   NumPy version 1.18.4
> 06/23/2021 03:30:30 PM ERROR [neuron-cc]:   MXNet not available
> 06/23/2021 03:30:30 PM ERROR [neuron-cc]:   TF not available
> 06/23/2021 03:30:30 PM ERROR [neuron-cc]:   ONNX not available
   
torch                         1.8.1+cu102
torch-neuron              1.8.1.1.4.1.0          

I shared you an artifacts dir at aws-neuron-support@amazon.com for further debugging.

Thanks!

**Comment by mrnikwaws** [comment]
Thanks Dmytro - received your artifacts.

**Comment by aws-taylor** [comment]
Hello @Kenterbery,

I was able to reproduce your issue. We're still working on a fix, but the good news is you can work around this issue by using more Neuron cores. For this particular example, I was able to compile using `--neuroncore-pipeline-cores 7`. 

Please let us know if you have any further issues or questions.

Regards,
Taylor

**Comment by awsrjh** [comment]
Hello @Kenterbery,

has this helped you resolve this?

**Comment by awsrjh** [comment]
please let us know if we can help more - feel free to reopen as needed.
