### ISSUE TITLE
wav2vec2 trace error (aten::_weight_norm, aten::index_put, aten::bitwise_not, aten::cumsum)

### ISSUE THREAD

**Issue by bobzsj87** [aws/aws-neuron-sdk#293]
When compiling the wav2vec2 model from hugging Face, the error shows
```
INFO:Neuron:There are 5 ops of 4 different types in the TorchScript that are not compiled by neuron-cc: aten::_weight_norm, aten::index_put, aten::bitwise_not, aten::cumsum, (For more information see https://github.com/aws/aws-neuron-sdk/blob/master/release-notes/neuron-cc-ops/neuron-cc-ops-pytorch.md)
INFO:Neuron:Number of arithmetic operators (pre-compilation) before = 1890, fused = 1782, percent fused = 94.29%
```

Any recent plan for supportin those ops?

**Comment by aws-renfu** [comment]
Hi bobzsj87,

We will raise the issue of supporting these two operators to the product planning group and get back to you. 

Thanks.

**Comment by awsrjh** [comment]
please track this on the roadmap 

https://github.com/aws/aws-neuron-sdk/projects/2

https://github.com/aws/aws-neuron-sdk/issues/306
