### ISSUE TITLE
Compiling Neuron in SageMaker Notebook

### ISSUE THREAD

**Issue by minhtcai** [aws/aws-neuron-sdk#294]
Hi, is that possible to compile neuron model from SM Notebook?

Couldn't find the environment aws_neuron_pytorch_p36 in any notebook.
I've tried to export env from inf1 instance but can't replicate the tutorial.
I can't use Neo since I train my model is in darknet -> pytorch -> neuron model

**Comment by aws-renfu** [comment]
Hi minhtcai,

We are following up with the SageMaker team to help solve the yolov4 compilation issue via Neo. We will get back to you shortly.

Thanks.

**Comment by aws-taylor** [comment]
Hello @minhtcai,

At this time, SageMaker notebooks do not support inf1 instances. You can however host your own Jupyter notebook on an inf1 instance. Please see https://awsdocs-neuron.readthedocs-hosted.com/en/latest/neuron-intro/neuron-install-guide.html#jupyter-notebook for details on configuring such an instance.

Please do not hesitate to reach out to us if you have any further questions.

Regards,
Taylor
