### ISSUE TITLE
Is dynamic batching supported on Pytorch?

### ISSUE THREAD

**Issue by zqliu19** [aws/aws-neuron-sdk#295]
Seems dynamic batching can be used only in Tensorflow to process a larger client-side inference batch-size?

**Comment by aws-renfu** [comment]
Hi zqliu19,

The dynamic batching feature in PyTorch will be included in the coming release. We will update you soon.

Thanks.

**Comment by AWSGH** [comment]
Neuron 1.14.1 added dynamic batching support for PT: 
`dynamic_batch_size (bool)` – A flag to allow Neuron graphs to consume variable sized batches of data. Dynamic sizing is restricted to the 0th dimension of a tensor.

https://awsdocs-neuron.readthedocs-hosted.com/en/latest/neuron-guide/neuron-frameworks/pytorch-neuron/api-compilation-python-api.html`

Closing the issue, feel free to reopen is any followup needed.
