### ISSUE TITLE
Failed to enable data parallel for BERT-large Pytorch (NEURONCORE_GROUP_SIZES=1,1,1,1)

### ISSUE THREAD

**Issue by zqliu19** [aws/aws-neuron-sdk#299]
We used the code below to enable data parallel for our model (BERT-large) using Pytorch, however, when we run the model, we noticed that perf is much worse compared to Tensorflow, and when we use neuron-top to check neuron core utilization we saw that only 1 core was being used.
We expect it to work to utilize all 4 cores, but it didn't. @aws-experts, could you advise how to fix this? THX!

nc_env = ','.join(['1'] * num_neuron_cores)
os.environ['NEURONCORE_GROUP_SIZES'] = nc_env

NUM_THREADS_PER_PREDICTOR = int(num_threads / avail_neuroncores)
model_neuron = torch.jit.load(COMPILED_MODEL)
pred_list = [model_neuron for _ in range(avail_neuroncores)]
pred_list = pred_list * NUM_THREADS_PER_PREDICTOR
executor = futures.ThreadPoolExecutor(max_workers = num_threads)
running = {executor.submit(one_thread,pred_list[idx],example_inputs[idx]): idx for idx in range(num_threads)}

We are using DLAMI and latest torch.neuron.
(aws_neuron_pytorch_p36) ubuntu@ip-172-31-2-230:~/aws-neuron-sdk/src/examples/pytorch/bert_tutorial$ sudo systemctl restart neuron-rtd
(aws_neuron_pytorch_p36) ubuntu@ip-172-31-2-230:~/aws-neuron-sdk/src/examples/pytorch/bert_tutorial$ export NEURONCORE_GROUP_SIZES=1,1,1,1
(aws_neuron_pytorch_p36) ubuntu@ip-172-31-2-230:~/aws-neuron-sdk/src/examples/pytorch/bert_tutorial$ echo $NEURONCORE_GROUP_SIZES
1,1,1,1

Models: 1 loaded, 1 running. NeuronCores: 1 used.
0000:00:1f.0 Utilizations: NC0 97.07%, NC1 0.00%, NC2 0.00%, NC3 0.00%,
Model ID   Device    NeuronCore%   Device Mem   Host Mem   Model Name
10001      nd0:nc0   97.07          594 MB         3 MB    1.2.7.0+eaf2e01fb-/tmp/tmpukb0_1fa

For current thread,start time is 1625213710.584766 end time is 1625213710.633593
For current thread,start time is 1625213710.5848756 end time is 1625213710.6803863
For current thread,start time is 1625213710.5848112 end time is 1625213710.7272043
For current thread,start time is 1625213710.5848424 end time is 1625213710.7739542

4 threads here are submitted at ~ same time, but they are running serially on 1 single core, not concurrently on 4 cores

**Comment by aws-renfu** [comment]
Hi zqliu19,

If you take look at https://github.com/aws/aws-neuron-sdk/blob/master/src/examples/pytorch/bert_tutorial/tutorial_pretrained_bert.ipynb and in particular https://github.com/aws/aws-neuron-sdk/blob/master/src/examples/pytorch/bert_tutorial/parallel.py#L41 you'll see that the approach in PyTorch is a little different to tensorflow.  The model needs to be loaded into each core.
If you want to use the provided class as used in the BERT tutorial I'd expect it to work well for your use case.

Thanks!
