### ISSUE TITLE
neuron_runtime error on inf1.6xlarge, BERT-large (seqlen=384), pytorch

### ISSUE THREAD

**Issue by zqliu19** [aws/aws-neuron-sdk#302]
We can run BERT-large pytorch model on inf1.2xlarge successfully with --num_threads=4 --num_cores=4
But when we tried to run on inf1.6xlarge with --num_threads=16 --num_cores=16, we got the run time error.
Detailed log below. 
@aws experts, could you help advise how to fix?

(aws_neuron_pytorch_p36) ubuntu@ip-172-31-46-132:~/aws-neuron-sdk/src/examples/pytorch/bert_tutorial$ systemctl is-active neuron-rtd
active
(aws_neuron_pytorch_p36) ubuntu@ip-172-31-46-132:~/aws-neuron-sdk/src/examples/pytorch/bert_tutorial$ python bert-large-pytorch-mlperf-run-bm-bs1-fix-dynamic-accuracy.py --user_batch=1 --num_threads=16 --num_cores=16
Constructing QSL...
Loading cached features from 'eval_features.pickle'...
Finished constructing QSL.
[E neuron_runtime.cpp:333] NeuronDevice::process_nrtd_response: Context=NRTD_CTX_LOAD NRTD response code 'NERR_RESOURCE' (4) The runtime was unable to allocate a resource for the requested operation. Raw runtime error message '[NEFF:neff_get_file_content] file not found cpu.so in NEFF
[TDRV:dmem_alloc] Failed to alloc DEVICE memory: 4194304
[TDRV:copy_and_stage_mr_one_channel] Failed to allocate aligned (0) buffer in MLA DRAM for W145-b of size 4194304 bytes, channel 0
[TDRV:kbl_model_add] copy_and_stage_mr() error
[NMGR:dlr_kelf_stage] Failed to load subgraph
[NMGR:stage_kelf_models] Failed to stage graph: kelf-a.json to NeuronCore
[NMGR:kmgr_load_nn] Failed to load NN: 1.5.5.0+3cc38c60b-/tmp/tmp___j1kwn, err: 4
[NRTD:load] DLR model load failed
'
Traceback (most recent call last):
  File "bert-large-pytorch-mlperf-run-bm-bs1-fix-dynamic-accuracy.py", line 124, in <module>
    model_neuron = NeuronSimpleDataParallel(COMPILED_MODEL,avail_neuroncores,num_threads,batch_per_thread)
  File "bert-large-pytorch-mlperf-run-bm-bs1-fix-dynamic-accuracy.py", line 77, in __init__
    self.models = [SimpleWrapper(torch.jit.load(model_file)) for i in range(self.num_threads)]
  File "bert-large-pytorch-mlperf-run-bm-bs1-fix-dynamic-accuracy.py", line 77, in <listcomp>
    self.models = [SimpleWrapper(torch.jit.load(model_file)) for i in range(self.num_threads)]
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch_neuron/jit_load_wrapper.py", line 13, in wrapper
    script_module = jit_load(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch/jit/_serialization.py", line 161, in load
    cpp_module = torch._C.import_ir_module(cu, str(f), map_location, _extra_files)
RuntimeError: NeuronDevice::process_nrtd_response: Context=NRTD_CTX_LOAD NRTD response code 'NERR_RESOURCE' (4) The runtime was unable to allocate a resource for the requested operation. Raw runtime error message '[NEFF:neff_get_file_content] file not found cpu.so in NEFF
[TDRV:dmem_alloc] Failed to alloc DEVICE memory: 4194304
[TDRV:copy_and_stage_mr_one_channel] Failed to allocate aligned (0) buffer in MLA DRAM for W145-b of size 4194304 bytes, channel 0
[TDRV:kbl_model_add] copy_and_stage_mr() error
[NMGR:dlr_kelf_stage] Failed to load subgraph
[NMGR:stage_kelf_models] Failed to stage graph: kelf-a.json to NeuronCore
[NMGR:kmgr_load_nn] Failed to load NN: 1.5.5.0+3cc38c60b-/tmp/tmp___j1kwn, err: 4
[NRTD:load] DLR model load failed

**Comment by micwade-aws** [comment]
Thanks for reporting the issue - will take a closer look today.  Do you mind providing additional details regarding the version of Neuron software in use?  I'm interested in knowing which version of DLAMI (guessing) that you're using, the output of: `apt list | grep neuron`, and the output of `pip list`.

**Comment by zqliu19** [comment]
> Thanks for reporting the issue - will take a closer look today. Do you mind providing additional details regarding the version of Neuron software in use? I'm interested in knowing which version of DLAMI (guessing) that you're using, the output of: `apt list | grep neuron`, and the output of `pip list`.

Thanks a lot!

(aws_neuron_pytorch_p36) ubuntu@ip-172-31-46-132:~/aws-neuron-sdk/src/examples/tensorflow/bert_demo$ apt list | grep neuron

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

aws-neuron-dkms/unknown,now 1.5.0.0 amd64 [installed]
aws-neuron-k8-plugin/unknown 1.6.0.0 amd64
aws-neuron-k8-scheduler/unknown 1.6.0.0 amd64
aws-neuron-runtime/unknown 1.6.5.0 amd64 [upgradable from: 1.5.0.0]
aws-neuron-runtime-base/unknown 1.6.1.0 amd64 [upgradable from: 1.5.1.0]
aws-neuron-tools/unknown 1.7.4.0 amd64 [upgradable from: 1.6.1.0]
neuron/bionic 7.5-1 amd64
neuron-dev/bionic 7.5-1 amd64
python3-neuron/bionic 7.5-1 amd64
tensorflow-model-server-neuron/unknown 1.15.0.1.5.1.0 all [upgradable from: 1.15.0.1.2.9.0]
(aws_neuron_pytorch_p36) ubuntu@ip-172-31-46-132:~/aws-neuron-sdk/src/examples/tensorflow/bert_demo$ pip list
Package                            Version
---------------------------------- ---------------------------
absl-py                            0.13.0
alabaster                          0.7.12
anyio                              3.2.1
appdirs                            1.4.4
argh                               0.26.2
argon2-cffi                        20.1.0
arrow                              1.1.1
asn1crypto                         1.4.0
astor                              0.8.1
astroid                            2.5.3
astropy                            4.1
async-generator                    1.10
atomicwrites                       1.4.0
attrs                              20.3.0
autopep8                           1.5.6
autovizwidget                      0.18.0
Babel                              2.9.0
backcall                           0.2.0
backports.functools-lru-cache      1.6.4
backports.shutil-get-terminal-size 1.0.0
beautifulsoup4                     4.9.3
binaryornot                        0.4.4
bitarray                           2.0.1
bkcharts                           0.2
black                              21.5b2
bleach                             3.3.0
bokeh                              2.3.1
boto                               2.49.0
boto3                              1.17.56
botocore                           1.20.56
Bottleneck                         1.3.2
brotlipy                           0.7.0
cached-property                    1.5.2
certifi                            2021.5.30
cffi                               1.14.5
chardet                            4.0.0
click                              7.1.2
cloudpickle                        1.6.0
clyent                             1.2.2
colorama                           0.4.4
contextlib2                        0.6.0.post1
contextvars                        2.4
cookiecutter                       1.7.3
cryptography                       3.4.7
cycler                             0.10.0
Cython                             0.29.23
cytoolz                            0.11.0
dask                               2021.3.0
dataclasses                        0.8
decorator                          5.0.7
defusedxml                         0.7.1
deprecation                        2.1.0
diff-match-patch                   20200713
dill                               0.3.3
distributed                        2021.3.0
dmlc-nnvm                          1.5.1.0+0
dmlc-topi                          1.5.1.0+0
dmlc-tvm                           1.5.1.0+0
docutils                           0.17.1
entrypoints                        0.3
environment-kernels                1.1.1
et-xmlfile                         1.0.1
fastcache                          1.1.0
filelock                           3.0.12
flake8                             3.8.4
Flask                              1.1.2
Flask-Cors                         3.0.10
fsspec                             2021.4.0
future                             0.18.2
gast                               0.2.2
gevent                             21.1.2
glob2                              0.7
gmpy2                              2.1.0b1
google-pasta                       0.2.0
graphviz                           0.16
greenlet                           1.0.0
grpcio                             1.38.1
h5py                               3.1.0
hdijupyterutils                    0.18.0
HeapDict                           1.0.1
html5lib                           1.1
huggingface-hub                    0.0.8
idna                               2.10
imagecodecs-lite                   2019.12.3
imageio                            2.9.0
imagesize                          1.2.0
immutables                         0.15
importlib-metadata                 4.0.1
inferentia-hwm                     1.5.1.0+0
inflection                         0.5.1
iniconfig                          1.1.1
intel-tensorflow                   1.15.0
intervaltree                       3.0.2
ipykernel                          5.5.3
ipyparallel                        6.3.0
ipython                            7.16.1
ipython-genutils                   0.2.0
ipywidgets                         7.6.3
islpy                              2018.2+aws2018.x.748.0.bld0
isort                              5.8.0
itsdangerous                       1.1.0
jdcal                              1.4.1
jedi                               0.17.2
jeepney                            0.6.0
Jinja2                             2.11.3
jinja2-time                        0.2.0
jmespath                           0.10.0
joblib                             1.0.1
json5                              0.9.5
jsonschema                         3.2.0
jupyter                            1.0.0
jupyter-client                     6.1.12
jupyter-console                    6.4.0
jupyter-core                       4.7.1
jupyter-packaging                  0.10.3
jupyter-server                     1.9.0
jupyterlab                         3.0.14
jupyterlab-pygments                0.1.2
jupyterlab-server                  2.4.0
jupyterlab-widgets                 1.0.0
Keras-Applications                 1.0.8
Keras-Preprocessing                1.1.2
keyring                            23.0.1
kiwisolver                         1.3.1
lazy-object-proxy                  1.6.0
libarchive-c                       2.9
llvmlite                           0.36.0
locket                             0.2.0
lxml                               4.6.3
Markdown                           3.3.4
MarkupSafe                         1.1.1
matplotlib                         3.3.4
mccabe                             0.6.1
mistune                            0.8.4
mkl-fft                            1.3.0
mkl-random                         1.2.0
mkl-service                        2.3.0
mock                               4.0.3
more-itertools                     8.7.0
mpmath                             1.2.1
msgpack                            1.0.2
multipledispatch                   0.6.0
multiprocess                       0.70.11.1
mypy-extensions                    0.4.3
nb-conda                           2.2.1
nb-conda-kernels                   2.3.1
nbclassic                          0.3.1
nbclient                           0.5.3
nbconvert                          6.0.7
nbformat                           5.1.3
nest-asyncio                       1.5.1
networkx                           2.4
neuron-cc                          1.5.5.0+3cc38c60b
nltk                               3.6.2
nose                               1.3.7
notebook                           6.3.0
numba                              0.53.1
numexpr                            2.7.3
numpy                              1.18.4
numpydoc                           1.1.0
olefile                            0.46
openpyxl                           3.0.7
opt-einsum                         3.3.0
packaging                          20.9
pandas                             1.1.5
pandocfilters                      1.4.2
parso                              0.7.0
partd                              1.2.0
path                               15.1.2
pathlib2                           2.3.5
pathos                             0.2.7
pathspec                           0.8.1
pathtools                          0.1.2
patsy                              0.5.1
pep8                               1.7.1
pexpect                            4.8.0
pickleshare                        0.7.5
Pillow                             8.1.2
pip                                21.0.1
pkginfo                            1.7.0
plotly                             4.14.3
pluggy                             0.13.1
ply                                3.11
pox                                0.2.9
poyo                               0.5.0
ppft                               1.6.6.3
prometheus-client                  0.10.1
prompt-toolkit                     3.0.18
protobuf                           3.15.8
protobuf3-to-dict                  0.1.5
psutil                             5.8.0
psycopg2                           2.7.5
ptyprocess                         0.7.0
py                                 1.10.0
pycodestyle                        2.6.0
pycosat                            0.6.3
pycparser                          2.20
pycrypto                           2.6.1
pycurl                             7.43.0.6
pydocstyle                         6.0.0
pyflakes                           2.2.0
pygal                              2.4.0
Pygments                           2.8.1
pykerberos                         1.2.1
pylint                             2.7.2
pyls-black                         0.4.6
pyls-spyder                        0.3.2
pyodbc                             4.0.30
pyOpenSSL                          20.0.1
pyparsing                          2.4.7
PyQt5                              5.12.3
PyQt5-sip                          4.19.18
PyQtChart                          5.12
PyQtWebEngine                      5.12.1
pyrsistent                         0.17.3
PySocks                            1.7.1
pytest                             6.2.3
python-dateutil                    2.8.1
python-jsonrpc-server              0.4.0
python-language-server             0.36.2
python-slugify                     5.0.2
pytz                               2021.1
PyWavelets                         1.1.1
pyxdg                              0.26
PyYAML                             5.4.1
pyzmq                              22.0.3
QDarkStyle                         3.0.2
qstylizer                          0.2.0
QtAwesome                          1.0.2
qtconsole                          5.0.3
QtPy                               1.9.0
regex                              2021.4.4
requests                           2.25.1
requests-kerberos                  0.12.0
requests-unixsocket                0.2.0
retrying                           1.3.3
rope                               0.18.0
Rtree                              0.9.7
ruamel-yaml-conda                  0.15.80
s3fs                               0.4.2
s3transfer                         0.4.2
sacremoses                         0.0.45
sagemaker                          2.38.0
scikit-image                       0.17.2
scikit-learn                       0.24.1
scipy                              1.4.1
seaborn                            0.11.1
SecretStorage                      3.3.1
Send2Trash                         1.5.0
setuptools                         49.6.0.post20210108
simplegeneric                      0.8.1
singledispatch                     0.0.0
sip                                4.19.25
six                                1.15.0
smdebug-rulesconfig                1.0.1
sniffio                            1.2.0
snowballstemmer                    2.1.0
sortedcollections                  2.1.0
sortedcontainers                   2.3.0
soupsieve                          2.0.1
sparkmagic                         0.15.0
Sphinx                             3.5.3
sphinxcontrib-applehelp            1.0.2
sphinxcontrib-devhelp              1.0.2
sphinxcontrib-htmlhelp             1.0.3
sphinxcontrib-jsmath               1.0.1
sphinxcontrib-qthelp               1.0.3
sphinxcontrib-serializinghtml      1.1.4
sphinxcontrib-websupport           1.2.4
spyder                             5.0.1
spyder-kernels                     2.0.1
SQLAlchemy                         1.4.11
statsmodels                        0.12.2
sympy                              1.8
tables                             3.6.1
tblib                              1.7.0
tensorboard                        1.15.0
tensorflow                         1.15.0
tensorflow-estimator               1.15.1
termcolor                          1.1.0
terminado                          0.9.4
testpath                           0.4.4
text-unidecode                     1.3
textdistance                       4.2.1
threadpoolctl                      2.1.0
three-merge                        0.1.1
tifffile                           2020.6.3
tinycss2                           1.1.0
tokenizers                         0.10.3
toml                               0.10.2
tomlkit                            0.7.2
toolz                              0.11.1
torch                              1.8.1
torch-neuron                       1.8.1.1.5.12.0
torchvision                        0.9.1
tornado                            6.1
tqdm                               4.60.0
traitlets                          4.3.3
transformers                       4.6.0
typed-ast                          1.4.3
typing-extensions                  3.7.4.3
ujson                              4.0.2
unicodecsv                         0.14.1
Unidecode                          1.2.0
urllib3                            1.26.4
watchdog                           1.0.2
wcwidth                            0.2.5
webencodings                       0.5.1
websocket-client                   0.57.0
Werkzeug                           1.0.1
wheel                              0.36.2
widgetsnbextension                 3.5.1
wrapt                              1.12.1
wurlitzer                          2.1.0
xlrd                               2.0.1
XlsxWriter                         1.4.0
xlwt                               1.3.0
yapf                               0.31.0
zict                               2.0.0
zipp                               3.4.1
zope.event                         4.5.0
zope.interface                     5.4.0

**Comment by micwade-aws** [comment]
Thanks. And aws-neuron-dkms ? What's the version of that package?  It's the driver the runtime interfaces with.

**Comment by zqliu19** [comment]
> Thanks. And aws-neuron-dkms ? What's the version of that package? It's the driver the runtime interfaces with.

Package: aws-neuron-dkms
Version: 1.5.0.0
Priority: optional
Section: misc
Maintainer: Dynamic Kernel Modules Support Team <pkg-dkms-maint@lists.alioth.debian.org>
Installed-Size: 313 kB
Depends: dkms (>= 1.95)
Download-Size: 57.9 kB
APT-Manual-Installed: yes
APT-Sources: https://apt.repos.neuron.amazonaws.com bionic/main amd64 Packages
Description: aws-neuron driver in DKMS format.

**Comment by zqliu19** [comment]
![image](https://user-images.githubusercontent.com/75308137/126300632-9dfb4fdb-f8ff-4edc-843f-b889663621a9.png)

**Comment by micwade-aws** [comment]
@zqliu19 - If 4 models worked on inf1.xlarge, then we expect 16 to work on inf1.6xlarge.  Would it be possible to share the inference script with any env settings being applied and the contents of /var/log/syslog?  The syslog will help us understand what is happening in the runtime/driver and the script will help us narrow down any possible issues with over allocation to the devices.  If you prefer email instead of GitHub, the artifacts could be sent to aws-neuron-support@amazon.com
