### ISSUE TITLE
Error when compiling model in Neuron

### ISSUE THREAD

**Issue by milesmathews70** [aws/aws-neuron-sdk#305]
Hello! I am currently trying to compile a model in Neuron using a model I trained in TF 1.15 in a separate instance leveraging S3. However, I keep getting an error that the model is saved in 2.x and should be saved in 1.15.x. Any ideas on how I should go forward?

**Comment by aws-joshim** [comment]
@milesmathews70, can you share sample code on how you saved the model and/or pointers to model so that we can recreate the error?

**Comment by milesmathews70** [comment]
@aws-joshim For sure! I attached the model artifacts that I was using in this message. After you compress the gz file I linked, you should get a folder named 'Neuron_Model' I used the following script to load the model into Neuron:

`modeldir = 'Neuron_Model'compileddir = 'Optimized_Model'
tf.neuron.compile(compileddir, modeldir)`
[neuron-model.tar.gz](https://github.com/aws/aws-neuron-sdk/files/6902996/neuron-model.tar.gz)

**Comment by aws-joshim** [comment]
thanks @milesmathews70, we will try out the model artifacts and provide an update

**Comment by milesmathews70** [comment]
@aws-joshim I'm sorry, but I just realized that model artifact doesn't work, and I can't upload the ones that do work on Github. Is there a different way I can upload them?

**Comment by aws-joshim** [comment]
@milesmathews70 The model artifact on github is broken and so we cannot try yet.
 
Given that the model throws a tf 2.x error, we think that the likely cause for the error is that the model was saved with tf.saved_model.save (https://www.tensorflow.org/api_docs/python/tf/saved_model/save#expandable-1) which is a backported 2.x API. We recommend using the classic 1.x API tf.saved_model.simple_save API (https://www.tensorflow.org/versions/r1.15/api_docs/python/tf/saved_model/simple_save).

**Comment by awsrjh** [comment]
HI milesmathews70

did this suggestion help?

**Comment by aws-zejdaj** [comment]
Closing the issue since we have not heard back from you @milesmathews70 - please reopen if you need further assistance.
