### ISSUE TITLE
How to verify pytorch model inference is running on Inf1 sagemaker endpoint properly

### ISSUE THREAD

**Issue by sunbc0120** [aws/aws-neuron-sdk#310]
The current workflow is like this:

1. Trained a pytorch model in P3 instance.
2. Compiled the model on P3 with `torch.neuron` SDK.
3. Host the compiled model in TorchServe.
4. Created a SageMaker model with (1) custom Docker image that setting up TorchServe pushed to ECR and (2) compressed *mar archived with TorchServe uploaded to S3.
5. Created a SageMaker endpoint with `ml.inf1.2xlarge` using the SageMaker model created in step 4.

Now Invoking the endpoing with boto3 can obtain the model prediction result. However, the question is:

**How to verify the TorchServe hosted model is harvesting the accelerating power of `ml.inf1.2xlarge`, rather than, for instance, "falling back to CPU execution"?**

In CloudWatch the endpoint has a log stream named: `AllTraffic/i-XXX/neuron_rtd` with some `errors`:

```
---------------------------------------------------------------------------------------------------------------------------
|                                                         message                                                         |
|-------------------------------------------------------------------------------------------------------------------------|
| nrtd[1]: [NRTD:nrtd_main] nrtd build using:1.4.12.0                                                                     |
| nrtd[1]: [TDRV:reset_mla] Resetting 0000:00:1f.0                                                                        |
| nrtd[1]: [TDRV:tdrv_init_one_mla_phase2] Initialized Inferentia: 0000:00:1f.0                                           |
| D0816 09:28:58.324626004       1 env_linux.cc:71]            Warning: insecure environment read function 'getenv' used  |
| nrtd[1]: [NRTD:RunServer] Server listening on unix:/opt/amazon/var/run/infa.sock                                        |
| nrtd[1]: [NRTD:session_monitor] Session 1 started                                                                       |
| nrtd[1]: [NRTD:session_monitor] Session 1 terminated                                                                    |
| nrtd[1]: [NRTD:session_monitor] Session 2 started                                                                       |
| nrtd[1]: [NRTD:map] shm_open failed, errno=2                                                                            |
| nrtd[1]: [NRTD:shm_map] shm_map() failed.                                                                               |
| nrtd[1]: [NMGR:kmgr_create_eg] Created EG(1) with 1 NCs, start: 0                                                       |
| nrtd[1]: [NMGR:kmgr_create_eg] Created EG(2) with 1 NCs, start: 1                                                       |
| nrtd[1]: [NMGR:kmgr_create_eg] Created EG(3) with 1 NCs, start: 2                                                       |
| nrtd[1]: [NMGR:kmgr_create_eg] Created EG(4) with 1 NCs, start: 3                                                       |
| nrtd[1]: [NEFF:neff_parse] Verifying the md5 hash                                                                       |
| nrtd[1]: [NMGR:kmgr_load_nn_from_neff] Loading NN: 1.6.13.0+9f61b2f75-/tmp/tmp2nhtm5pe version: 1.0                     |
| nrtd[1]: [TDRV:kbl_model_add] Added model: 1001 on: 0(1)                                                                |
| nrtd[1]: [NEFF:neff_get_file_content] file not found loop.json in NEFF                                                  |
| nrtd[1]: [NMGR:kmgr_load_nn_from_neff] Loaded NN "1.6.13.0+9f61b2f75-/tmp/tmp2nhtm5pe" ID: 10001                        |
| nrtd[1]: [NMGR:kmgr_load_nn_from_neff] NN ID: 10001 has 1 MLA nodes and 2 CPU nodes - running in regular execution mode |
| nrtd[1]: [NMGR:kmgr_load_nn] NN: 1.6.13.0+9f61b2f75-/tmp/tmp2nhtm5pe, loaded successfully                               |
| nrtd[1]: [NEFF:neff_parse] Verifying the md5 hash                                                                       |
| nrtd[1]: [NMGR:kmgr_load_nn_from_neff] Loading NN: 1.6.13.0+9f61b2f75-/tmp/tmp9xxm0m8t version: 1.0                     |
| nrtd[1]: [TDRV:kbl_model_add] Added model: 1002 on: 1(1)                                                                |
| nrtd[1]: [NEFF:neff_get_file_content] file not found loop.json in NEFF                                                  |
| nrtd[1]: [NMGR:kmgr_load_nn_from_neff] Loaded NN "1.6.13.0+9f61b2f75-/tmp/tmp9xxm0m8t" ID: 10002                        |
| nrtd[1]: [NMGR:kmgr_load_nn_from_neff] NN ID: 10002 has 1 MLA nodes and 2 CPU nodes - running in regular execution mode |
| nrtd[1]: [NMGR:kmgr_load_nn] NN: 1.6.13.0+9f61b2f75-/tmp/tmp9xxm0m8t, loaded successfully                               |
| nrtd[1]: [NMGR:kmgr_start_nn] Started NN: 10001                                                                         |
| nrtd[1]: [NMGR:kmgr_start_nn] Started NN: 10002                                                                         |
| nrtd[1]: [NRTD:sig_act] SIG: 15                                                                                         |
---------------------------------------------------------------------------------------------------------------------------
```

**Comment by awsrjh** [comment]
Hi sunbc0120 

the errors you see are not in fact errors - the first conveys that within the container, neuron first attempts to find the shared memory path to the runtime and then falls back to grpc. The second message about the loop.json is informational. We will improve this messaging.

As for determining the amount of acceleration, there are several potential ways  : 1 is the resulting inferences per second as compared to cpu inference, the second is to use neuron-monitor (which will need to be added to your container): https://awsdocs-neuron.readthedocs-hosted.com/en/latest/neuron-guide/neuron-tools/neuron-monitor-user-guide.html. 

In addition you can use the `torch.neuron.analyze_model` method to collect information about the operator support in your network.  You can find an example of how to use this method (https://awsdocs-neuron.readthedocs-hosted.com/en/latest/src/examples/pytorch/resnet50.html?highlight=torch.neuron.analyze_model).

**Comment by sunbc0120** [comment]
> Hi sunbc0120
> 
> the errors you see are not in fact errors - the first conveys that within the container, neuron first attempts to find the shared memory path to the runtime and then falls back to grpc. The second message about the loop.json is informational. We will improve this messaging.
> 
> As for determining the amount of acceleration, there are several potential ways : 1 is the resulting inferences per second as compared to cpu inference, the second is to use neuron-monitor (which will need to be added to your container): https://awsdocs-neuron.readthedocs-hosted.com/en/latest/neuron-guide/neuron-tools/neuron-monitor-user-guide.html.
> 
> In addition you can use the `torch.neuron.analyze_model` method to collect information about the operator support in your network. You can find an example of how to use this method (https://awsdocs-neuron.readthedocs-hosted.com/en/latest/src/examples/pytorch/resnet50.html?highlight=torch.neuron.analyze_model).

Thanks very much, @awsrjh ! I will try out the 1st option and report back here for other's reference.

As to the 2nd option, my understanding is `torch.neuron.analyze` will collect information **before** compiling. However, the question here is **after** compiled, how to verify it's using the Inferentia silicon. Please correct me if I'm wrong.

**Comment by awsrjh** [comment]
HI sunbc0120,

yes you are correct - the torch.neuron.analyze step will determine this at compile time. For actuals during inference the other 2 options will help.

take care,

**Comment by aws-zejdaj** [comment]
@sunbc0120 let us know if you run into any issues trying the 1st or 2nd option
