### ISSUE TITLE
Inferencing on larger input taking too long.

### ISSUE THREAD

**Issue by Udit1999** [aws/aws-neuron-sdk#315]
Hey, 
We are facing an issue while inferencing the AWS neuron compiled model on the large inputs. It is working well on 512x512 input, the performance boost is clearly visible as we are getting a 10x gain in speed as compared to CPU inference.  But when we the same model compiled with input size 1024x1024, the inference time went up to 15mins which is ~14x more than the CPU inference.

Here is some basic info:

1. We are using inf1.6xlarge.
2. The model got 100% compiled with 100% fusion.
3. Here is the output of neuron-top
![Screenshot from 2021-08-23 13-13-57](https://user-images.githubusercontent.com/42462392/130410038-d412382a-56b7-41b0-abd9-c44b8a4e6b00.png)

@neildcruz

**Comment by awsryg** [comment]
Hi @Udit1999 , thank for your feedback. The performance loss you are reporting is not expected. It is worthy of some investigation. If you are interested in pursuing, you can use TensorBoard:
https://awsdocs-neuron.readthedocs-hosted.com/en/latest/neuron-guide/neuron-tools/getting-started-tensorboard-neuron-plugin.html#neuron-plugin-tensorboard 
And / Or, if you can share with us the model you are using, we can try to reproduce the problem and try to look into it.

**Comment by aws-zejdaj** [comment]
@Udit1999, have you had chance to try the tensorboard to get insight into where time is spent?

If you need help to debug performance we'll be happy to look at your model. You can share it here on github or privately with us at aws-neuron-support@amazon.com

**Comment by mrnikwaws** [comment]
Hi Udit,

The team is actively working on answering your question.  We'll respond here as that guidance becomes available.

**Comment by aws-taylor** [comment]
Hello @Udit1999,

 We've addressed the issues exposed when using the 512x512 model and you should expect the fixes to be available in a near release. As for the 1024x1024 model, we've identified the issue and are investigating potential performance improvements.

  One other observation we made was that your compiled model contains bi-linear resize operations with non-integral scale factors. Such instructions cannot currently be executed on inf1. If you are able to refactor your model to avoid these operations then you'll likely see additional performance.

Regards,
Taylor

**Comment by awsrjh** [comment]
Closing based on 

https://github.com/aws/aws-neuron-sdk/issues/346
