### ISSUE TITLE
Disadvantage when Dynamic batching set True

### ISSUE THREAD

**Issue by manchann** [aws/aws-neuron-sdk#322]
When I compiled the model using neuron sdk, I tried to set the 'dynamic batching' True and False. The experiment showed that when using dynamic batching, its performance slightly better. So I think it'll always be okay to set True.
Then, is there a case when dynamic batching must be set False?

**Comment by jeffhataws** [comment]
Hi manchann,
When dynamic batching is enabled, Neuron needs to select the batching dimension. This is not always possible for all models so it is off by default since many models do not have batching dimension.

**Comment by manchann** [comment]
Thank you for answer my question.
I newly learned that dynamic batching is not available in all cases and I understand the answer. Then, if in the case that dynamic batching is available, it is always advantage using dynamic batching?

**Comment by aws-renfu** [comment]
Hi manchann,

Dynamic batchig is simply a syntactic sugar that is provided for user convenience. The overhead is small (a couple of 'if' statements, i.e. padding when the input size is too small). So in the case your models have well-defined batching axis such that dynamic batching can be supoorted, it will make your code easier to maintain.

**Comment by mrnikwaws** [comment]
Hi @manchann,

I believe the question has been answered - please re-open if you have further questions
