### ISSUE TITLE
How to tell if my tensorflow pipeline is benefiting from inf1's hardware acceleration.

### ISSUE THREAD

**Issue by dan-hu-spring** [aws/aws-neuron-sdk#324]
I'm posting this because for a specified input, my ALBERT TF2 model usually takes 15 seconds to process on a `g4dn.xlarge` GPU instance but is taking 45 seconds on a `inf1.6xlarge`. I'm assuming a neuron-compiled version of this model should take at most the same amount of time, based on the documentation and marketing message of the inf1 instances. 

FYI: I'm not using huggingface; I'm using the TF models repo's version of ALBERT trained on a Google TPU.

I've tried tracing the model and running the neuron traced model on the results immediately. Using the examples from this link: https://awsdocs-neuron.readthedocs-hosted.com/en/latest/neuron-guide/neuron-frameworks/tensorflow-neuron/api-tracing-python-api.html.

Something like

```
model_neuron = tfn.trace(albert_model, example_input)
model_neuron.save('my_model')
with timer.time():
    logits = model_neuron(x, training=False)
```

I also tried loading it from compiled saved model. (This is more confusing since I don't need tensorflow-neuron installed to load the models from keras right).
 
```
model_neuron = tf.keras.models.load_model('my_model')
with timer.time():
    logits = model_neuron(x, training=False)
```

In either scenario, I'm not getting the expected results. On a GPU-accelerated EC2, tensorflow logs that hardware name of the CUDA device accelerating it. I'm not seeing any such relevant information in the logs in the inf1 neuron build. But I did get this log message that I can't find much information about.

```
2021-09-10 00:05:01.856022: F tensorflow/neuron/tf2hlo/aws_neuron_tf2hlo.cc:78] Non-OK-status: status status: Internal: RET_CHECK failure (tensorflow/neuron/tf2hlo/compile.cc:52) SerializeToBufferDeterministic(*module, serialized.get(), size) 
```

So I guess my questions are:
- how do I know that my tensorflow 2.4 environment is benefiting from inf1's hardware acceleration? Is there a command I can run that can tell me that?
- Importing the model is done through `tf.keras.models.load_model('my_model')`. Is it expected that it does not require a `tensorflow.neuron` library dependency to import it.

**Comment by aws-renfu** [comment]
Hi Dan,

Based on the serialization failure in "SerializeToBufferDeterministic" and that "my ALBERT TF2 model usually takes 15 seconds to process on a g4dn.xlarge GPU instance", it is very likely that this model is too big and it hits the 2 GB protobuf size limit during tf2xla protobuf format conversion. This is a hard limitation of XLA AOT because of our current implementation. It is on our roadmap to life this restriction. 

The workaround is to call tfn.trace on part of the model instead of the full model, e. g.,

```
class FullModel(tf.keras.model):
    def __init__(self, submodel0, submodel1):
        super().__init__(trainable=False, autocast=False)
        self.submodel0 = submodel0
        self.submodel1 = submodel1
    def call(self, inputs):
        return self.submodel1(self.submodel0(inputs))

submodel0 = tf.keras.Model(...)
submodel1 = tf.keras.Model(...)
model = FullModel(submodel0, submodel1)

model.submodel0 = tfn.trace(model.submodel0, ...)
model.submodel1 = tfn.trace(model.submodel1, ...)
```

**Comment by aws-renfu** [comment]
On the model importing question, it is expected that they do not need to import tensorflow.neuron, because tensorflow automatically hooks up to us once tensorflow-neuron is installed

**Comment by dan-hu-spring** [comment]
Thanks for the response @aws-renfu. I am using the ALBERT xxlarge model. Not sure if the submodel approach would work for me but perhaps I'll give it a try.

**Comment by dan-hu-spring** [comment]
Also, which of these items relates to the tf2xla ticket on the public roadmap? https://github.com/aws/aws-neuron-sdk/projects/2?fullscreen=true, I would love to keep track of this effort.

**Comment by mrnikwaws** [comment]
Hi Dan,

The XLA is part of our intermediate representation in the compilation process.  Lifting the tf2xla size limitations is not tracked on the github project, but you can follow our [What’s New page](https://awsdocs-neuron.readthedocs-hosted.com/en/latest/release-notes/index.html) for upcoming releases.

We are also exploring improving the error message for the failure mode you encountered in a future release.

Were you able to split compilation into sub-models?  If you have been able to solve the problem I will plan to close this ticket.

**Comment by aws-taylor** [comment]
Hello @dan-hu-spring,

 Just a follow-up - were you able to split compilation into sub-models and/or compile successfully?

Regards,
Taylor

**Comment by dan-hu-spring** [comment]
No, unfortunately our team is not familiar enough with the BERTSpanLabeler layer to split it. We plan to observe the progress of the tf2xla size issue and re-attempt adopting the neuron library when that ticket is complete. Thank you!

**Comment by aws-diamant** [comment]
Hi @dan-hu-spring,

Quick update:  we were able to recreate the issue that you are reporting, and are working on a solution. We will update this ticket with the relevant roadmap item once available.

**Comment by awsrjh** [comment]
please track this; https://github.com/aws/aws-neuron-sdk/issues/357
