### ISSUE TITLE
[PyTorch] dynamic_batch_size=True breaks bi-directional LSTM

### ISSUE THREAD

**Issue by Askannz** [aws/aws-neuron-sdk#326]
Hi,

It seems that that PyTorch models compiled with `torch.neuron.trace()` break when the following conditions are met:

* The model contains a `torch.nn.LSTM` module
* The parameter `bidirectional=True` is set on that module
* The model is compiled with `dynamic_batch_size=True`

The compilation passes without error, but trying to run inference on the compiled model raises the following exception: `RuntimeError: Inconsistent neff batch sizes`.

I am aware that Inferentia does not support the LSTM module ([yet](https://github.com/aws/aws-neuron-sdk/issues/242)), but this bug prevents Neuron from using the CPU fallback (which otherwise works outside of the situation described above).

Here's a minimal example. The `ReLU` module is only there so that Neuron can offload at least one operation to Inferentia, and does not abort compilation thinking the whole trace has failed. You can swap it out for `torch.nn.Linear` with the same result.

If `bidirectional` or `dynamic_batch_size` are changed to `False`, the crash does not happen anymore.

```python
import torch
import torch.nn as nn
import torch_neuron


model = nn.Sequential(
    nn.ReLU(),
    nn.LSTM(1, 1, bidirectional=True, batch_first=True)
)
model.eval()

input_tensor = torch.zeros((1, 1, 1), dtype=torch.float32)

print("\nCompilation")
model_neuron = torch.neuron.trace(
    model,
    example_inputs=[input_tensor],
    dynamic_batch_size=True)

print("\nInference")
model_neuron(input_tensor)
```
Console output:
```
Compilation
INFO:Neuron:There are 1 ops of 1 different types in the TorchScript that are not compiled by neuron-cc: aten::lstm, (For more information see https://github.com/aws/aws-neuron-sdk/blob/master/release-notes/neuron-cc-ops/neuron-cc-ops-pytorch.md)
INFO:Neuron:Number of arithmetic operators (pre-compilation) before = 7, fused = 6, percent fused = 85.71%
INFO:Neuron:Compiling function _NeuronGraph$15 with neuron-cc
INFO:Neuron:Compiling with command line: '/home/ubuntu/env/bin/neuron-cc compile /tmp/tmp3dr_nja9/graph_def.pb --framework TENSORFLOW --pipeline compile SaveTemps --output /tmp/tmp3dr_nja9/graph_def.neff --io-config {"inputs": {"0:0": [[1, 1, 1], "float32"]}, "outputs": ["Relu:0", "zeros:0", "zeros_1:0"]} --verbose 35'
.Analyzing dependencies of sg00/Block1
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

Compiler status PASS
INFO:Neuron:Number of arithmetic operators (post-compilation) before = 7, compiled = 6, percent compiled = 85.71%
INFO:Neuron:The neuron partitioner created 1 sub-graphs
INFO:Neuron:Neuron successfully compiled 1 sub-graphs, Total fused subgraphs = 1, Percent of model sub-graphs successfully compiled = 100.0%
INFO:Neuron:Compiled these operators (and operator counts) to Neuron:
INFO:Neuron: => aten::Int: 2
INFO:Neuron: => aten::relu: 1
INFO:Neuron: => aten::size: 1
INFO:Neuron: => aten::zeros: 2
INFO:Neuron:Not compiled operators (and operator counts) to Neuron:
INFO:Neuron: => aten::lstm: 1 [not supported]

Inference
Traceback (most recent call last):
  File "bug_repro.py", line 21, in <module>
    model_neuron(input_tensor)
  File "/home/ubuntu/env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
/home/ubuntu/env/lib/python3.6/site-packages/torch_neuron/decorators.py(348): forward
/home/ubuntu/env/lib/python3.6/site-packages/torch/nn/modules/module.py(860): _slow_forward
/home/ubuntu/env/lib/python3.6/site-packages/torch/nn/modules/module.py(887): _call_impl
/home/ubuntu/env/lib/python3.6/site-packages/torch_neuron/graph.py(523): __call__
/home/ubuntu/env/lib/python3.6/site-packages/torch_neuron/graph.py(189): run_op
/home/ubuntu/env/lib/python3.6/site-packages/torch_neuron/graph.py(178): __call__
/home/ubuntu/env/lib/python3.6/site-packages/torch_neuron/convert.py(173): forward
/home/ubuntu/env/lib/python3.6/site-packages/torch/nn/modules/module.py(860): _slow_forward
/home/ubuntu/env/lib/python3.6/site-packages/torch/nn/modules/module.py(887): _call_impl
/home/ubuntu/env/lib/python3.6/site-packages/torch/jit/_trace.py(940): trace_module
/home/ubuntu/env/lib/python3.6/site-packages/torch/jit/_trace.py(742): trace
/home/ubuntu/env/lib/python3.6/site-packages/torch_neuron/convert.py(139): trace
bug_repro.py(18): <module>
RuntimeError: Inconsistent neff batch sizes
```

Environment:
```
Python 3.6.9
neuron-cc==1.6.13.0+9f61b2f75
torch==1.8.1
torch-neuron==1.8.1.1.5.21.0
```
System:
```
ii  aws-neuron-dkms                        2.1.5.0                             amd64        aws-neuron driver in DKMS format.
ii  aws-neuron-runtime                     1.6.24.0                            amd64        Neuron Runtime Driver and Inference Server
ii  aws-neuron-runtime-base                1.6.21.0                            amd64        neuron_base built using CMake
ii  aws-neuron-tools                       1.7.25.0                            amd64        Neuron profile and debug tools
```

**Comment by mrnikwaws** [comment]
Hi Robin,

The reason for the issue you are seeing is that the auto-partioner works at the resolution of PyTorch operators.  In the sample graph zero tensors are implicitly constructed for the LSTM hidden state.  The auto-partitioner is excluding the (unsupported) LSTM operator, but fusing the (supported) zeros operator.  The dimensions of the hidden state tensor are different for a bidirection LSTM ([2,1,1] vs. [1,1,1] in this case) and this violates the batch assumptions made by the dynamic batching logic (also these hidden state tensors do not respect 'batch-first').

To avoid compiling the implicit hidden state to Neuron you can do the following:
```
import torch
import torch.nn as nn
import torch_neuron


model = nn.Sequential(
    nn.ReLU(),
    nn.LSTM(1, 1, bidirectional=False, batch_first=True)
)
model.eval()

input_tensor = torch.zeros((5, 1, 1), dtype=torch.float32)

def graph_builder(node):
    if "LSTM" in node.name or node.name.startswith('prim'):
        print(node.name, "[CPU]")
        return False
    else:
        print(node.name, "[Neuron]")
        return True

print("\nCompilation")
model_neuron = torch.neuron.trace(
    model,
    example_inputs=[input_tensor],
    dynamic_batch_size=True,
    subgraph_builder_function = graph_builder,
    minimum_segment_size=1)

#traced = torch.jit.trace(model, [input_tensor])
#torch._C._jit_pass_inline(traced.graph)

#print(traced.graph)
print(model_neuron.graph)

print("\nInference")
print(model_neuron(input_tensor))
```
This code makes use of a "subgraph_builder_function" - this decides which operators get partitioned to Neuron or the CPU based on naming. 'minimum_segment_size' tells the partitioner it is OK to compile just one partitioned operator (ReLU) in this test code.  It should be easy to extend to your real code.

I figured this out by comparing this out by comparing the regular torch.jit.trace to the torch.neuron.trace and comparing the graphs.  We are looking into LSTM support in neuron, so hopefully we can come up with a more elegant solution for you in a future release.

Please let us know if this does not resolve your issue.

**Comment by Askannz** [comment]
Hi @mrnikwaws 

Thanks for the explanation and the workaround. We were able to compile our full model to Inferentia using that `graph_builder()` function and tweaking it a bit.

Unfortunately it turned out that offloading the LSTM to CPU crippled the performance of our model too much. But we'll be sure to re-visit Inferentia for this model when support for this operation is implemented. Looking forward to it!
