### ISSUE TITLE
Examples using detectron2?

### ISSUE THREAD

**Issue by joel1st** [aws/aws-neuron-sdk#332]
Are there any examples on how to use this with detectron2? I know detectron2 uses pytorch under the hood, but I'm curious if there is a recommended approach that doesn't involve changing the detectron2 library. For reference I am using the PointRend model: https://github.com/facebookresearch/detectron2/tree/main/projects/PointRend

**Comment by hannanjgaws** [comment]
Hi @joel1st:

Detectron2 is based on the Mask RCNN model family. Support for Mask RCNN models is on our roadmap. You can track the progress of this effort under roadmap item #153.
