### ISSUE TITLE
Model has not support operation how to solve?

### ISSUE THREAD

**Issue by gongxh13** [aws/aws-neuron-sdk#343]
I has many other people trained model, but these model has many not support operation. The output log as below:
``
Failed to parse model /home/ec2-user/gongxh/./tfx_bed/: The following operators are not implemented: {'PlaceholderWithDefault', 'SaveV2', 'StringJoin', 'VariableV2', 'ShardedFilename', 'TruncatedNormal', 'Assign', 'RestoreV2'(aws_neuron_tensorflow_p36)(aws_neuron_tensor(aws_neuron_tensor
```
I want know whether have solution? (I has no train code, so I can not change model)

**Comment by awsrjh** [comment]
HI gongxh13

could you supply us with the output of the file "log-neuron-cc.txt" ? It seems that there are few supported operators.

you can send it to aws-neuron-support@amazon.com

The list of supported operators is found here:

https://awsdocs-neuron.readthedocs-hosted.com/en/latest/release-notes/neuron-cc-ops/index.html

**Comment by gongxh13** [comment]
> HI gongxh13
> 
> could you supply us with the output of the file "log-neuron-cc.txt" ? It seems that there are few supported operators.
> 
> you can send it to [aws-neuron-support@amazon.com](mailto:aws-neuron-support@amazon.com)
> 
> The list of supported operators is found here:
> 
> https://awsdocs-neuron.readthedocs-hosted.com/en/latest/release-notes/neuron-cc-ops/index.html

Hello.  where is file "log-neuron-cc.txt" location ?

**Comment by aws-owinop** [comment]
Hi @gongxh13,
By default you can find this log file in the compiler logs directory, where you also find the graph_def.pb, relay_graph_opt_pre_color.txt.

**Comment by awsrjh** [comment]
Hi

has this helped or is this issues still happening?

**Comment by mrnikwaws** [comment]
Closing - since there has been no response, please re-open this ticket if you are able to provide more information.
