### ISSUE TITLE
How to enable data parallel in tensorflow without NCGs using latest neuron SDK

### ISSUE THREAD

**Issue by zqliu19** [aws/aws-neuron-sdk#349]
The latest release has deprecated support for NCGs, and for pytorch we can use torch.neuron.DataParallel API to enable data parallel.
For tensorflow, what is the recommended way to do it? (tutorial https://github.com/aws/aws-neuron-sdk/blob/master/src/examples/tensorflow/keras_resnet50/infer_resnet50_keras_loadtest.py still uses NCG, which is confusing since the latest release saying NCG is deprecated)

The existing example code for TF:

```python
group_sizes = [str(1)] * avail_neuroncores
os.environ['NEURONCORE_GROUP_SIZES'] = ','.join(group_sizes)
```
```python
pred_list = [tf.contrib.predictor.from_saved_model(COMPILED_MODEL_DIR) for _ in range(avail_neuroncores)]
pred_list = pred_list * NUM_THREADS_PER_PREDICTOR
num_threads = len(pred_list)
```

```python
def one_thread(pred, model_feed_dict):
    result = pred(model_feed_dict)
    return result
executor = futures.ThreadPoolExecutor(max_workers = num_threads)
```

`running = {executor.submit(one_thread,pred_list[idx],model_feed_dict): idx for idx in range(num_threads)}`

what do we need to change for the above code for the latest TF-neuron release?

**Comment by awsrjh** [comment]
we will continue to add more tutorials and guides to help provide more information on these new areas. 

We have also created overall guidance here:

https://awsdocs-neuron.readthedocs-hosted.com/en/latest/neuron-guide/appnotes/neuron-components/introducing-libnrt.html#migrate-your-application-to-neuron-runtime-2-x-libnrt-so

see item  # 6.

In the mean time - the use of NeuronCoreGroupSizes will continue to work.

**Comment by zqliu19** [comment]
> we will continue to add more tutorials and guides to help provide more information on these new areas.
> 
> We have also created overall guidance here:
> 
> https://awsdocs-neuron.readthedocs-hosted.com/en/latest/neuron-guide/appnotes/neuron-components/introducing-libnrt.html#migrate-your-application-to-neuron-runtime-2-x-libnrt-so
> 
> see item # 6.
> 
> In the mean time - the use of NeuronCoreGroupSizes will continue to work.

Thanks for the reply.
Tried, but it doesn't work. Details below:
 https://github.com/aws/aws-neuron-sdk/issues/351

**Comment by awsrjh** [comment]
the information at

https://awsdocs-neuron.readthedocs-hosted.com/en/latest/neuron-guide/neuron-runtime/nrt-configurable-parameters.html

Should help clarify how to use these environment variables.

regards,
