### ISSUE TITLE
infer error 1004 with NeuronRT2.x + TensorFlow-1.x

### ISSUE THREAD

**Issue by zqliu19** [aws/aws-neuron-sdk#351]
```python
group_sizes = [str(1)] * avail_neuroncores
os.environ['NEURONCORE_GROUP_SIZES'] = ','.join(group_sizes)

pred_list = [tf.contrib.predictor.from_saved_model(COMPILED_MODEL_DIR) for _ in range(avail_neuroncores)]
pred_list = pred_list * NUM_THREADS_PER_PREDICTOR
num_threads = len(pred_list)

def one_thread(pred, model_feed_dict):
    result = pred(model_feed_dict)
    return result
executor = futures.ThreadPoolExecutor(max_workers = num_threads)

running = {executor.submit(one_thread,pred_list[idx],model_feed_dict): idx for idx in range(num_threads)}
```

error:
2021-Nov-01 06:02:18.0992 13660:14125 ERROR  NMGR:dlr_infer                               Inference completed with err: 1004
2021-11-01 06:02:18.992183: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at neuron_op.cc:44 : Internal: tensorflow/neuron/runtime/direct/adaptor.cc:446:Execute failed: nrt_execute: status=1004, error message="Execution was completed with other errors".
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/aws_neuron_tensorflow_p36/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/home/ubuntu/anaconda3/envs/aws_neuron_tensorflow_p36/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "/home/ubuntu/anaconda3/envs/aws_neuron_tensorflow_p36/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InternalError: tensorflow/neuron/runtime/direct/adaptor.cc:446:Execute failed: nrt_execute: status=1004, error message="Execution was completed with other errors".
         [[{{node resnet_model/neuron_op_a85e4e2fb66543cb}}]]

The same code worked when we were using NeuronRT1.0

UPDTAE:
**This ERROR occurs when we set consumed cores to be 1 first and then set consumed cores to be 4**
Using NeuronRT1.0 doesn't have this issue

**Comment by zqliu19** [comment]
fixed by re-install, closing

**Comment by zqliu19** [comment]
error log:
![image](https://user-images.githubusercontent.com/75308137/139642890-e56c9dfc-5ea5-4683-a4a2-aa5c8c6b4a5c.png)

using 1 core first and then use 4 cores will not work.

**Comment by zqliu19** [comment]
FURTHER UPDATE:
re-start the instance, then we found that the error is gone.
Even when we do the same thing (using 1 core first and then use 4 cores as shown in https://github.com/aws/aws-neuron-sdk/issues/351#issuecomment-956031450) we will not see that error.
Seems the error can not be reliably re-produced, sometimes it throws the error, sometimes not, with same code/sw
weird to see that NeuronRT2.x + TensorFlow-1.x + NCG is not reliably working

**Comment by awsrjh** [comment]
zqliu19, thanks for the report. we will examine this and provide more information as soon as we have it.

**Comment by micwade-aws** [comment]
@zqliu19 - the [1004 error](https://awsdocs-neuron.readthedocs-hosted.com/en/latest/neuron-guide/neuron-runtime/v1/nrt-return-codes.html) from neuron-rtd indicates a possible transient HW failure.  We use automation to find and replace hardware issues and while rare it's possible for a failure to happen while you were using the instance.  If possible, please email us the instance-id where the failure occurred and we'll take a closer look.  Our support email is aws-neuron-support@amazon.com.

**Comment by zqliu19** [comment]
> @zqliu19 - the [1004 error](https://awsdocs-neuron.readthedocs-hosted.com/en/latest/neuron-guide/neuron-runtime/v1/nrt-return-codes.html) from neuron-rtd indicates a possible transient HW failure. We use automation to find and replace hardware issues and while rare it's possible for a failure to happen while you were using the instance. If possible, please email us the instance-id where the failure occurred and we'll take a closer look. Our support email is [aws-neuron-support@amazon.com](mailto:aws-neuron-support@amazon.com).

Thanks a lot @micwade-aws for checking this.
I have terminated the instance and didn't track the ID. Will email you the instance ID if I see this error again.
