### ISSUE TITLE
Warning message after neuron-ls 

### ISSUE THREAD

**Issue by JBKYang** [aws/aws-neuron-sdk#359]
I installed the latest neuron SDK with the installation instructions [here](https://awsdocs-neuron.readthedocs-hosted.com/en/latest/neuron-guide/neuron-frameworks/pytorch-neuron/index.html)
However when I do `neuron-ls` there's a warning
```
neuron-ls
Neuron Tools have changed with Neuron v1.16.0. Go here to learn more:
https://awsdocs-neuron.readthedocs-hosted.com/en/latest/neuron-guide/neuron-tools/

If you're still running Neuron Runtime 1.0, run this program as sudo to display neuron-rtd runtime information

+--------+--------+--------+--------------+
| NEURON | NEURON | NEURON |     PCI      |
| DEVICE | CORES  | MEMORY |     BDF      |
+--------+--------+--------+--------------+
| 0      | 4      | 8 GB   | 0000:00:1f.0 |
+--------+--------+--------+--------------+
```
When I go to the suggested [neuron-ls link](https://awsdocs-neuron.readthedocs-hosted.com/en/latest/neuron-guide/neuron-tools/neuron-ls.html) the result doesn't show the above issue. Am I using an old version of Neuron SDK?

Another additional question - is there a way to not use neuron-ls? Can I find the number of neuron instances with the pytorch/tensorflow SDK?

**Comment by micwade-aws** [comment]
The warning messages were omitted from the documentation and will be removed on future versions of the Neuron Tools packages.  The frameworks do not have an API to query device count.  The closest/fastest approach would be to scan /dev/ for Neuron Devices (/dev/neuron*).
