### ISSUE TITLE
How to run multiple "Application with runtime containers" on single inf1 node?

### ISSUE THREAD

**Issue by Udit1999** [aws/aws-neuron-sdk#363]
Hi,
I got this error when I was trying to run multiple containers on the same inf1 instance.

`[E neuron_runtime.cpp:333] NeuronDevice::process_nrtd_response: Context=NRTD_CTX_INFER_POST NRTD response code 'NERR_FAIL' (1) This is a general catch-all failure.  Please reach out to AWS support. Raw runtime error message '[TDRV:wait_for_engine_start] Failed to start 3 engines.
[NMGR:dlr_kelf_start] Model (1001) start wait failed for VNC=0, ret: 1
[TDRV:kbl_exec_wait]  Sync Infer Completion failed for cookie: 0x1, err: 2
[NRTD:start] Failed to start NN: 10001
`

I'm using "inf1.2xlarge" and it is highly under-utilized with a single application container and these applications also don't vertically scale well. So, I wanted to run multiple application containers on the same node while using the same or different neuron-runtimes. 

I referred this [doc](https://awsdocs-neuron.readthedocs-hosted.com/en/latest/neuron-deploy/v1/packaging-neuron-rt-containers.html#packaging-neuron-rt-containers-rst) for "Packaging Application and Neuron Runtime in the same container" and 
"Packaging Application and Neuron Runtime in different container". I have tried both things for multiple containers but neither of them worked for me.

**Is there any way to run multiple "Application with runtime containers" or multiple "Application containers" using the same runtime on a single inf1 node?**

@neildcruz

**Comment by awsryg** [comment]
Thanks for reaching out.  If it is possible to update all Neuron components to latest, please do so as it will remove the need for dealing with neuron-rtd.  If you prefer to stay on the older software, the document pointed at is the ideal starting point.  What's not clear is the specific configuration you're attempting to use from the documentation.  To help us figure out what is going on, please indicate the version of aws-neuron-dkms on the host and the version(s) of aws-neuron-runtime (neuron-rtd) that's running on the host or inside the container depending on config.  We will also need to know the version(s) of ML/Neuron frameworks in use inside the app container(s).  Thanks!

**Comment by awsrjh** [comment]
Hi udit1999,

did this suggestion to update to the latest help you?

**Comment by Udit1999** [comment]
Hi awsrjh,

Updating to the latest version along with setting env var `NEURONCORE_GROUP_SIZES=1` worked for us.
Thanks a lot.

Closing this issue.
