### ISSUE TITLE
Error while inferring on traced sshleifer/distilbart-cnn-12-6

### ISSUE THREAD

**Issue by DevBey** [aws/aws-neuron-sdk#364]
the module actually got traced though in 40 min or something, but when I tried to do inference on the traced model it threw errors.

default Aws neuron 1.9.1+cu102 environment !!

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-26-3ef79b68a6e9> in <module>
----> 1 model_neuron(*inputs_trace)

~/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
   1049         if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1050                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1051             return forward_call(*input, **kwargs)
   1052         # Do not call functions when jit is used
   1053         full_backward_hooks, non_full_backward_hooks = [], []

RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch_neuron/decorators.py(347): forward
/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/nn/modules/module.py(1039): _slow_forward
/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/nn/modules/module.py(1051): _call_impl
/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch_neuron/graph.py(546): __call__
/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch_neuron/graph.py(205): run_op
/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch_neuron/graph.py(194): __call__
/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch_neuron/convert.py(220): forward
/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/nn/modules/module.py(1039): _slow_forward
/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/nn/modules/module.py(1051): _call_impl
/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/jit/_trace.py(959): trace_module
/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/jit/_trace.py(744): trace
/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch_neuron/convert.py(186): trace
<ipython-input-24-92e51e910a02>(3): <module>
/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/IPython/core/interactiveshell.py(3343): run_code
/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/IPython/core/interactiveshell.py(3263): run_ast_nodes
/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/IPython/core/interactiveshell.py(3072): run_cell_async
/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/IPython/core/async_helpers.py(68): _pseudo_sync_runner
/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/IPython/core/interactiveshell.py(2895): _run_cell
/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/IPython/core/interactiveshell.py(2867): run_cell
/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/ipykernel/zmqshell.py(539): run_cell
/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/ipykernel/ipkernel.py(302): do_execute
/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/contextvars/__init__.py(38): run
/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/tornado/gen.py(234): wrapper
/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/ipykernel/kernelbase.py(538): execute_request
/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/contextvars/__init__.py(38): run
/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/tornado/gen.py(234): wrapper
/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/ipykernel/kernelbase.py(261): dispatch_shell
/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/contextvars/__init__.py(38): run
/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/tornado/gen.py(234): wrapper
/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/ipykernel/kernelbase.py(358): process_one
/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/tornado/gen.py(775): run
/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/contextvars/__init__.py(38): run
/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/tornado/gen.py(814): inner
/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/tornado/ioloop.py(741): _run_callback
/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/tornado/ioloop.py(688): <lambda>
/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/asyncio/events.py(145): _run
/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/asyncio/base_events.py(1462): _run_once
/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/asyncio/base_events.py(442): run_forever
/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/tornado/platform/asyncio.py(199): start
/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/ipykernel/kernelapp.py(619): start
/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/traitlets/config/application.py(664): launch_instance
/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/ipykernel_launcher.py(16): <module>
/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/runpy.py(85): _run_code
/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/runpy.py(193): _run_module_as_main
RuntimeError: The PyTorch Neuron Runtime could not be initialized. Neuron Driver issues are logged
to your system logs. See the Neuron Runtime's troubleshooting guide for help on this
topic: https://awsdocs-neuron.readthedocs-hosted.com/en/latest/

**Comment by DevBey** [comment]
while tracing it says, not supported for a few things, is the error because of this ??
INFO:Neuron: => aten::embedding: 4 [not supported]
INFO:Neuron: => aten::eq: 1 [supported]
INFO:Neuron: => aten::expand: 1 [supported]
INFO:Neuron: => aten::masked_fill: 1 [supported]
INFO:Neuron: => aten::new_zeros: 1 [not supported]

**Comment by aws-joshim** [comment]
@DevBey, the inference failures that are you are seeing are likely due to this error that was shared in the log above
RuntimeError: The PyTorch Neuron Runtime could not be initialized. Neuron Driver issues are logged
to your system logs

Please double check that the Neuron driver is loaded by verifying the presence of Neuron Device(s) in the host under /dev. If you don't see them or are unsure, reinstall the aws-neuron-dkms package by first removing it and then installing it.
Command to check for devices:
 ls -als /dev/neuron*
Commands to reinstall the driver:
yum remove aws-neuron-dkms
yum install aws-neuron-dkms

More details on troubleshooting runtime and driver issues may be found here: https://awsdocs-neuron.readthedocs-hosted.com/en/latest/neuron-guide/neuron-runtime/nrt-troubleshoot.html
If this doesn't help, please provide more details about the software versions involved:
yum list installed | grep neuron
pip list | grep neuron

**Comment by DevBey** [comment]
Hi @aws-joshim, thanks for a prompt response.

I was able to mitigate these errors and trace the model using this 

traced_model = torch.neuron.trace(model,(inputs["input_ids"],inputs["attention_mask"]), verbose=1, compiler_workdir='./compilation_artifacts')

I have been able to deploy around five transformer models some even finetuned on sagemaker doing the same, but when I tried the same with this model which is an encoder-decoder model, I am getting weird tensor output instead of summary_input_ids which I should ideally get. ideally it should be like this -> 
tensor([[    2,     0,   250,   752, 27492,   803,   669,     5,   121,     4,
           104,     4,   641,     9,  6338,    18, 24869,  5033,  5264,     8,
          1309,  4237,     7,   645,    10,  2499,  1830, 28472, 19003,   479,
            20, 28472, 19003,    21,  2740,    30,     5,   641,     9,  4178,
             7,    28,  5923,    11,  2499,     6,  1184,   479,    85,    18,
             5,    78,    86,    10, 28472, 19003,     2]])


I have also tried tracing in a similar way as this github issue only to lead to the same output which looks like this -> 
![image](https://user-images.githubusercontent.com/85338857/143293761-709262b9-0cdd-49ea-acf8-8043e132ade3.png)

**Comment by aws-joshim** [comment]
@DevBey the neuron trace example code in the  tutorial https://github.com/aws/aws-neuron-sdk/blob/master/src/examples/pytorch/transformers-marianmt.ipynb provides examples for tracing encoder/decoder generative models. We recommend that you use that as reference for the trace issues that you see with the distilbart-12-6-cnn model. Please send us a email at aws-neuron-support@amazon.com with the AWS account ID for the deployment support request.

**Comment by DevBey** [comment]
Hi @aws-joshim, 

I also tried this notebook last few cells for pegasus and my model both failed without following errors !!








---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-17-cafee58cc37e> in <module>
      6     num_beams=num_beams,
      7     max_encoder_length=max_encoder_length,
----> 8     max_decoder_length=max_decoder_length,
      9 )
     10 infer(pegasus_neuron, pegasus_tokenizer, pegasus_text)

<ipython-input-7-95cbb5e23ebf> in trace(self, model, num_texts, num_beams, max_encoder_length, max_decoder_length)
     35         )
     36         decoder = NeuronDecoder(model, max_decoder_length)
---> 37         self.decoder = torch_neuron.trace(decoder, inputs)
     38 
     39     # ------------------------------------------------------------------------

~/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch_neuron/convert.py in trace(func, example_inputs, fallback, op_whitelist, minimum_segment_size, subgraph_builder_function, subgraph_inputs_pruning, skip_compiler, debug_must_trace, allow_no_ops_on_neuron, compiler_workdir, dynamic_batch_size, compiler_timeout, _neuron_trace, compiler_args, verbose, **kwargs)
    148 
    149     # Translate the torch-script to a Graph object
--> 150     neuron_graph, jit_trace = to_graph(func, example_inputs, return_trace=True, **kwargs)
    151 
    152     if _dump_graph_json:

~/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch_neuron/convert.py in to_graph(func_or_mod, example_inputs, return_trace, **kwargs)
    227     example_inputs = execute.unify_example_inputs(example_inputs)
    228     with track_script() as script_tracker, torch_trace_error_handler():
--> 229         jit_trace = torch.jit.trace(func_or_mod, example_inputs, **kwargs)
    230     original_name = getattr(jit_trace, 'original_name',
    231                             getattr(jit_trace, 'name', None))

~/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/jit/_trace.py in trace(func, example_inputs, optimize, check_trace, check_inputs, check_tolerance, strict, _force_outplace, _module_class, _compilation_unit)
    742             strict,
    743             _force_outplace,
--> 744             _module_class,
    745         )
    746 

~/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/jit/_trace.py in trace_module(mod, inputs, optimize, check_trace, check_inputs, check_tolerance, strict, _force_outplace, _module_class, _compilation_unit)
    957                 strict,
    958                 _force_outplace,
--> 959                 argument_names,
    960             )
    961             check_trace_method = module._c._get_method(method_name)

~/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
   1049         if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1050                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1051             return forward_call(*input, **kwargs)
   1052         # Do not call functions when jit is used
   1053         full_backward_hooks, non_full_backward_hooks = [], []

~/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/nn/modules/module.py in _slow_forward(self, *input, **kwargs)
   1037                 recording_scopes = False
   1038         try:
-> 1039             result = self.forward(*input, **kwargs)
   1040         finally:
   1041             if recording_scopes:

<ipython-input-6-6692427aa6bc> in forward(self, input_ids, attention_mask, encoder_outputs, index)
     48             decoder_causal_mask=causal_mask,
     49             return_dict=False,
---> 50             use_cache=False,
     51         )
     52 

~/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
   1049         if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1050                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1051             return forward_call(*input, **kwargs)
   1052         # Do not call functions when jit is used
   1053         full_backward_hooks, non_full_backward_hooks = [], []

~/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/nn/modules/module.py in _slow_forward(self, *input, **kwargs)
   1037                 recording_scopes = False
   1038         try:
-> 1039             result = self.forward(*input, **kwargs)
   1040         finally:
   1041             if recording_scopes:

TypeError: forward() got an unexpected keyword argument 'encoder_padding_mask'

**Comment by aws-joshim** [comment]
@DevBey can you check on the version of transformers used to trace the pegasus model?  the Error: TypeError: forward() got an unexpected keyword argument 'encoder_padding_mask' is likely due to a later version of transformers which is currently not supported for this model on Neuron. Note that our install dependencies are transformers==4.0.1
and torch-neuron==1.7.*

**Comment by DevBey** [comment]
Hi @aws-joshim ,

thanks for the help, we were able to trace the model. but it seems like as mentioned in https://github.com/aws/aws-neuron-sdk/issues/368..

the performance is very poor, and as mentioned as we can't have data-parallel then it's not really beneficial to deploy it on inferentia !!

Currently, it's deployed on g4dn instance, if there is any other better way of deploying it cost-wise and latency-wise, it would be really appreciated ??

otherwise, we can close this issue!!

**Comment by mrnikwaws** [comment]
Hi @DevBey,

At the moment our ability to accelerate generator style models is limited and only effective on short sequence lengths.  Please see the tracking issue for future improvements here:https://github.com/aws/aws-neuron-sdk/issues/370.  Closing this issue for now since at this time there is not a better answer.
