### ISSUE TITLE
YoloV5 neuron conversion

### ISSUE THREAD

**Issue by diazGT94** [aws/aws-neuron-sdk#372]
Until a couple of weeks ago I was able to use the following structure to convert my custom models to neuron

```
import torch.neuron

def subgraph_builder_function(node):
    return 'Detect' not in node.name

model = torch.hub.load('ultralytics/yolov5', 'custom', path='best.pt',force_reload=True) 
fake_image = torch.zeros([1, 3, 416, 416], dtype=torch.float32)  #Need to be equal to the input size of the image
try:
    torch.neuron.trace(model, example_inputs=[fake_image],subgraph_builder_function=subgraph_builder_function)
except Exception:
    torch.neuron.trace(model, example_inputs=[fake_image],subgraph_builder_function=subgraph_builder_function)

model_neuron = torch.neuron.trace(model, example_inputs=[fake_image],subgraph_builder_function=subgraph_builder_function)

model_neuron.save('neuron_model.pt')  
``` 

Today, I test the same approach but I couldn't succeed in converting the model. Therefore, I proceed to use the same code without passing the `subgraph_builder_function` argument to the function. However, this is giving me a terrible performance in the predicted results compared to using the other approach. 

Is this related to the fact I update my neuron tools to the latest version?

**Comment by aws-taylor** [comment]
Hello @diazGT94,

 Thank you for the report. We are investigating.

-Taylor

**Comment by diazGT94** [comment]
@aws-taylor Any updates on this?

**Comment by aws-taylor** [comment]
Hi @diazGT94,

 We've debugged the issue and identified that the yoloV5 authors changed the names of some of the tensors. As such, you'll need to update your code to the following (notice '#'):
 
 ```
 def subgraph_builder_function(node):
    return 'Detect#' not in node.name
```

Please let us know if you have any further questions.

-Taylor
