### ISSUE TITLE
Batch inference with TF 2.0 (pre trained model) using neuron sdk for vision model

### ISSUE THREAD

**Issue by subhamkhemka** [aws/aws-neuron-sdk#378]
Hi

I want to run batch inference using https://tfhub.dev/google/faster_rcnn/openimages_v4/inception_resnet_v2/1 pretrained model and my code is in tf 2.0.
I wasn't able to find an example or turorial for vision model with tf 2.0

Could you please help me with an example of how to do this with neuron on any of the inferentia instances ?

Regards,
Subham

**Comment by shebbur-aws** [comment]
Hi Subham,

Currently our support for TF2.0 is [limited to Bert-like models](https://awsdocs-neuron.readthedocs-hosted.com/en/latest/release-notes/neuron-cc.html?highlight=%22limited%20to%20Bert-like%22#known-issues-and-limitations-updated-10-27-2021). You can find further details about these here : [TF2.0 support](https://awsdocs-neuron.readthedocs-hosted.com/en/latest/neuron-guide/neuron-frameworks/tensorflow-neuron/tf2.html)

Thanks,
Shruthi.

**Comment by subhamkhemka** [comment]
okay thanks!
