### ISSUE TITLE
Question about auto partitioned model execution

### ISSUE THREAD

**Issue by Gabriel4256** [aws/aws-neuron-sdk#382]
Hi, team. 

I have a question about the way the model is executed when it is [auto-partitoned](https://awsdocs-neuron.readthedocs-hosted.com/en/latest/neuron-guide/models/models-inferentia.html#operator-coverage) during compilation time (due to unsupported operator(s)). In such cases, do Neuron compiler and runtime have functionality for running subgraphs executed on different processing unit (e.g., CPU, Inferentia) parallelly when it's possible?

For example, assume model M1 can be partitioned as below, where subgraph B1 and B2 has no dependency between them. Then, subgraph B1 and B2 can be executed in parallel, respectively on CPU and Inferentia. Do AWS Neuron's compiler and runtime support this?
```
         B1 (on CPU)
A ->                          -> C
         B2 (on Inferentia)
```

Thanks in advance.

**Comment by aws-joshim** [comment]
@Gabriel4256 We do not automatically execute partitioned subgraphs in parallel. Modules traced with `torch_neuron.trace` are converted to torchscript. The default behavior of the torchscript interpreter is to execute operations serially. For parallel execution of the subgraphs, currently you would need to manually partition your graph and add `torch.jit.fork`/`torch.jit.wait` calls to the graph. Reference documentation: https://pytorch.org/docs/stable/notes/cpu_threading_torchscript_inference.html

**Comment by Gabriel4256** [comment]
Ok, that's exactly what I want to know. Thanks!
