### ISSUE TITLE
Is it possible to run inference with CLIP (OpenAI) model ?

### ISSUE THREAD

**Issue by subhamkhemka** [aws/aws-neuron-sdk#386]
Hi

Is it possible to run inference with CLIP (OpenAI) model ?

Sample code from CLIP git repo which I need to run.

```
import torch
import clip
from PIL import Image

device = "cuda" if torch.cuda.is_available() else "cpu"
model, preprocess = clip.load("ViT-B/32", device=device)

image = preprocess(Image.open("CLIP.png")).unsqueeze(0).to(device)
text = clip.tokenize(["a diagram", "a dog", "a cat"]).to(device)

with torch.no_grad():
    image_features = model.encode_image(image)
    text_features = model.encode_text(text)
    
    logits_per_image, logits_per_text = model(image, text)
    probs = logits_per_image.softmax(dim=-1).cpu().numpy()

print("Label probs:", probs)  # prints: [[0.9927937  0.00421068 0.00299572]]

```

If CLIP is supported, could you please share an example to run batch inference on inf1.6xlarge ?

Thanks,
Subham

**Comment by aws-joshim** [comment]
@subhamkhemka we have not compiled and run the CLIP model on Inferentia. You can try to compile and trace the CLIP model using the torch-neuron APIs. For general guidance on compilation and inference for Pytorch models including different batch sizes, please refer to the tutorial at https://awsdocs-neuron.readthedocs-hosted.com/en/latest/src/examples/pytorch/resnet50.html
