### ISSUE TITLE
Cloudwatch monitor script is missing

### ISSUE THREAD

**Issue by TomasGajarsky** [aws/aws-neuron-sdk#387]
The script `neuron-monitor-cloudwatch.py` for linking neuron-monitor to Cloudwatch is missing in the [documentation](https://awsdocs-neuron.readthedocs-hosted.com/en/latest/neuron-guide/neuron-tools/neuron-monitor-user-guide.html#neuron-monitor-prometheuspy)

**Comment by aws-joshim** [comment]
@TomasGajarsky You can find the scripts under the Neuron Tools installation directory, once you’ve installed it. On a Ubuntu instance that path is /opt/aws/neuron/bin

**Comment by TomasGajarsky** [comment]
Thank you @aws-joshim, I found it there. It is just confusing that the file in the documentation is hyper linked, but it leads to nowhere.
