### ISSUE TITLE
Operators: add non-Max-suppression operator support

### ISSUE THREAD

**Issue by AWSGH** [aws/aws-neuron-sdk#39]

**Comment by nonatofabio** [comment]
For Non-MAX suppression operators we recommend leveraging [CPU optimized NMS ops](https://www.tensorflow.org/versions/r1.15/api_docs/python/tf/image/combined_non_max_suppression) for the best performance on inf1 instance. 

Check out our [YOLOv4 Tutorial](https://awsdocs-neuron.readthedocs-hosted.com/en/latest/neuron-guide/neuron-frameworks/tensorflow-neuron/tutorials/yolo_v4_demo/yolo_v4_demo.html#optimizing-image-pre-processing-and-post-processing-for-object-detection-models) for details on how to leverage it to perform bounding box post-processing on an object detection pipeline.
