### ISSUE TITLE
NLP Generative Models Greedy Search Optimisation

### ISSUE THREAD

**Issue by twolffpiggott** [aws/aws-neuron-sdk#391]
Hi there!

Thank you for a great open source library!

I'm looking at implementing Neuron optimisation of a [Transformers M2M100 model](https://huggingface.co/docs/transformers/model_doc/m2m_100). This is an NLP generative model, so linked to #370  

It's very similar to [MarianMT generation](https://awsdocs-neuron.readthedocs-hosted.com/en/latest/src/examples/pytorch/transformers-marianmt.html), but the M2M100 model was only introduced in Transformers v4.4.0, so unfortunately your `NeuronGeneration` class is out of sync with the Transformers internal API (since it's pinned to `transformers==4.0.1`).

For generation using this model, we don't need to use beam search, but use [greedy search](https://github.com/huggingface/transformers/blob/05fa1a7ac17bb7aa07b9e0c1e138ecb31a28bbfe/src/transformers/generation_utils.py#L1262) by default. I think this is a relatively common use case for generation.

Does supporting only greedy search (rather than beam search) simplify the process for Neuron optimization? If you can provide any high-level pointers it would be much appreciated!

I'm familiarising myself with the transformers [generation implementation](https://github.com/huggingface/transformers/blob/05fa1a7ac17bb7aa07b9e0c1e138ecb31a28bbfe/src/transformers/generation_utils.py#L355), but it has changed really significantly since the [reference example with Neuron](https://awsdocs-neuron.readthedocs-hosted.com/en/latest/src/examples/pytorch/transformers-marianmt.html).

**Comment by awsrjh** [comment]
thanks for the note (and for letting us know what is helpful too!)

we will take a look and get back to you.

**Comment by aws-zejdaj** [comment]
Hi Tim, We tried a public MarianMT Model, encountered an issue with low performance due to a Neuron compiler limitation in mapping to a mix of accelerated HW and CPU.
With the following additional compiler flag as a workaround the model ran an order of magnitude faster: --enable-replication=False. You can try the attached script or share with us your exact script
[391.txt](https://github.com/aws/aws-neuron-sdk/files/8020240/391.txt)
.

**Comment by twolffpiggott** [comment]
Thanks so much @aws-zejdaj ; keen to take a look into this for the `M2M100` model this week! Will post results

**Comment by twolffpiggott** [comment]
@aws-zejdaj I was able to successfully compile the M2M100 model using your updated `NeuronGeneration` class– thank you!

I've put together a minimal script comparing inference times between the compiled `NeuronGeneration` model and the original Transformers model.

Running this on an `inf1.6xlarge` I get an unexpected result: average inference time for a short sample text using the Neuron compiled model is roughly 6.2 seconds, while using the original Transformers model it is roughly .5 seconds. That is, the Neuron model seems to be an order of magnitude slower than the original model.

Please let me know if I'm missing something obvious here and should be setting additional flags? I'm using the same Neuron environment in which I compiled the model.

I looked into [NeuronCore Pipeline](https://awsdocs-neuron.readthedocs-hosted.com/en/latest/neuron-guide/technotes/neuroncore-pipeline.html) for performance optimisation, but the model has a very large number of parameters:

```
>>>sum(p.numel() for p in model.parameters())
486006784
```
Which means that it would need a prohibitively high number of Neuron cores for sharding (larger than an `inf1.24xlarge`):

```
>>>4 * round(486006784/(2 * 10**7) )
96
```

[test_inferentia.txt](https://github.com/aws/aws-neuron-sdk/files/8033158/test_inferentia.txt)

**Comment by aws-owinop** [comment]
Hi @twolffpiggott, 
We have analyzed the model performance and found that Neuron can perform significantly better with a small change to the decoder. During partitioning of the decoder execution graph the final matmul weights were partitioned off as a constant input. This means that the final model weights were passed as an input to the decoder for each inference. This is sometimes acceptable for small weights, but since the weights are very large in this model, this caused degraded performance. This can be preloaded on the Neuron hardware by detaching the weights in the `NeuronDecoder.` The compiler will be able to optimize the final matrix multiplication to be significantly faster than when the weights were passed as a parameter.
```
class NeuronDecoder(torch.nn.Module):

    def __init__(self, model, max_length):
        super().__init__()
        self.decoder = model.model.decoder
        self.weight = model.model.shared.weight.detach() # Detach the weights here
        self.max_length = max_length
```
We have also added (attached) a custom greedy decode loop example that will work with `transformers==4.15.*`
[greedy.txt](https://github.com/aws/aws-neuron-sdk/files/8074856/greedy.txt)

**Comment by twolffpiggott** [comment]
Sounds great, thanks @aws-owinop. It does seem like this model is significantly larger than typical Neuron use cases, so this makes sense as a gotcha. Really appreciate the help of the team in optimising this– I'm not familiar enough with the Neuron internals to have worked this out. Keen to test this!

**Comment by jeffhataws** [comment]
Hi @twolffpiggott, please reopen this case if you still have problems with it. Thanks!

**Comment by DevBey** [comment]
Hi @jeffhataws, 

I tried your greedy.txt script with following version 
```
print(transformers.__version__)4.6.0
print(torch.__version__)1.10.1+cu102
print(torch_neuron.__version__)1.10.1.2.1.7.0
```

but I got the following error
```
/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/transformers/models/m2m_100/modeling_m2m_100.py:173: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if max_pos > self.weights.size(0):
/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/transformers/models/m2m_100/modeling_m2m_100.py:283: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if attn_weights.size() != (bsz * self.num_heads, tgt_len, src_len):
/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/transformers/models/m2m_100/modeling_m2m_100.py:289: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if attention_mask.size() != (bsz, 1, tgt_len, src_len):
/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/transformers/models/m2m_100/modeling_m2m_100.py:320: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if attn_output.size() != (bsz * self.num_heads, tgt_len, self.head_dim):
INFO:Neuron:There are 1 ops of 1 different types in the TorchScript that are not compiled by neuron-cc: aten::embedding, (For more information see https://github.com/aws/aws-neuron-sdk/blob/master/release-notes/neuron-cc-ops/neuron-cc-ops-pytorch.md)
INFO:Neuron:Number of arithmetic operators (pre-compilation) before = 783, fused = 779, percent fused = 99.49%
WARNING:tensorflow:From /home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch_neuron/ops/aten.py:1982: where (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
Output exceeds the size limit. Open the full output data in a text editor
INFO:Neuron:Compiler args type is <class 'list'> value is ['--fp32-cast', 'matmult', '--fast-math', 'no-fast-relayout']
INFO:Neuron:Compiling function _NeuronGraph$381 with neuron-cc
INFO:Neuron:Compiling with command line: '/home/ubuntu/anaconda3/envs/pytorch_p36/bin/neuron-cc compile /tmp/tmpygbhhlc3/graph_def.pb --framework TENSORFLOW --pipeline compile SaveTemps --output /tmp/tmpygbhhlc3/graph_def.neff --io-config {"inputs": {"0:0": [[1, 32, 1024], "float32"], "1:0": [[1, 32], "int64"], "tensor.15:0": [[1, 32], "int64"]}, "outputs": ["batchnorm_24/add_1:0"]} --fp32-cast matmult --fast-math no-fast-relayout --verbose 35'
INFO:Neuron:Number of arithmetic operators (post-compilation) before = 783, compiled = 779, percent compiled = 99.49%
INFO:Neuron:The neuron partitioner created 1 sub-graphs
INFO:Neuron:Neuron successfully compiled 1 sub-graphs, Total fused subgraphs = 1, Percent of model sub-graphs successfully compiled = 100.0%
INFO:Neuron:Compiled these operators (and operator counts) to Neuron:
INFO:Neuron: => aten::Int: 221
INFO:Neuron: => aten::add: 39
INFO:Neuron: => aten::bmm: 24
INFO:Neuron: => aten::contiguous: 36
INFO:Neuron: => aten::cumsum: 1
INFO:Neuron: => aten::detach: 1
INFO:Neuron: => aten::dropout: 49
INFO:Neuron: => aten::expand: 1
INFO:Neuron: => aten::index_select: 1
INFO:Neuron: => aten::layer_norm: 25
INFO:Neuron: => aten::linear: 72
INFO:Neuron: => aten::masked_fill: 1
INFO:Neuron: => aten::mul: 38
INFO:Neuron: => aten::ne: 1
INFO:Neuron: => aten::relu: 12
INFO:Neuron: => aten::reshape: 12
INFO:Neuron: => aten::rsub: 1
INFO:Neuron: => aten::size: 52
...
INFO:Neuron:Number of arithmetic operators (pre-compilation) before = 1477, fused = 1473, percent fused = 99.73%
INFO:Neuron:Compiler args type is <class 'list'> value is ['--fp32-cast', 'matmult', '--fast-math', 'no-fast-relayout']
INFO:Neuron:Compiling function _NeuronGraph$981 with neuron-cc
INFO:Neuron:Compiling with command line: '/home/ubuntu/anaconda3/envs/pytorch_p36/bin/neuron-cc compile /tmp/tmpl5c8cejw/graph_def.pb --framework TENSORFLOW --pipeline compile SaveTemps --output /tmp/tmpl5c8cejw/graph_def.neff --io-config {"inputs": {"0:0": [[1, 32], "int64"], "tensor.3:0": [[], "int64"], "2:0": [[1, 32, 1024], "float32"], "tensor.23:0": [[1, 32], "int64"], "4:0": [[1, 32], "int64"], "5:0": [[1, 32, 1024], "float32"], "6:0": [[], "int64"]}, "outputs": ["Cast_10:0"]} --fp32-cast matmult --fast-math no-fast-relayout --verbose 35'
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-3-3134b07b3e05> in <module>
----> 1 infer()

<ipython-input-2-ebf61509e690> in infer()
      1 def infer():
----> 2     neuron_model = trace()
      3 
      4     # Generate example inputs
      5     tokenizer = M2M100Tokenizer.from_pretrained("facebook/m2m100_418M")

<ipython-input-1-d31dac739f3e> in trace(filename)
    105     model = M2M100ForConditionalGeneration.from_pretrained("facebook/m2m100_418M")
    106     neuron_model = NeuronGreedyGenerator(model)
--> 107     neuron_model.trace()
    108     neuron_model = torch.jit.script(neuron_model)
    109     torch.jit.save(neuron_model, filename)

<ipython-input-1-d31dac739f3e> in trace(self)
     79             torch.tensor(0),
     80         )
---> 81         self.decoder = torch_neuron.trace(self.decoder, inputs, compiler_args=compiler_args)
     82 
     83 

~/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch_neuron/convert.py in trace(func, example_inputs, fallback, op_whitelist, minimum_segment_size, subgraph_builder_function, subgraph_inputs_pruning, skip_compiler, debug_must_trace, allow_no_ops_on_neuron, compiler_workdir, dynamic_batch_size, compiler_timeout, _neuron_trace, compiler_args, optimizations, verbose, **kwargs)
    165     with skip_inference_context() as s:
    166         neuron_graph = cu.compile_fused_operators(neuron_graph, **compile_kwargs)
--> 167     cu.stats_post_compiler(neuron_graph)
    168 
    169     # Wrap the compiled version of the model in a script module. Note that this is

~/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch_neuron/convert.py in stats_post_compiler(self, neuron_graph)
    496         if succesful_compilations == 0 and not self.allow_no_ops_on_neuron:
    497             raise RuntimeError(
--> 498                 "No operations were successfully partitioned and compiled to neuron for this model - aborting trace!")
    499 
    500         if percent_operations_compiled < 50.0:

RuntimeError: No operations were successfully partitioned and compiled to neuron for this model - aborting trace!

```

**Comment by DevBey** [comment]
Hi @jeffhataws, 

was able to circumvent the issue, after downgrading transformers to 4.4, everything else remains same torch 1.10.1.

results for summarization model sshleifer/distilbart-cnn-12-6 is as follows ->
```
Throughput: 0.91/s
Samples: 100
Total Duration: 109.34s
Average Duration: 1.09s
Decoder Latency: 39.05ms
```

which is quite good and deployable rather than paying three times for a GPU for half the latency.
