### ISSUE TITLE
How to speed up inference time?

### ISSUE THREAD

**Issue by alejoGT1202** [aws/aws-neuron-sdk#393]
Hello,

I noticed that loading a model to a single core vs loading the model into multiple cores doesn't have an noticeable impact on inference time. I would like to know if there is an alternative to speed up the inference time. I'm not sure if batch inference would speed up inference time, if so is any available resource of how to do batch inference with TF1?  Thanks for the help

**Comment by aws-zejdaj** [comment]
hi @alejoGT1202 , Batching will help increase the number of inferences running at the same time, but will not decrease inference time. For yolov4 mentioned earlier the optimal batch for Neuron will depend on the image size and model details, eg for 608x608 it is 1 to 2, for 320x320 2 to 8. I suggest to start with the Neuron demo https://github.com/aws/aws-neuron-sdk/blob/master/src/examples/tensorflow/yolo_v4_demo/evaluate.ipynb and make sure you can reproduce the performance captured in https://awsdocs-neuron.readthedocs-hosted.com/en/latest/neuron-guide/benchmark/index.html#computer-vision
Then rerun with your model.
Also more information about Tensorflow batching is on https://awsdocs-neuron.readthedocs-hosted.com/en/latest/neuron-guide/technotes/neuroncore-batching.html?highlight=batching
Let us know how your run went.

**Comment by aws-owinop** [comment]
consolidating and merging this issue with #392
