### ISSUE TITLE
Neuron not found in Kubernetes deployment 

### ISSUE THREAD

**Issue by ndenStanford** [aws/aws-neuron-sdk#396]
Hello everyone, 

I am trying to deploy on my cluster on EKS (inf1.xlarge). However, Kubernetes could not locate the neuron driver and failed with an error message "1 Insufficient aws.amazon.com/neuron". Below is how I specified resources in the deployment file. 

resources:
        limits:
          aws.amazon.com/neuron: 1 

Is there anything I'm missing here? Any suggestion is greatly appreciated.

**Comment by aws-owinop** [comment]
Hi @ndenStanford, we need more details to assist you further. Kindly confirm if the neuron device plugin is setup and running [steps here](https://awsdocs-neuron.readthedocs-hosted.com/en/latest/neuron-deploy/tutorials/tutorial-k8s.html#tutorial-k8s-env-setup-for-neuron) and also confirm that your docker environment is setup in the host as per this [guide](https://awsdocs-neuron.readthedocs-hosted.com/en/latest/neuron-deploy/tutorials/tutorial-docker-env-setup.html).

**Comment by jeffhataws** [comment]
Hi @ndenStanford , just want to check if you still need more assistance after following the steps mentioned in @aws-owinop 's previous post.

**Comment by mrnikwaws** [comment]
Closing this ticket since we have not heard back from the customer
