### ISSUE TITLE
Models: deepen Neuron CV Object detection support (YOLO v3 YOLO v4)

### ISSUE THREAD

**Issue by AWSGH** [aws/aws-neuron-sdk#40]

**Comment by AWSGH** [comment]
faster-rcnn

**Comment by AWSGH** [comment]
SSD1200, YOLO, Mask-RCNN and Faster-RCNN

**Comment by aws-zejdaj** [comment]
Compilation of ssd1200 and yolo v3,4 is being tested, and preview with limited performance will be available in one of the next releases.

**Comment by AWSGH** [comment]
With Neuron 1.8.0 release, running YOLO v3 and YOLO v4 on Inf1 instances provides up to 1.85X higher throughput and 40% lower cost-per-inference compared to running the same models on the EC2 G4 GPU instances.
