### ISSUE TITLE
Yum fails to detect neuron packages on latest DLAMI

### ISSUE THREAD

**Issue by aws-anantsh** [aws/aws-neuron-sdk#400]
After setting up the neuron-repo, installing the yum package fails with no package available error for aws-neuron-dkms and tensorflow-model-server-neuron

```
sudo yum install aws-neuron-dkms                                                                                                                                                                                                     
No package aws-neuron-dkms available.
Error: Nothing to do
```

AMI Versions - 
Deep Learning AMI (Amazon Linux 2) Version 58.0
Deep Learning Base AMI (Amazon Linux 2) Version 50.0

**Comment by aws-maens** [comment]
Before installing/upgrading aws-neuron-dkms  on Amazon Linux DLAMI should unlock the package first:

sudo yum versionlock delete aws-neuron-dkms

Installation instructions will be updarted accordingly in the next Neuron release (1.18.0) .

**Comment by Mayurji** [comment]
@aws-maens I tried `sudo yum versionlock delete aws-neuron-dkms`,  but got an error has 'versionlock delete has no matches'
