### ISSUE TITLE
Is there anyway to load a model on a specific neuron core?

### ISSUE THREAD

**Issue by Udit1999** [aws/aws-neuron-sdk#407]

**Comment by Udit1999** [comment]
Hi @aws-taylor,

I have already used `NEURON_RT_VISIBLE_CORES`. It is good when we have multiple processes but if we have a single process that loads multiple models, this doesn't work well. All the models get loaded on the same core.
Is there anyway with which we can load model to different core within a same process just like `model.to(torch.device("cuda:0")` , `model.to(torch.device("cuda:1")` ?

**Comment by aws-taylor** [comment]
Hello @Udit1999,

 At this time there is no way to explicitly place models onto cores from within a given process. I have submitted a feature request to the appropriate team.
 
 Regards,
Taylor

**Comment by alejoGT1202** [comment]
Hello @Udit1999 I have been able to deploy two models in a single process using `NEURON_RT_VISIBLE_CORES` I created a function that loads the models like this: 

```
  def loadModel(model_type):
    if model_type == 'Model_A':
      os.environ['NEURON_RT_VISIBLE_CORES'] = '0,1'
      model_neuron = torch.jit.load('Model_A.pt')
      classes = ['Model_A_Classes']
    else:
      os.environ['NEURON_RT_VISIBLE_CORES'] = '2,3'
      model_neuron = torch.jit.load('Model_B.pt')
      classes = ['Model_B_Classes']
    return model_neuron, classes
```
And in my script i call the function first to load model A and later in the same script I called the function that loads model B. Dunno if this might help you.

**Comment by aws-joshim** [comment]
@alejoGT1202 closing this ticket since you were able to resolve this issue by the changes in the script that you outlined above. We will look into the feature request that you mention above - model.to with Neuron devices as a future looking roadmap item.
