### ISSUE TITLE
EKS deployment could not find neuron driver 

### ISSUE THREAD

**Issue by ndenStanford** [aws/aws-neuron-sdk#415]
Hello AWS team, 

I deployed my application on the inf.xlarge machine in the EKS cluster. I used torchserve as a framework and I have verified that the server was started correctly. However, I could not run prediction because the neuron driver cannot be found. This is the error message I am seeing. 

```
2022-04-02 18:19:58,646 [WARN ] MODEL_LOG - 2022-Apr-02 18:19:58.0646    28:28    ERROR   NRT:nrt_init                                Unable to read compatible Driver version.
2022-04-02 18:19:58,646 [WARN ] MODEL_LOG - 2022-Apr-02 18:19:58.0646    28:28    ERROR   NRT:nrt_init                                Please check /dev/neuron# is accessible. If you're using containers, please ensure Neuron Devices are passed to the container by specifying `--device /dev/neuron#`.
2022-04-02 18:19:58,649 [WARN ] MODEL_LOG - Warning: NEURONCORE_GROUP_SIZES is being deprecated. Please see Neuron documentation for more details. (initialize at /opt/workspace/KaenaPyTorchRuntime/neuron_op/runtime.cpp:173)
```

I have already installed necessary dependencies on the node. 

```
# Configure Linux for Neuron repository updates
sudo tee /etc/yum.repos.d/neuron.repo > /dev/null <<EOF
[neuron]
name=Neuron YUM Repository
baseurl=https://yum.repos.neuron.amazonaws.com
enabled=1
metadata_expire=0
EOF
sudo rpm --import https://yum.repos.neuron.amazonaws.com/GPG-PUB-KEY-AMAZON-AWS-NEURON.PUB

# Update OS packages
sudo yum update -y
# Install OS headers
sudo yum install kernel-devel-$(uname -r) kernel-headers-$(uname -r) -y
# Install Neuron Driver
sudo yum install aws-neuron-dkms -y
```

Oddly, this error only occurs in some pods within the cluster and I cannot explain why. Is there anything I'm missing or any test I can do to make sure that the neuron-rtd was set up correctly? 

I greatly appreciate any suggestions you may have.

**Comment by micwade-aws** [comment]
Hi @ndenStanford -- 

It's unusual for the driver to not come up if it's installed.  There's two possible scenarios that might explain the issue:
1. (unlikely) There was a problem communicating with the devices and the driver failed to initialize.
2. (more likely) the kernel was updated and the driver needs to be reinstalled to match the new running kernel.

Ideas to help you debug the issue:
* Ensure the neuron.ko (Neuron Driver) installed matches the currently running kernel: `find /usr/lib/modules/$(uname -r) -name neuron.ko`
  * If this returns nothing, then remove aws-neuron-dkms and follow the full install instructions again.
* Check that the driver is loaded: `lsmod | grep neuron`
* Not loaded?  Check for errors in /var/log/messages: `sudo grep neuron /var/log/messages*`

Please try the above and let us know.  If further debug is needed, please post the output of the above commands as well.  Thanks!

**Comment by ndenStanford** [comment]
I'm seeing the output below 

```
find /usr/lib/modules/$(uname -r) -name neuron.ko
/usr/lib/modules/4.14.198-152.320.amzn2.x86_64/kernel/drivers/neuron/neuron.ko

lsmod | grep neuron
neuron                155648  0
```

**Comment by micwade-aws** [comment]
You see that output on a working pod or a broken one?  If you don't mind, please email me at aws-neuron-support@amazon.com and we'll figure this out.  Also, if possible, please include an instance id for one of the failing inf1 instances.  Thanks!

**Comment by ndenStanford** [comment]
Just sent over the e-mail with the title "EKS deployment could not find neuron driver". Appreciate your help.

**Comment by micwade-aws** [comment]
Thanks for working with us @ndenStanford - closing this issue out.

Summary for readers of this thread was that we updated from an older version of k8 to k8 version 1.20, which resolved the issues.
