### ISSUE TITLE
Verifying if Prediction is not from CPU

### ISSUE THREAD

**Issue by ndenStanford** [aws/aws-neuron-sdk#416]
Is there a way to verify if the prediction was run on the neuron chip instead of a regular CPU? 

Any recommendation is greatly appreciated.

**Comment by micwade-aws** [comment]
There's more than a few.  The simplest way is to fire up [neuron-top](https://awsdocs-neuron.readthedocs-hosted.com/en/latest/neuron-guide/neuron-tools/neuron-top-user-guide.html) and watch for your model to load and execute on the Neuron Cores.  There's a script we provide to [check models](https://awsdocs-neuron.readthedocs-hosted.com/en/latest/neuron-guide/neuron-tools/tutorial-neuron-check-model.html) in advance to execution for Neuron supported operations.  If your curious about monitoring and checking on execution of a fleet of machines, [neuron-monitor](https://awsdocs-neuron.readthedocs-hosted.com/en/latest/neuron-guide/neuron-tools/neuron-monitor-user-guide.html) might be a better fit.

**Comment by ndenStanford** [comment]
I'm seeing that it's possible to connect neuron-monitor with cloudwatch. If I'm working with docker, should this be executed inside the container every time the container is spun up? Thanks

```
neuron-monitor | neuron-monitor-cloudwatch.py --namespace <namespace> --region <region>
```

**Comment by aws-joshim** [comment]
@ndenStanford that is correct. You would need to execute the neuron-monitor script when the container is spun up. Another option would be to create a sidecar docker container that runs the neuron monitor script alongside the main container. 
Here's a link to docker's official documentation for how to run background processes - https://docs.docker.com/config/containers/multi-service_container/

**Comment by hannanjgaws** [comment]
Hi @ndenStanford,

We will close this ticket because the above should enable you to use neuron-monitor in your application. Please open a new ticket if you run into any other issues.
