### ISSUE TITLE
running the bert_demo case in Docker has core dump issue 

### ISSUE THREAD

**Issue by paladin2000cn** [aws/aws-neuron-sdk#418]
try to migration bert_demo case into docker env and make sure the same software stack as old one (as old AMI-028dbc12531690cf4 Deep Learning AMI (Ubuntu 18.04) ) is not available.     main software we used on docker "aws-neuron-tools-1.6.1.0 aws-neuron-runtime-1.5.0.0 aws-neuron-dkms-2.1.5.0 aws-neuron-runtime-base-1.5.1.0"
but we meet this issue that needed stop service neuron-rtd on host and running neuron-rtd service in container instance.
but when we used software on docker as (aws-neuron-tools-2.0.790.0 aws-neuron-runtime-1.6.21.0 aws-neuron-dkms2.2.14.0 aws-neuron-runtime-base-1.6.24.0),  no need top service neuron-rtd on host and running neuron-rtd service in container instance.

More when running as python3 bert_server.py --dir bert-saved-model-neuron-final-cmpbs2-core2 --batch 8  --parallel 8 --thread 8 --bootstrap --core 2   ; core dump with "bus error" raised

![image](https://user-images.githubusercontent.com/12146532/162672349-77cb5ce0-2759-4306-a358-11d70f554de7.png)

**Comment by aws-joshim** [comment]
@paladin2000cn, can you confirm if you are manually starting neuron-rtd in the docker setup where you see the coredump? Also, would you consider updating to the latest version of the Neuron release? Please note that the latest Neuron runtime does not require the neuron rtd daemon – details are at https://awsdocs-neuron.readthedocs-hosted.com/en/latest/neuron-guide/appnotes/neuron-components/introducing-libnrt.html. Install steps to update to the latest Neuron release are at https://awsdocs-neuron.readthedocs-hosted.com/en/latest/neuron-intro/tensorflow-setup/tensorflow-install.html#install-neuron-tensorflow.  If you would like to continue to use the older versions of the packages, please make sure that the correct packages listed under Neuron 1.15.2 at https://awsdocs-neuron.readthedocs-hosted.com/en/latest/release-notes/neuronrelease/previous-content.html#pre-release-content are installed in the docker container

**Comment by hannanjgaws** [comment]
Hi @paladin2000cn,

Are you still seeing the coredump issue after manually restarting neuron-rtd or upgrading to the newest Neuron release?

**Comment by aws-mvaria** [comment]
Hi @paladin2000cn , 

We are closing the ticket as we have not heard back, but please reopen if you are still seeing the issue.
