### ISSUE TITLE
ONNX Graph Support

### ISSUE THREAD

**Issue by codertimo** [aws/aws-neuron-sdk#423]
It would be great to support the compile ONNX graph to neuron sdk.
Then doesnt have to make lot's of neuron sdk compiler for each framework (tf, torch, Jax etc)
Just build the model to ONNX graph with in-framework fuctions (torch.onnx, tf onnx) and transfer to neuron-sdk easily!!

**Comment by samskalicky** [comment]
Hi @codertimo, do you have an onnx model you would like to try compiling with Neuron? One option would be to [import the onnx model into MXNet](https://mxnet.apache.org/versions/1.8.0/api/python/docs/api/contrib/onnx/index.html#mxnet.contrib.onnx.import_model) like:
```
sym, arg, aux = mx.contrib.onnx.import_model(onnx_model_file)
```

heres an example:
https://mxnet.apache.org/versions/1.7/api/python/docs/tutorials/packages/onnx/super_resolution.html

**Comment by jeffhataws** [comment]
Hi @codertimo, thanks for filing the issue. Aside from the potential solution shown above, as of 11/17/2020, [ONNX support is also end-of-life](https://awsdocs-neuron.readthedocs-hosted.com/en/latest/release-notes/deprecation.html?highlight=ONNX#end-of-support-for-onnx). We recommend running models in TensorFlow, PyTorch or MXNet for best performance and support. Let us know if you have further issues.
