### ISSUE TITLE
aws-neuron-dkms package docker container

### ISSUE THREAD

**Issue by alejoGT1202** [aws/aws-neuron-sdk#425]
I've  a container that uses torch-neuron and it runs as it should be inside my cluster. I used the example from [here ](https://awsdocs-neuron.readthedocs-hosted.com/en/latest/neuron-deploy/docker-example/v1/Dockerfile-app-rt-diff.html?highlight=docker%20tensorflow) to create my `Dockerfile`

I used the same one to create a container that uses `tensorflow-neuron==1.15.5.*` and run it in a new cluster but when it tries to load the model to the chip I get the following error: 
` Unable to determine Neuron Driver version. Please check aws-neuron-dkms package is installed`.  I check the solution explained [here](https://github.com/aws/aws-neuron-sdk/issues/353) but I can't access to my host instance because it's controlled by k8s. What should I do to overcome this issue?

**Comment by hannanjgaws** [comment]
Hi @alejoGT1202,

If your nodes are not configured from the beginning to allow ssh or ssm access, one idea might be to launch the same ami on an inf1 outside of the cluster to check.  Going forward though, you'll want to configure to either collect syslogs from nodes or enable remote access via ssm (preferably) or ssh.  If you used eksctl to setup your cluster, ssm access is enabled by default.  In case it helps, here's the relevant eksctl documentation on ssh/ssm: https://eksctl.io/introduction/#ssh-access.

**Comment by alejoGT1202** [comment]
Hi,

I think the issue is caused because I create my nodes using the AWS console where I selected the wrong AMI the new nodes are using  `amazon-eks-node` AMI and I think they should use `amazon-eks-gpu-node`. However, I notice that it's not possible to select this AMI using the console. Guess I should create the node group again using the `kubectl` command so the correct AMI is assigned to my `inf1` nodes right?

**Comment by hannanjgaws** [comment]
Hi @alejoGT1202,

You're most likely correct.  When creating the cluster+nodegroup using eksctl, it will pick an optimized AMI from EKS for inf1.  We'll double check the console to make sure there's not a bug/optimization to be made there for inf1 managed node groups.

In the meantime, yes, you'll want to create a node group using an AMI that includes the driver.  EKS recommends using one of these AMIs under the "x86 acelerated" category: https://docs.aws.amazon.com/eks/latest/userguide/eks-optimized-ami.html

**Comment by alejoGT1202** [comment]
Hello @hannanjgaws  

I was able to create the node group with the correct AMI.

I checked that the pod `neuron-device-plugin-daemonset` was running correctly and it's running as expected.

However when I'm running my pod I get the following error: 

```
2022-May-11 15:18:49.0703     1:37    ERROR   NRT:nrt_init                                Unable to read compatible Driver version.
2022-May-11 15:18:49.0703     1:37    ERROR   NRT:nrt_init                                Please check /dev/neuron# is accessible. If you're using containers, please ensure Neuron Devices are passed to the container by specifying `--device /dev/neuron#`.

```

Thanks for the help.

**Comment by awsilya** [comment]
Hi, looks like the issue was traced to not having the right AMI and resolved.  Could we close this ticket?  Thank you.

**Comment by alejoGT1202** [comment]
Yes, the issue was resolved by assigning the correct AMI
