### ISSUE TITLE
Dynamic Input Size

### ISSUE THREAD

**Issue by yangyang-nus-lv** [aws/aws-neuron-sdk#427]
Hi team, does torch-neuron support exporting models with dynamic input size? And can the traced model accept input with dynamic size when inference? For example, the shape of an input image is dynamic if either width and height is arbitrary. As far as I know, torch script model can. Also I saw the example for dynamic batchsize. is it the same way to handle dynamic sizes? Thanks in advance. I haven't got the chance to use inferentia yet, if the dynamic input is supported that would be great.

**Comment by aws-mvaria** [comment]
Hi @yangyang-nus-lv,

Neuron requires the input size shape to be fixed at compile time. If the shapes of your input images are dynamic (arbitrary width or height as per your comment), we recommend using padding to pad the images up to a fixed size. Additionally, for some applications we recommend using bucketing techniques (see https://awsdocs-neuron.readthedocs-hosted.com/en/latest/neuron-guide/appnotes/perf/bucketing-app-note.html#bucketing-app-note) to optimize compute utilization, particularly when many of the input sizes in your dataset are smaller than the largest input size.

As you have noted, Neuron supports dynamic-batching (see https://awsdocs-neuron.readthedocs-hosted.com/en/latest/neuron-guide/technotes/neuroncore-batching.html#neuron-batching). This is applicable only to the batch dimension of the input tensor.

Thanks!

**Comment by fabiozappo** [comment]
Hello, will torch-neuron support dynamic input sizes in the future?
