### ISSUE TITLE
[NRTD:infer_wait] error: 1004

### ISSUE THREAD

**Issue by JunxiChhen** [aws/aws-neuron-sdk#429]
Hi,

I am running infer_resnet50_keras_loadtest.py. And some of the parameter combinations run with below issue: 

1: 2022-05-26 01:44:11.574098: E tensorflow/neuron/runtime/model.cc:706] shard error code 13, error message nrt::infer_wait failed with grpc status code 0, error message ""; nrt status code 1004, details "[NMGR:exec_wait] Inference completed with err: 1004
1: [NRTD:infer_wait] error: 1004
1: "
1: 2022-05-26 01:44:11.578292: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at neuron_op.cc:28 : Internal: nrt::infer_wait failed with grpc status code 0, error message ""; nrt status code 1004, details "[NMGR:exec_wait] Inference completed with err: 1004
1: [NRTD:infer_wait] error: 1004
1: "
1: 2022-05-26 01:44:18.951891: E tensorflow/neuron/runtime/model.cc:706] shard error code 13, error message nrt::infer_wait failed with grpc status code 0, error message ""; nrt status code 1004, details "[NMGR:exec_wait] Inference completed with err: 1004
1: [NRTD:infer_wait] error: 1004
1: "
1: 2022-05-26 01:44:18.955906: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at neuron_op.cc:28 : Internal: nrt::infer_wait failed with grpc status code 0, error message ""; nrt status code 1004, details "[NMGR:exec_wait] Inference completed with err: 1004
1: [NRTD:infer_wait] error: 1004

**Comment by JunxiChhen** [comment]
Specially use related large number of "loop".

**Comment by aws-owinop** [comment]
Hi @JunxiChhen,
The 1004 indicates an error during inference. We will need the syslog of the system (if possible), the EC2 instance id, and the failing input parameters to investigate further. We also noticed you are using gRPC-based Neuron runtime, we suggest you upgrade to the [direct-link runtime](https://awsdocs-neuron.readthedocs-hosted.com/en/latest/neuron-guide/appnotes/neuron-components/introducing-libnrt.html?highlight=library%20mode )

**Comment by JunxiChhen** [comment]
Thanks for your respond!

Instance type: inf1.6xlarge

Parameters: 
    batch size for compile: 7
    user batch size: 21
    loops: 1000
    neuroncore per instance: 4

Pls. attach the failed log:
[log.txt](https://github.com/aws/aws-neuron-sdk/files/8783348/log.txt)

**Comment by JunxiChhen** [comment]
BTW, I've already used the latest neuron runtime version

**Comment by aws-owinop** [comment]
Hi @JunxiChhen,
We are unable to reproduce your issue using your configuration with the latest tensorflow-neuron. The logs you have provided indicate an older version of tensorflow-neuron. Follow the instructions [here](https://awsdocs-neuron.readthedocs-hosted.com/en/latest/neuron-intro/tensorflow-setup/tensorflow-update.html) to upgrade to the latest tensorflow-neuron.
If you still see the error, send us an email with the EC2 instance id to aws-neuron-support@amazon.com

**Comment by hannanjgaws** [comment]
Hi @JunxiChhen,

We are closing the ticket because have not heard back from you. Please re-open this issue if you need further assistance.
