### ISSUE TITLE
Detectron2 instance segmentation model for Inferentia

### ISSUE THREAD

**Issue by qritive-ola** [aws/aws-neuron-sdk#430]
Hello, 

I have been unable to convert the instance segmentation model to inferentia.

**Comment by mrnikwaws** [comment]
Hi @qritive-ola,

We'll need some more information to try and reproduce your issue.  Can you please share sample code for failure? Versions that you used in your testing (pip list or similar) are also helpful.

**Comment by hannanjgaws** [comment]
Hi @qritive-ola, Detectron2 is based on the Mask RCNN model family. We are planning to provide guidance on running RCNNs on Inf1 using Neuron. You can track the progress of this effort under roadmap item https://github.com/aws/aws-neuron-sdk/issues/153.

**Comment by jluntamazon** [comment]
Hello @TZeng20,
Support is still very limited but it is possible to accelerate portions of these types of models.

Please use the roadmap item to track the progress on RCNN models: https://github.com/aws/aws-neuron-sdk/issues/153

I am closing this issue in favor of the roadmap item.
