### ISSUE TITLE
Profiling Unknown framework used

### ISSUE THREAD

**Issue by alejoGT1202** [aws/aws-neuron-sdk#433]
I'm trying to Profile a yoloR converted to Pytorch Neuron. Followed the steps specified [here](https://awsdocs-neuron.readthedocs-hosted.com/en/latest/neuron-guide/neuron-tools/getting-started-tensorboard-neuron-plugin.html#enable-profiling). I'm able to see that the `.ntff`, `.pb` and `.neff` files where after running the inference on a single image. 

When I connect to the localhost I can't see the operators in the graph and just display the following graph

![image](https://user-images.githubusercontent.com/99010562/174013711-32827cbe-56d1-460e-b07d-69080364af74.png)

Also on the terminal where tensorboard is running I get the following message: 

``` Running neuron-profile
TensorBoard 1.15.0 at http://ip-172-31-16-203:6006/ (Press CTRL+C to quit)
W0616 07:14:16.198482 140492762142464 neuron_plugin.py:289] Unknown framework used - defaulting to TensorFlow supported ops
``` 

Should I update TensorBoard and/or the plugin to see the results? 

Thanks for the help!

**Comment by jeffhataws** [comment]
We will take a look. To help us further, please provide versions of the Neuron packages. 

pip list | grep neuron
yum list | grep neuron # on AL2
apt list | grep neuron # on ubuntu

If you have the DLAMI version that would also help. 

Thanks.

**Comment by jeffhataws** [comment]
Hi alejoGT1202. Thanks for filing the issue. As noted in the [overview for TensorBoard Neuron](https://awsdocs-neuron.readthedocs-hosted.com/en/latest/neuron-guide/neuron-tools/getting-started-tensorboard-neuron-plugin.html#overview), graph visualization is currently only supported for TensorFlow-Neuron. Support for PyTorch-Neuron visualization will be added in a future release.

**Comment by aws-joshim** [comment]
@alejoGT1202, please let us know if we can be of any further help for this issue before closing the ticket
