### ISSUE TITLE
Cant trace Detectron2 segmentation on inferentia!

### ISSUE THREAD

**Issue by jaswanth-tango** [aws/aws-neuron-sdk#438]
Not able to trace the model on inferentia machine for Detectron2 Instance Segmentation. Am i missing something or there is a whole different method to do the same.

![inferentia_trace_error_detectron2](https://user-images.githubusercontent.com/84085435/177085710-52a33730-a363-41d2-8aac-ecfb45b68c9b.png)

**Comment by jluntamazon** [comment]
I am closing this issue in favor of the roadmap item: https://github.com/aws/aws-neuron-sdk/issues/153
