### ISSUE TITLE
neuron-ls: command not found

### ISSUE THREAD

**Issue by Mayurji** [aws/aws-neuron-sdk#447]
I am currently running a MaskRCNN model from detection2 in Inf1.2xlarge instance. I've checked the list of the python packages installed, I see neuron is installed, tried reinstalling aws-neuron-tools and other dependency as well. But still I keep getting error like

neuron-ls command not found
neuron-top command not found
neuron-monitor command not found.

What am I missing?

**Comment by micwade-aws** [comment]
@Mayurji - append the path of the Neuron Tools to your environment $PATH variable if you want to call the tools without a full path.

See the export line below, taken from the [install guide](https://awsdocs-neuron.readthedocs-hosted.com/en/latest/neuron-intro/pytorch-setup/pytorch-install.html#install-neuron-pytorch).
```
# Install Neuron Tools
sudo apt-get install aws-neuron-tools -y
export PATH=/opt/aws/neuron/bin:$PATH
```

**Comment by Mayurji** [comment]
@micwade-aws It worked. Thank you.
