### ISSUE TITLE
optimize torchscript traced model

### ISSUE THREAD

**Issue by pconway11** [aws/aws-neuron-sdk#451]
I am trying to run detectron 2 on aws, with aws-neuron

I already have a traced torchscript model which can be loaded with torch.jit.

can this model be optimized for torch neuron instead of the original pytorch model?

calling torch.neuron.trace on the torchscript trace model , gives a warning that the model is already scripted, then throws an error on optimize as the graph is None

I've tried updating torch.neuron.save to use my traced model

when it gets to resolve_call_function

WARNING:Neuron:resolve_call_function cannot find TorchScript "_batched_nms_coordinate_trick" for operator <Operation RPN#51/prim::CallFunction#693>

https://github.com/pytorch/vision/blob/3db30442a52e250c569ba131485fc432c8300f16/torchvision/ops/boxes.py#L79

**Comment by jluntamazon** [comment]
Compilation for detectron2 is known to be problematic on Neuron. However, this is an error that we have not encountered before. Would you be able to provide your compilation script and the specific model configurations you were using so that we can reproduce this error?

We have a roadmap item to add support for this class of models since they are currently known to fail compilation.  You can track the progress of this effort under roadmap item [#153](https://github.com/aws/aws-neuron-sdk/issues/153).

**Comment by pconway11** [comment]
I had already used the export tool on detectron to export a traced model

https://github.com/facebookresearch/detectron2/blob/main/tools/deploy/export_model.py

so for neuron.trace I edited the code to use the model passed in as the traced model and remove the call to torch.jit.trace

this gave errors where the code tried to use model.original_name
or model.name as those attributes didnt exist.

So I just used the string “detectron” in the calls to Graph constructor

_batched_nms_coordinate_trick is relatively recent addition to the torchvision code

I was wondering if the neuron libraries /compiler just needed to be rebuilt with the latest version of torch / torchvision?

so my compilation script is basically just 
model=torch.script.load(‘my_ts_model.ts’)
neuron_model = torch.neuron.trace(model)

with the edits to torch.neuron.trace outlined above

**Comment by aws-taylor** [comment]
Hello @pconway11,

  Can we request that you provide a complete list of commands and/or self-contained script that we can use to reproduce your issue? There are many variations of detectron2 and datasets available, and without more information it is difficult for us to diagnose your problem.
  
  -Taylor
