### ISSUE TITLE
Install guidelines for DLAMI(s) missing ?

### ISSUE THREAD

**Issue by Othmane796** [aws/aws-neuron-sdk#452]
Hi,

I believe there is some steps missing in the install guidelines followed the guidelines [here](https://awsdocs-neuron.readthedocs-hosted.com/en/latest/neuron-intro/tensorflow-setup/tensorflow-install.html) to install Neuron Tensorflow.

Infrastructure : 
EC2 Instance: inf1.xlarge
AMI Name:  Deep Learning AMI GPU TensorFlow 2.8.2 (Ubuntu 20.04) 20220720
AMI ID:  ami-0868cb576a728c9aa

Following install guide under "Tensorflow 2.8.0" and "Ubuntu DLAMI" [here ](https://awsdocs-neuron.readthedocs-hosted.com/en/latest/neuron-intro/tensorflow-setup/tensorflow-install.html)(screenshot)
<img width="1000" alt="Screen Shot 2022-07-21 at 10 38 15" src="https://user-images.githubusercontent.com/8608330/180169887-c0149ce4-2e5c-49c3-8098-eba6ebbaa8e2.png">

When running the following command : 
`$ sudo apt-get install aws-neuron-dkms --allow-change-held-packages -y
`
I get the following error : 
`E: Unable to locate package aws-neuron-dkms
`
I ended up fixing this by running the first  command lines under "Tensorflow 2.8.0"/"Ubuntu AMI": 

```
# Configure Linux for Neuron repository updates
. /etc/os-release
sudo tee /etc/apt/sources.list.d/neuron.list > /dev/null <<EOF
deb https://apt.repos.neuron.amazonaws.com ${VERSION_CODENAME} main
EOF
wget -qO - https://apt.repos.neuron.amazonaws.com/GPG-PUB-KEY-AMAZON-AWS-NEURON.PUB | sudo apt-key add -

```

Is this the expected behavior and just the install guideline should be updated or I'm doing something wrong?

Othmane,

**Comment by awsilya** [comment]
Hi Othmane,

thank you for bringing this to our attention.  You did the right thing, nothing to worry about.  I think the expectation was that Neuron apt source was preconfigured on DLAMI.  I'll check why this is not the case.

**Comment by awsilya** [comment]
Also, did not notice that originally:

This: 

AMI Name: Deep Learning AMI GPU TensorFlow 2.8.2 (Ubuntu 20.04) 20220720

Is a GPU AMI and does not support Neuron by default (see https://docs.aws.amazon.com/dlami/latest/devguide/appendix-ami-release-notes.html#appendix-ami-release-notes-gpu )
Neuron is supported by default in Ubuntu 18.04 DLAMI and Amazon Linux 2 DLAMI
