### ISSUE TITLE
No Package aws-neuron-dkms available 

### ISSUE THREAD

**Issue by Mayurji** [aws/aws-neuron-sdk#479]
Started a Amazon Linux DLAMI with pytorch 1.9.1 and followed the steps to install the torch neuron using this URL

https://awsdocs-neuron.readthedocs-hosted.com/en/latest/neuron-intro/pytorch-setup/pytorch-install.html

While performing these steps:
`# Install Neuron Driver`
`sudo yum versionlock delete aws-neuron-dkms`
`sudo yum install aws-neuron-dkms -y`

First error we got was for yum verisionlock as follows
`versionlock delete has no matches`

Next tried installing the package
`no package aws-neuron-dkms available`

Checked this existing issue: https://github.com/aws/aws-neuron-sdk/issues/400 but it didn't work.

**Comment by micwade-aws** [comment]
@Mayurji - Please double check that you're using a DLAMI that supports inf1.  The DLAMIs that do support inf1 will come with a version of the Neuron driver pre-installed.  You can check in the DLAMI Catalog (link below) or with a specific command to query for the latest ami id from a region (same link).  

DLAMI Catalog: https://aws.amazon.com/releasenotes/aws-deep-learning-ami-catalog/
Latest AL2 DLAMI supporting Inf1 is version 65 of https://aws.amazon.com/releasenotes/aws-deep-learning-ami-amazon-linux-2/

If you confirm that you're running a DLAMI that supports inf1, please post the exact AMI version and ami-id for us to reproduce the problem.

**Comment by Mayurji** [comment]
We used the following ami-id `ami-090f33f325bfb2483`

**Comment by micwade-aws** [comment]
ami-090f33f325bfb2483 == Deep Learning AMI GPU PyTorch 1.9.1 (Amazon Linux 2) 20220316

That's not an AMI built to support inf1.  If you want the convenience of pre-installed software for inf1, I would suggest using the latest Multi-framework AMI from DLAMI: http://aws.amazon.com/releasenotes/aws-deep-learning-ami-amazon-linux-2

If you simply want to push latest Neuron into the AMI you have, or any AmazonLinux2/Ubuntu AMI, start with our install guide: https://awsdocs-neuron.readthedocs-hosted.com/en/latest/neuron-intro/pytorch-setup/pytorch-install.html. There's a tab for torch 1.9 in the guide.

**Comment by Mayurji** [comment]
@micwade-aws But we should be able to install Neuron Driver in the AMI ami-090f33f325bfb2483 == Deep Learning AMI GPU PyTorch 1.9.1 (Amazon Linux 2) 20220316?

**Comment by micwade-aws** [comment]
If you follow the install link I provided and pick the Torch 1.9.1 + Amazon Linux AMI tabs, you'll find instructions to install Neuron Driver and all of the Neuron SDK into an Amazon Linux 2 based AMI.  

Please note though, ami-090f33f325bfb2483 is not missing _just_ the Neuron Driver, but rather the entire Neuron SDK.  Modifying it to support Neuron/inf1 is going to be similar to modifying a non-DLAMI AL2 image.

**Comment by Mayurji** [comment]
I have multiple instances under AMI (ami-090f33f325bfb2483) using inf1.2xlarge & inf1.6xlarge running, where we installed all packages as mentioned in the link you've shared for PyTorch 1.9.1, the problem is occurring in the last few days, if we start any new instance with this AMI ID we are unable to install any of the packages as mentioned in the link.

**Comment by micwade-aws** [comment]
What do you get as output for `yum repolist all`?

**Comment by micwade-aws** [comment]
*on the broken one, not one of the working ones that is.

**Comment by Mayurji** [comment]
We see a bunch of yum repos related to amzn and nvidia.

![IMG_20220826_230751](https://user-images.githubusercontent.com/10477789/186961413-f5f217a9-14ab-448e-8403-a2e042eb76b9.jpg)

**Comment by micwade-aws** [comment]
Makes sense.  The AMI does not have the Neuron yum repo on it.  The first step in the install instructions under the torch 1.9+AL2 tabs will be to put the Neuron yum repo in place like this:

```
# Configure Linux for Neuron repository updates
sudo tee /etc/yum.repos.d/neuron.repo > /dev/null <<EOF
[neuron]
name=Neuron YUM Repository
baseurl=https://yum.repos.neuron.amazonaws.com
enabled=1
metadata_expire=0
EOF
sudo rpm --import https://yum.repos.neuron.amazonaws.com/GPG-PUB-KEY-AMAZON-AWS-NEURON.PUB
```

After that command, you'll run `sudo yum update`, then install the driver, and so on.  But the Neuron repo needs to be configured so yum will find the Neuron Driver package and many others.

**Comment by micwade-aws** [comment]
Might be a lot easier to use the Multi-framework AMI from the DLAMI catalog that supports p4, g4, and inf1 with many ML frameworks: https://aws.amazon.com/releasenotes/aws-deep-learning-ami-catalog/

**Comment by micwade-aws** [comment]
Please re-open if more help is needed.
