### ISSUE TITLE
"/dev/neuron0": no such file or directory

### ISSUE THREAD

**Issue by Mayurji** [aws/aws-neuron-sdk#482]
Hi Team, we are trying to perform inference using AWS Neuron while running it as a docker service.  After the docker build is complete, we run the docker image as a container as follows:

`docker run -v '/local_model_path/':'/app/server/models' -d --name fastapi-inf-container --device=/dev/neuron0 -p 8080:8080 fastapi-inf`

We receive an error as follows

`Error response from daemon: error gathering device information while adding custom device "/dev/neuron0": no such file or directory`

**Comment by Mayurji** [comment]
We used an instance that comes with Neuron SDK by default. Will cross with the command.

![image](https://user-images.githubusercontent.com/10477789/186956193-1dfc14d3-a219-4c32-a6d1-11ca3d34fe41.png)

**Comment by Mayurji** [comment]
@RobinFrcd Unable to do `ls /dev/neuron*`, as mentioned it throws no file or directory.

**Comment by RobinFrcd** [comment]
Do you know exactly was EC2 instance type you're using ?

**Comment by Mayurji** [comment]
this is the instance we are Inf1.2xlarge under that AMI ID, does this answer your question?

**Comment by RobinFrcd** [comment]
I've personally only used ECS images (see [here](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-inference.html)), maybe you can try with one of them and see if it works ? (I'm running `ami-0c2cf03c1c3ed59db` right now, which works perfectly).

**Comment by micwade-aws** [comment]
Hi @Mayurji - it's unclear why you're getting the error.  Suggest a couple quick sanity checks:

1. From the host OS (not in the container), make sure you see the Neuron Devices:
```
> ls /dev/neuron*

/dev/neuron0
```

2. If that worked, then fire up a generic container for testing to see if you can see Neuron Devices in that container:
```
# This will download a tiny linux container, mount /dev/neuron0, and wait.
> docker run --device=/dev/neuron0 -d --name checking4neuron alpine watch "date >> /var/log/date.log"
> docker exec checking4neuron ls /dev/neuron*

/dev/neuron0
```

If either of the above failed, please post the output from these commands (executed from the host OS of the failing instance) to help identify other possible issues:

```
> curl http://169.254.169.254/latest/meta-data/instance-id
> ls /dev/
> yum list installed | grep neuron
> lsmod | grep neuron
> uname -r
> ls /lib/modules/
> ls /lib/modules/$(uname -r)/kernel/drivers
> docker info
```

**Comment by Mayurji** [comment]
Neuron devices are visible, without any installation of neuron drivers on AMI ID as mentioned above.
