### ISSUE TITLE
No package tensorflow-model-server-neuron available.

### ISSUE THREAD

**Issue by haitong** [aws/aws-neuron-sdk#483]
I tried to run the docker file here 
https://github.com/aws/aws-neuron-sdk/blob/860896cf734d999f1a37ae2edb84ad0149274060/neuron-deploy/docker-example/Dockerfile.tf-serving
with `docker build . -f Dockerfile.tf-serving -t tensorflow-model-server-neuron`

but hit 
"""
No package tensorflow-model-server-neuron available.
"""

Any ideas?

**Comment by kct22aws** [comment]
Hello, it looks like you don't have `tensorflow-model-server-neuron` installed in your environment. You may try either command below: 

```
# Set Pip repository  to point to the Neuron repository
pip config set global.extra-index-url https://pip.repos.neuron.amazonaws.com

#Install Neuron TensorFlow
pip install tensorflow-neuron[cc] "protobuf<4"

# Optional: Install Neuron TensorFlow model server
sudo yum install tensorflow-model-server-neuron -y
```
or 
``` 
# Set Pip repository  to point to the Neuron repository
pip config set global.extra-index-url https://pip.repos.neuron.amazonaws.com

#Install Neuron TensorFlow
pip install tensorflow-neuron[cc] "protobuf<4"

# Optional: Install Neuron TensorFlow model server
sudo apt-get install tensorflow-model-server-neuron --allow-change-held-packages -y
```

These are from our Neuron SDK's Tensorflow fresh installation instruction [here](https://awsdocs-neuron.readthedocs-hosted.com/en/latest/neuron-intro/tensorflow-setup/tensorflow-install.html#develop-on-aws-ml-accelerator-instance ).

**Comment by haitong** [comment]
@kct22aws Thanks for the reply!

I am trying to build a tfserving docker image which can run on Inferentia. Your suggestions above won't apply here though.

Can you share one working Dockerfile I can use to build tfserving docker image which runs on Inferentia? 

The [Dockerfile](https://github.com/aws/aws-neuron-sdk/blob/860896cf734d999f1a37ae2edb84ad0149274060/neuron-deploy/docker-example/Dockerfile.tf-serving) in `aws-neuron-sdk` master branch does not compile 

I am following the instructions how to compile the Dockerfile [here](https://github.com/aws/aws-neuron-sdk/blob/860896cf734d999f1a37ae2edb84ad0149274060/neuron-deploy/docker-example/Dockerfile.tf-serving#L6-L7) as well (basically I am running `docker build . -f Dockerfile.tf-serving -t tensorflow-model-server-neuron` as mentioned in the above Dockerfile)

```
# Example tensorflow-model-server-neuron dockerfile.

# Note: tensorflow_model_server_neuron must be pointed at the model location and name using MODEL_BASE_PATH and
# MODEL_NAME env variables. MODEL_BASE_PATH may be an s3 location.

# To build:
#    docker build . -f Dockerfile.tf-serving -t tensorflow-model-server-neuron


FROM amazonlinux:2


# Expose ports for gRPC and REST
EXPOSE 8500 8501

ENV MODEL_BASE_PATH=/models \
    MODEL_NAME=model

RUN echo $'[neuron] \n\
name=Neuron YUM Repository \n\
baseurl=https://yum.repos.neuron.amazonaws.com \n\
enabled=1' > /etc/yum.repos.d/neuron.repo

RUN rpm --import https://yum.repos.neuron.amazonaws.com/GPG-PUB-KEY-AMAZON-AWS-NEURON.PUB

RUN yum install -y tensorflow-model-server-neuron
RUN mkdir -p /root/models/
#copy your model
COPY tf_model/  /root/models/
RUN ls -la /root/models/*

CMD ["/bin/sh", "-c", "/usr/local/bin/tensorflow_model_server_neuron --port=8500 --rest_api_port=8501 --model_name=${MODEL_NAME} --model_base_path=/root/models/${MODEL_NAME}"]
```

**Comment by haitong** [comment]
I found a very old Dockerfile which builds for me 
https://github.com/aws/aws-neuron-sdk/blob/f957e6343aad4a4b3234520f66181bb9e7c65b9f/docs-rtd/neuron-guide/neuron-frameworks/tensorflow-neuron/tutorials/k8s_bert_demo/Dockerfile.tfserving_example

I haven't tried if the docker image is usable

**Comment by micwade-aws** [comment]
@haitong - glad to hear the other docker file worked for you, but still concerned that you got stuck on the first one.  

This error message: `No package tensorflow-model-server-neuron available.` usually indicates that the Neuron YUM Repository is not configured.  Would you mind modifying your dockerfile to list out the yum repos right before the install, try the build again, then pasting back the complete output from your build?

I'm pasting the modified file here with the additional command: `RUN yum repolist all`:

```
# Example tensorflow-model-server-neuron dockerfile.

# Note: tensorflow_model_server_neuron must be pointed at the model location and name using MODEL_BASE_PATH and
# MODEL_NAME env variables. MODEL_BASE_PATH may be an s3 location.

# To build:
#    docker build . -f Dockerfile.tf-serving -t tensorflow-model-server-neuron


FROM amazonlinux:2


# Expose ports for gRPC and REST
EXPOSE 8500 8501

ENV MODEL_BASE_PATH=/models \
    MODEL_NAME=model

RUN echo $'[neuron] \n\
name=Neuron YUM Repository \n\
baseurl=https://yum.repos.neuron.amazonaws.com \n\
enabled=1' > /etc/yum.repos.d/neuron.repo

RUN rpm --import https://yum.repos.neuron.amazonaws.com/GPG-PUB-KEY-AMAZON-AWS-NEURON.PUB
RUN yum repolist all
RUN yum install -y tensorflow-model-server-neuron
RUN mkdir -p /root/models/
#copy your model
COPY tf_model/  /root/models/
RUN ls -la /root/models/*

CMD ["/bin/sh", "-c", "/usr/local/bin/tensorflow_model_server_neuron --port=8500 --rest_api_port=8501 --model_name=${MODEL_NAME} --model_base_path=/root/models/${MODEL_NAME}"]
```

**Comment by haitong** [comment]
@micwade-aws Thanks for the reply! See the output
```
$ docker build . -f Dockerfile.tf-serving -t tensorflow-model-server-neuron
Sending build context to Docker daemon  3.072kB
Step 1/11 : FROM amazonlinux:2
 ---> b142cd55b3b7
Step 2/11 : EXPOSE 8500 8501
 ---> Using cache
 ---> d7d053f12664
Step 3/11 : ENV MODEL_BASE_PATH=/models     MODEL_NAME=model
 ---> Using cache
 ---> 2fb57486c2e7
Step 4/11 : RUN echo $'[neuron] \nname=Neuron YUM Repository \nbaseurl=https://yum.repos.neuron.amazonaws.com \nenabled=1' > /etc/yum.repos.d/neuron.repo
 ---> Using cache
 ---> 6c3fb89ee188
Step 5/11 : RUN rpm --import https://yum.repos.neuron.amazonaws.com/GPG-PUB-KEY-AMAZON-AWS-NEURON.PUB
 ---> Using cache
 ---> 79443b4f0675
Step 6/11 : RUN yum repolist all
 ---> Running in 677d0e2d1853
Loaded plugins: ovl, priorities
https://yum.repos.neuron.amazonaws.com/repodata/9b762af22cf197ff2a1a41761a19d9fc4952d61527b5f978310be07ac9babac0-primary.sqlite.bz2: [Errno 12] Timeout on https://yum.repos.neuron.amazonaws.com/repodata/9b762af22cf197ff2a1a41761a19d9fc4952d61527b5f978310be07ac9babac0-primary.sqlite.bz2: (28, 'Resolving timed out after 5000 milliseconds')
Trying other mirror.

repo id                        repo name                         status
amzn2-core/2/aarch64           Amazon Linux 2 core repository    enabled:  19932
amzn2-core-debuginfo/2/aarch64 Amazon Linux 2 core repository -  disabled
amzn2-core-source/2            Amazon Linux 2 core repository -  disabled
neuron                         Neuron YUM Repository             enabled: 18+212
repolist: 19950
Removing intermediate container 677d0e2d1853
 ---> 3ea17aafad15
Step 7/11 : RUN yum install -y tensorflow-model-server-neuron
 ---> Running in 39b09ac8001a
Loaded plugins: ovl, priorities
No package tensorflow-model-server-neuron available.
Error: Nothing to do
The command '/bin/sh -c yum install -y tensorflow-model-server-neuron' returned a non-zero code: 1
```

**Comment by micwade-aws** [comment]
Heh, really got me on this one for a bit there!  

Problem is that you're attempting to execute the container build from an ARM machine (aarch64), and we don't generate ARM binaries for Neuron (yet!).  Is it possible to switch over to an x86_64 system?

**Comment by haitong** [comment]
I see. I am running it on M1 mac indeed! Just tried on another intel mac and it works! Thanks for the help @micwade-aws!
