### ISSUE TITLE
Do not see any inference time improvement on object detection model.

### ISSUE THREAD

**Issue by whatdhack** [aws/aws-neuron-sdk#54]
Compared the run time of an  uncompiled and a compiled Tensorflow object detection model.  Unlike the example ResNet model (which had about 6x improvement over CPU run time), there is no improvement.  I think the following compile messages probably explains why - **"Number of operations placed on Neuron runtime: 0"** .   Question is why no op is placed on Nuron.  Because of that the whole graph ran in the CPU, and hence no difference. 

```
WARNING:tensorflow:subgraph neuron_op_3830212827f60cb5, tensor pred_sbbox/range0/_0:0: invalid shape (?,)
WARNING:tensorflow:Not fusing subgraph neuron_op_3830212827f60cb5: --io-config error
WARNING:tensorflow:subgraph neuron_op_6e11ec1372c1bd87, tensor upsample1/ResizeNearestNeighbor0/_6:0: invalid shape (?, ?, ?, 128)
WARNING:tensorflow:Not fusing subgraph neuron_op_6e11ec1372c1bd87: --io-config error
WARNING:tensorflow:subgraph neuron_op_a64bf54893aa3612, tensor upsample0/ResizeNearestNeighbor0/_9:0: invalid shape (?, ?, ?, 256)
WARNING:tensorflow:Not fusing subgraph neuron_op_a64bf54893aa3612: --io-config error
WARNING:tensorflow:subgraph neuron_op_6282ae96789270ea, tensor pred_mbbox/range0/_11:0: invalid shape (?,)
WARNING:tensorflow:Not fusing subgraph neuron_op_6282ae96789270ea: --io-config error
WARNING:tensorflow:subgraph neuron_op_7a2c5493ed9a8729, tensor pred_lbbox/range0/_17:0: invalid shape (?,)
WARNING:tensorflow:Not fusing subgraph neuron_op_7a2c5493ed9a8729: --io-config error
INFO:tensorflow:fusing subgraph neuron_op_6ec953b285e9ba28 with neuron-cc
WARNING:tensorflow:Failed to fuse subgraph neuron_op_6ec953b285e9ba28 with '/home/ubuntu/anaconda3/envs/aws_neuron_tensorflow_p36/bin/neuron-cc compile /tmp/tmpqybqolf_/neuron_op_6ec953b285e9ba28/graph_def.pb --framework TENSORFLOW --pipeline compile SaveTemps --output /tmp/tmpqybqolf_/neuron_op_6ec953b285e9ba28/graph_def.neff --io-config "{\"inputs\": {\"input/input_data0/_8:0\": [[1, 416, 416, 3], \"float32\"]}, \"outputs\": [\"darknet/residual10/add:0\", \"darknet/residual18/add:0\", \"conv_lbbox/BiasAdd:0\", \"conv57/LeakyRelu:0\", \"upsample0/ResizeNearestNeighbor/size:0\", \"pred_lbbox/strided_slice:0\", \"pred_lbbox/strided_slice_1:0\"]}"'
INFO:tensorflow:Number of operations in TensorFlow session: 3290
INFO:tensorflow:Number of operations after tf.neuron optimizations: 914
INFO:tensorflow:Number of operations placed on Neuron runtime: 0
INFO:tensorflow:Successfully converted 
```
For comparison, the compile output for the  ResNet50 model is as follows.

```
INFO:tensorflow:fusing subgraph neuron_op_d6f098c01c780733 with neuron-cc
INFO:tensorflow:Number of operations in TensorFlow session: 4638
INFO:tensorflow:Number of operations after tf.neuron optimizations: 556
INFO:tensorflow:Number of operations placed on Neuron runtime: 554
INFO:tensorflow:Successfully converted
```

**Comment by awsrjh** [comment]
Hello and thank you for providing feedback. 

Object detection models are currently a limitation of the Neuron Compiler (please see https://github.com/aws/aws-neuron-sdk/blob/master/release-notes/neuron-cc.md#1046800 ) and thus the behavior of the Tensorflow-Neuron integration is to revert the whole graph to a CPU-only execution. This is why you see that "Number of operations placed on Neuron runtime: 0" as you pointed out.

We are working on this and expect to have support for the additional functions shortly (please see the roadmap here: https://github.com/aws/aws-neuron-sdk/projects/2 . The Issue https://github.com/aws/aws-neuron-sdk/issues/40 tracks this. Please feel free to to add additional information there.

**Comment by aws-taylor** [comment]
Hello whatdhack, 

  Is there any further assistance we can offer at this time? 

Regards,
Taylor

**Comment by whatdhack** [comment]
Any timeline on when you  might release  object detection ( specifically Faster RCNN, Yolo V3 and SSD) support ?

**Comment by aws-taylor** [comment]
Hello whatdhack,

  You can find our roadmap [here](https://github.com/aws/aws-neuron-sdk/projects/2). In particular, notice that [Mask R-CNN](https://github.com/aws/aws-neuron-sdk/issues/40) is high on the priority list. I'd encourage you to to "watch" this issue for the most up-to-date information.

Is there any other help we can offer?

Regards,
Taylor

**Comment by micwade** [comment]
Since we haven’t heard back in a while we are closing this issue, please reopen it if more support from us is needed.

**Comment by whatdhack** [comment]
Hi, any update on  support for object detection models like maskrcnn ?

**Comment by AWSGH** [comment]
We just released a new Neuron version with support for SSD300, and plan to continue expanding our support in the future. Please have a look at: https://github.com/aws/aws-neuron-sdk/blob/master/src/examples/tensorflow/ssd300_demo/README.md
