### ISSUE TITLE
Input size limitations and undocumented compiler args

### ISSUE THREAD

**Issue by davidas1** [aws/aws-neuron-sdk#58]
It was mentioned in the docs that there memory limitations preventing compilation with larger input sizes. Do you plan to improve that, as currently it renders the framework unusable for non-classification tasks.
How can we find out what is the input limit for a specific model?
I'm trying to compile a relatively small model (about 2e6 parameters) and it looks like it fails with input sizes larger that 272x272 (batch size==1)
Are there additional complier args I can set? I saw in the re:invent lab lots of undocumented compiler args used, would be great if you would document them as well.

**Comment by mrnikw** [comment]
Thanks for the question.  The docs [here](https://github.com/aws/aws-neuron-sdk/blob/master/release-notes/neuron-cc.md) document a max size of 480x480 fp/bf16, with batch size=4.  So the use case you are describing should work and be within the capacity of the hardware

Can you share more of your specific use case, or some example code?  Information like which instance type you were using and whether you had any special configuration for the runtime will also help.

On compiler flags:  I am following up with other members of the team.  In some cases (particularly at launch) we wanted to show some features of the hardware not ready for general consumption.  We want you to be able to fully leverage Inferentia, without the experience being confusing or messy!  We also don't want to tease you with functionality you can't use, or won't be able to use soon ...  This is a great question and I'll find out more.  

In this particular case there should be no magic needed, so let's see if we can figure out what is going on.

**Comment by davidas1** [comment]
Thanks for the quick reply.

I'm using the inf1.6xlarge instance for compilation with dlami 26.0, and I didn't make any changes to the runtime (that I know of..).
I did update the packages like described in [DLAMI with Neuron Release Notes](https://github.com/aws/aws-neuron-sdk/blob/5ddbd39f6dc9500fd997044c4bcfbb2e89fcd412/release-notes/dlami-release-notes.md#known-issues)

I'd love to share code for reproducing the issue, but the network architecture I used is confidential.
If possible, I can open a ticket with AWS support and attach the code there.

**Comment by aws-taylor** [comment]
Hello David,

 If you could open an AWS support issue with the attached network we would be happy to investigate further.

Regards,
Taylor

**Comment by davidas1** [comment]
Thanks, I opened an issue with case ID 6733794191

**Comment by aws-taylor** [comment]
Thanks David,

 We will follow up on the support issue.

Regards,
Taylor
