### ISSUE TITLE
Compilation error: aten::size not supported

### ISSUE THREAD

**Issue by gilbahat** [aws/aws-neuron-sdk#66]
(test_venv) root@ip-10-0-108-116:~/midas# python3 run.py
Traceback (most recent call last):
  File "run.py", line 75, in <module>
    run(INPUT_PATH, OUTPUT_PATH, MODEL_PATH)
  File "run.py", line 27, in run
    model_neuron = torch.neuron.trace(model, example_inputs=[image])
  File "/root/test_venv/lib/python3.5/site-packages/torch_neuron/decorators.py", line 165, in trace
    tensor_outputs = _resolve_func(node)(op, *tensor_inputs)
  File "/root/test_venv/lib/python3.5/site-packages/torch_neuron/decorators.py", line 826, in _resolve_func
    assert hasattr(module, func_name), "Neuron compile failed.  Operator {}::{} is not supported".format(mod_name,func_name)
AssertionError: Neuron compile failed.  Operator aten::size is not supported

**Comment by micwade** [comment]
Hi, gilbahat.

The operator aten::size is not currently supported by torch-neuron.  A list of the current supported operators can be found here:
https://github.com/aws/aws-neuron-sdk/blob/master/release-notes/neuron-cc-ops/neuron-cc-ops-pytorch.md

We are continuing to expand our operator support and will specifically have support for aten::size in a coming release of torch-neuron.  We will also fix the missing operator name in the error messages asap.

In the meantime, you can manually partition out the model to instruct the framework to run that specific part of the model with aten::size on the instance vCPU, while other parts of the model will still be accelerated on the Inferentia.  A tutorial on this is available here:
https://github.com/aws/aws-neuron-sdk/blob/master/docs/pytorch-neuron/tutorial-manual-partitioning.md

Mike
