### ISSUE TITLE
Problem compiling a BASNet network

### ISSUE THREAD

**Issue by gilbahat** [aws/aws-neuron-sdk#67]
RuntimeError: Only tensors or tuples of tensors can be output from traced functions (getOutput at /opt/workspace/KaenaPyTorchBase/build/private/pytorch/torch/csrc/jit/tracer.cpp:209)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x47 (0x7ff41318ba07 in /root/test_venv/lib/python3.5/site-packages/torch/lib/libc10.so)
frame #1: torch::jit::tracer::TracingState::getOutput(c10::IValue const&) + 0x362 (0x7ff3fb9a8572 in /root/test_venv/lib/python3.5/site-packages/torch/lib/libtorch.so)
frame #2: torch::jit::tracer::exit(std::vector<c10::IValue, std::allocator<c10::IValue> > const&) + 0x3c (0x7ff3fb9a876c in /root/test_venv/lib/python3.5/site-packages/torch/lib/libtorch.so)
frame #3: <unknown function> + 0x5e853c (0x7ff3fe52653c in /root/test_venv/lib/python3.5/site-packages/torch/lib/libtorch_python.so)
frame #4: <unknown function> + 0x5fd260 (0x7ff3fe53b260 in /root/test_venv/lib/python3.5/site-packages/torch/lib/libtorch_python.so)
frame #5: <unknown function> + 0x374625 (0x7ff3fe2b2625 in /root/test_venv/lib/python3.5/site-packages/torch/lib/libtorch_python.so)
<omitting python frames>
frame #8: python3() [0x539a13]
frame #11: python3() [0x4e3537]
frame #14: python3() [0x539f5f]
frame #17: python3() [0x539a13]
frame #19: python3() [0x6292c2]
frame #24: __libc_start_main + 0xf0 (0x7ff4174ea830 in /lib/x86_64-linux-gnu/libc.so.6)

**Comment by micwade** [comment]
Hi, gilbahat.

The reported error appears to be related to torch.jit.trace failing to generate torchscript from your code.  If you can share more information and/or sample code to help us recreate the error, that would be very helpful.  We can coordinate any confidential exchanges via aws-neuron-support@amazon.com.

Thanks,
Mike

**Comment by micwade** [comment]
Since we haven’t heard back in a while we are closing this issue, please reopen it if more support from us is needed.
