### ISSUE TITLE
Can't profile with different resolution

### ISSUE THREAD

**Issue by mbuckler** [aws/aws-neuron-sdk#77]
I am attempting to profile ResNet50 with a resolution of 640x480. I am able to generate trace files with 224x224, but I am unable to do so for 640x480. The include_top option is False for both 224x224 and 640x480 resolution networks, and compilation seems to complete OK for both. This issue is possibly due to the resolution limitations described [here](https://github.com/aws/aws-neuron-sdk/issues/58) and [here](https://github.com/aws/aws-neuron-sdk/issues/35). I have attached my log and a tar file of my code.

[resnet50_files.tar.gz](https://github.com/aws/aws-neuron-sdk/files/4156906/resnet50_files.tar.gz)
[lack_of_trace.txt](https://github.com/aws/aws-neuron-sdk/files/4156907/lack_of_trace.txt)

**Comment by awsrjh** [comment]
Hi and thanks for the data - it will help us to debug .

we will come back to you on this.

**Comment by micwade** [comment]
Hi, mbuckler.
 
At the moment the maximum input size supported by the Neuron Compiler for CNN models is 480x480 (see “Known issues and limitations” here: https://github.com/aws/aws-neuron-sdk/blob/master/release-notes/neuron-cc.md#known-issues-and-limitations-3).  In this particular issue, the input size is 640x480 which exceeds our current limit.  When exceeding the limit, the compiler will place all the operations on the instance CPUs instead on the Inferentias. In addition the Neuron profiler does not yet support profiling of CPU operations.  The result is a lack of trace output from profiling.
 
In a future release we plan to increase the 480x480 input limit, as well as, add support for CPU operation profiling.  Please keep an eye out for those updates.
 
Thanks,
Mike
