### ISSUE TITLE
Getting a WARN about optimize having no effects on pytorch

### ISSUE THREAD

**Issue by Damiox** [aws/aws-neuron-sdk#87]
Following the tutorial for pytorch (https://github.com/aws/aws-neuron-sdk/blob/master/docs/pytorch-neuron/tutorial-compile-infer.md) is showing the following WARNING when running `python trace_resnet50.py`:

```
/home/prod/neuron/lib/python3.5/site-packages/torch/jit/__init__.py:847: UserWarning: `optimize` is deprecated and has no effect. Use `with torch.jit.optimized_execution() instead
  warnings.warn("`optimize` is deprecated and has no effect. Use `with torch.jit.optimized_execution() instead")
```

Is this something that it's just fine? does it need to be fixed?

**Comment by aws-renfu** [comment]
We’re going to take a look into this soon. You can also file AWS support ticket or contact us directly at aws-neuron-support@amazon.com.

**Comment by mrnikwaws** [comment]
Hi Damiox,  

Thanks for reporting this issue.  We’ve been able to reproduce the issue and we’ll ship the fix in a future version of the of Neuron-torch.  It has no impact on your compilation, please let us know if you have any additional concern

**Comment by mrnikwaws** [comment]
I'm going to close this issue.  Feel free to reopen if you have concerns
