### ISSUE TITLE
neuron-cc: `--verbose` instead of `--log-level`?

### ISSUE THREAD

**Issue by kcy1019** [aws/aws-neuron-sdk#94]
### Problem

[The reference guide][ref1] states `--log-level` option can adjust the log level, whose default is `INFO`. However, `neuron-cc` does not understand the option(`neuron-cc compile: error: unrecognized arguments: --log-level=INFO`).

### Feedback

The correct option is `--verbose=INFO` and the default is `ERROR`, not `INFO`.

### Version Info

```
Neuron Compiler version 1.0.7878.0+6004821168

HWM version 1.0.897.0-6002947737
NEFF version 0.6
TVM version 1.0.1826.0+6004211132
NumPy version 1.17.2
MXNet not available
TF version 1.15.0
ONNX version 1.6.0
```

[ref1]: https://github.com/aws/aws-neuron-sdk/blob/master/docs/neuron-cc/command-line-reference.md#common-options

**Comment by micwade-aws** [comment]
Thanks for calling it out, kcy1019.  A fix to the documentation is on its way (#96).
